define("callTreeViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,o,i,l)=>{return a={9442:e=>{const t=document.createElement("script");t.id="CallTreeRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBleHBhbmRhYmxlID8gJ3Zpc2libGUnIDogJ2hpZGRlbicgfSI+PC9kaXY+DQogICAgICAgIDxkaXYgY2xhc3M9ImhvdEhpZ2hsaWdodCIgZGF0YS1iaW5kPSJjc3M6IHsgaG90UGF0aDogJHBhcmVudC5zaG93SG90UGF0aEhpZ2hsaWdodGluZygpICYmIGlzSG90UGF0aCgpLCBob3RJdGVtOiAkcGFyZW50LnNob3dIb3RQYXRoSGlnaGxpZ2h0aW5nKCkgJiYgaXNIb3RJdGVtKCkgfSI+PC9kaXY+DQogICAgICAgIDxkaXYgY2xhc3M9InR5cGVJY29uIiBkYXRhLWJpbmQ9ImNzczogeyB2YWx1ZUNvbGxlY3Rpb25UeXBlOiBpc1ZhbHVlQ29sbGVjdGlvblR5cGUsIHJlZkNvbGxlY3Rpb25UeXBlOiBpc1JlZkNvbGxlY3Rpb25UeXBlLCB2YWx1ZVR5cGU6IGlzVmFsdWVUeXBlLCByZWZUeXBlOiBpc1JlZlR5cGUgfSI+PC9kaXY+DQogICAgICAgIDxzcGFuIGNsYXNzPSJ0cmVlR3JpZENlbGwtbGFiZWwiIGRhdGEtYmluZD0idGV4dDogbGFiZWwiPjwvc3Bhbj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBuYW1lIj48L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkVG90YWwiIGRhdGEtY29sdW1uaWQ9InRvdGFsIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRTZWxmIiBkYXRhLWNvbHVtbmlkPSJzZWxmIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRUb3RhbFNpemUiIGRhdGEtY29sdW1uaWQ9InRvdGFsU2l6ZSI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkU2VsZlNpemUiIGRhdGEtY29sdW1uaWQ9InNlbGZTaXplIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRBdmVyYWdlU2l6ZSIgZGF0YS1jb2x1bW5pZD0iYXZlcmFnZVNpemUiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWNvbHVtbmlkPSJtb2R1bGVOYW1lIiBkYXRhLWJpbmQ9InRleHQ6IG1vZHVsZU5hbWUiPjwvdGQ+DQo8L3RyPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},6680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},4103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},4956:e=>{const t=document.createElement("script");t.id="SearchControlView",t.innerHTML=atob("PGRpdiBjbGFzcz0iY29udGFpbmVyIHNlYXJjaC1jb250YWluZXIiIGRhdGEtYmluZD0iY3NzOiB7IGNvbnRyb2xEaXNhYmxlZDogaXNEaXNhYmxlZCgpLCBjb250cm9sRW5hYmxlZDogIWlzRGlzYWJsZWQoKSB9LCBhdHRyOiB7ICdhcmlhLWRpc2FibGVkJzogaXNEaXNhYmxlZCB9LCB0ZW1wbGF0ZTogeyBhZnRlclJlbmRlcjogb25BZnRlckRvbUluc2VydCB9Ij4NCiAgICA8ZGl2IGNsYXNzPSJzZWFyY2gtY29udHJvbCIgZGF0YS1iaW5kPSJjc3M6IHsgaGFzRm9jdXM6IGhhc0ZvY3VzKCkgfSI+DQogICAgICAgIDxpbnB1dCB0eXBlPSJzZWFyY2giIGRhdGEtYmluZD0iDQogICAgICAgICAgICAgICBkaXNhYmxlOiBpc0Rpc2FibGVkLA0KICAgICAgICAgICAgICAgdGV4dElucHV0OiBzZWFyY2hUZXJtLA0KICAgICAgICAgICAgICAgZm9jdXM6IHNlYXJjaElucHV0SGFzRm9jdXMsDQogICAgICAgICAgICAgICB2YWx1ZVVwZGF0ZTogJ2FmdGVya2V5ZG93bicsDQogICAgICAgICAgICAgICBsb2NhbGl6ZWRQbGFjZWhvbGRlclRleHQ6ICdTZWFyY2hXYXRlcm1hcmsnLA0KICAgICAgICAgICAgICAgZXZlbnQ6IHsga2V5ZG93bjogb25TZWFyY2hCb3hLZXlEb3duLCBjbGljazogY2xvc2VBdXRvQ29tcGxldGVMaXN0cyB9LA0KICAgICAgICAgICAgICAgYXR0cjogeyAnYXJpYS1sYWJlbCc6IGFyaWFMYWJlbCB9IiAvPg0KICAgICAgICA8ZGl2IGNsYXNzPSJzZWFyY2gtc3VibWl0LWJ1dHRvbiIgZGF0YS1iaW5kPSJjbGljazogb25DbGljaywgZm9jdXM6IHNlYXJjaFN1Ym1pdEhhc0ZvY3VzLCBsb2NhbGl6ZWRBcmlhTGFiZWw6ICdTZWFyY2hJY29uQXJpYUxhYmVsJywgc3ZnSW1hZ2U6ICdkaWFnbm9zdGljc0h1Yi1zZWFyY2gnIj48L2Rpdj4NCiAgICAgICAgPGRpdiBpZD0ic2VhcmNoLW9wdGlvbnMtYnV0dG9uIiBjbGFzcz0iZHJvcGRvd24tYnV0dG9uIiBkYXRhLWJpbmQ9ImNsaWNrOiBvbkRyb3BEb3duQ2xpY2siPjwvZGl2Pg0KICAgIDwvZGl2Pg0KICAgIDxkaXYgaWQ9InNlYXJjaE9wdGlvbnNGbHlvdXQiIGRhdGEtYmluZD0iY3NzOiB7IGZseW91dEFjdGl2ZTogc2hvd1NldHRpbmdzKCkgfSwgZXZlbnQ6IHsga2V5ZG93bjogb25GbHlvdXRLZXlEb3duIH0iPg0KICAgICAgICA8c3BhbiBjbGFzcz0iZmx5b3V0SGVhZGVyIiBkYXRhLWJpbmQ9ImxvY2FsaXplZFRleHQ6ICdTZWFyY2hPcHRpb25zVGl0bGUnIj48L3NwYW4+DQogICAgICAgIDxsYWJlbCBjbGFzcz0icmVnRXhTZXR0aW5nIiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgICAgY3NzOiB7IGhhc0ZvY3VzOiBpc1JlZ3VsYXJFeHByZXNzaW9uSGFzRm9jdXMoKSB9LA0KICAgICAgICAgICAgZXZlbnQ6IHsgbW91c2VlbnRlcjogZnVuY3Rpb24odmlld01vZGVsKSB7IHZpZXdNb2RlbC5pc1JlZ3VsYXJFeHByZXNzaW9uSGFzRm9jdXModHJ1ZSk7IH0gfSI+DQogICAgICAgICAgICA8aW5wdXQgdHlwZT0iY2hlY2tib3giDQogICAgICAgICAgICAgICAgICAgZGF0YS1iaW5kPSJjaGVja2VkOiBpc1JlZ3VsYXJFeHByZXNzaW9uLCBmb2N1czogaXNSZWd1bGFyRXhwcmVzc2lvbkhhc0ZvY3VzLA0KICAgICAgICAgICAgICAgICAgICBsb2NhbGl6ZWRBcmlhTGFiZWw6ICdTZWFyY2hSZWd1bGFyRXhwcmVzc2lvbicsDQogICAgICAgICAgICAgICAgICAgIGF0dHI6IHsgJ2FyaWEtY2hlY2tlZCc6IGlzUmVndWxhckV4cHJlc3Npb24oKSB9IiAvPg0KICAgICAgICAgICAgPHNwYW4gY2xhc3M9ImNoZWNrYm94TGFiZWwiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ1NlYXJjaFJlZ3VsYXJFeHByZXNzaW9uJyI+PC9zcGFuPg0KICAgICAgICA8L2xhYmVsPg0KICAgICAgICA8bGFiZWwgY2xhc3M9ImNhc2VTZW5zaXRpdmVTZXR0aW5nIiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgICAgY3NzOiB7IGhhc0ZvY3VzOiBpc0Nhc2VTZW5zaXRpdmVIYXNGb2N1cygpIH0sDQogICAgICAgICAgICBldmVudDogeyBtb3VzZWVudGVyOiBmdW5jdGlvbih2aWV3TW9kZWwpIHsgdmlld01vZGVsLmlzQ2FzZVNlbnNpdGl2ZUhhc0ZvY3VzKHRydWUpOyB9IH0iPg0KICAgICAgICAgICAgPGlucHV0IHR5cGU9ImNoZWNrYm94Ig0KICAgICAgICAgICAgICAgICAgIGRhdGEtYmluZD0iY2hlY2tlZDogaXNDYXNlU2Vuc2l0aXZlLCBmb2N1czogaXNDYXNlU2Vuc2l0aXZlSGFzRm9jdXMsDQogICAgICAgICAgICAgICAgICAgIGxvY2FsaXplZEFyaWFMYWJlbDogJ1NlYXJjaENhc2VTZW5zaXRpdmUnLA0KICAgICAgICAgICAgICAgICAgICBhdHRyOiB7ICdhcmlhLWNoZWNrZWQnOiBpc0Nhc2VTZW5zaXRpdmUoKSB9IiAvPg0KICAgICAgICAgICAgPHNwYW4gY2xhc3M9ImNoZWNrYm94TGFiZWwiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ1NlYXJjaENhc2VTZW5zaXRpdmUnIj48L3NwYW4+DQogICAgICAgIDwvbGFiZWw+DQogICAgPC9kaXY+DQogICAgPCEtLSBrbyBpZjogaXNBdXRvY29tcGxldGVFbmFibGVkIC0tPg0KICAgIDwhLS0ga28gdGVtcGxhdGU6IHsgbmFtZTogJ0F1dG9Db21wbGV0ZVZpZXcnLCBkYXRhOiBhdXRvQ29tcGxldGVWaWV3TW9kZWwgfSAtLT48IS0tIC9rbyAtLT4NCiAgICA8IS0tIC9rbyAtLT4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},4423:function(e,t,o){var i,l,a=this&&this.__createBinding||(Object.create?function(e,t,o,i){void 0===i&&(i=o),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[o]}})}:function(e,t,o,i){void 0===i&&(i=o),e[i]=t[o]}),s=this&&this.__exportStar||function(e,t){for(var o in e)"default"===o||Object.prototype.hasOwnProperty.call(t,o)||a(t,e,o)};i=[o,t,o(5226),o(3028),o(9371),o(4881),o(4881),o(4881),o(4881),o(2560),o(8117),o(8117),o(8117),o(8117),o(8117),o(4881),o(952),o(3766),o(5758),o(7886),o(2027),o(1521),o(118),o(4881),o(4881),o(4881),o(4881),o(6680),o(833),o(4956),o(4103)],l=function(e,t,o,i,l,a,r,n,c,d,h,g,u,I,C,m,p,b,A,v,_,w,G,R,T,S,Z){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getCallTreeViewModel=t.CallTreeViewModel=void 0,s(l,t);class Y{constructor(){this._marshaler=new b.DotNetObjectAllocMarshaler,this._telemetry=new A.DotNetObjectAllocTelemetryMarshaler,this._logger=g.getLogger("CallTreeViewModel"),this._isOverlayActive=i.pureComputed((()=>null!==this._currentOverlay())),this._currentOverlay=i.pureComputed((()=>this.computeOverlay())),this._automation=u.getAutomationManager(this._logger),this._viewEventManager=I.getViewEventManager(),h.loadDataWarehouse().then((e=>(this._dataWarehouse=e,this._dataWarehouse.getContextService().getGlobalContext()))).then((e=>Promise.all([this._dataWarehouse.getJmcService().getJmcEnabledState(),e.getTimeDomain(),this._marshaler.isNativeCodeFoldingEnabled()]))).then((e=>{const[t,l,s]=e;this._showJmc=new T.ToggleButtonViewModel(void 0,void 0,"ShowJmc","ShowJmc"),this._showJmc.isChecked(t),this._showJmc.isChecked.subscribe((()=>{this._dataWarehouse.getJmcService().setJmcEnabledState(this._showJmc.isChecked())})),this._showNative=new T.ToggleButtonViewModel(void 0,void 0,"ShowNative","ShowNative"),this._showNative.isChecked(!s),this._showNative.isChecked.subscribe((()=>{this._marshaler.setNativeCodeFoldingEnabled(!this._showNative.isChecked()),this._callTree.onResultChanged(0)})),this._marshaler.onUpdateNativeCodeFolding.addEventListener((e=>this._showNative.isChecked(!e.isEnabled))),this._marshaler.onCrossReferenceEvent.addEventListener((e=>this.crossReferenceEvent(e))),this._dao=new _.CallTreeDAO(this._dataWarehouse,l,this._marshaler);const c=o.Resources.getString,d=new n.TreeGridHeaderViewModel([{id:"name",text:c("HeaderName"),tooltip:c("HeaderNameToolTip"),hideable:!1,sortable:a.SortDirection.Asc},{id:"total",text:c("CallTreeHeaderTotalAllocCount"),tooltip:c("HeaderTotalAllocCountToolTipFunction"),hideable:!0,sortable:a.SortDirection.Desc},{id:"self",text:c("CallTreeHeaderSelfAllocCount"),tooltip:c("CallTreeHeaderSelfAllocCountToolTip"),hideable:!0,sortable:a.SortDirection.Desc},{id:"totalSize",text:c("CallTreeHeaderTotalAllocSize"),tooltip:c("CallTreeHeaderTotalAllocSizeToolTip"),hideable:!0,sortable:a.SortDirection.Desc},{id:"selfSize",text:c("CallTreeHeaderSelfAllocSize"),tooltip:c("CallTreeHeaderSelfAllocSizeToolTip"),hideable:!0,sortable:a.SortDirection.Desc},{id:"averageSize",text:c("HeaderAverageSize"),tooltip:c("HeaderAverageSizeToolTipFunction"),hideable:!0},{id:"moduleName",text:c("HeaderModuleName"),tooltip:c("HeaderModuleNameToolTip"),hideable:!0,sortable:a.SortDirection.Desc}],new G.DotNetObjectAllocColumnSettingsProvider("CallTreeView"),this._dao.defaultSortColumnId);this._callTree=new r.TreeGridViewModel(this._dao,d,"CallTreeAriaLabel"),this._expandHotPathButton=new Z.ToolbarButtonViewModel("hotItemIcon","CallTree_ExpandHotPathButtonText","CallTree_ExpandHotPathAriaLabel",(()=>{this.expandHotPath()})),this._showHotPathToggleButton=new T.ToggleButtonViewModel("hotPathIcon","hotPathDisabledIcon","CallTree_ShowPathButtonText","CallTree_ShowHotPathAriaLabel"),this._showHotPathToggleButton.isChecked(!0),this._callTree.showHotPathHighlighting=this._showHotPathToggleButton.isChecked,this._callTree.roots.subscribe((()=>{this.showHotPathToggleButton.isChecked()&&this.expandHotPath()})),this._callTree.onResultChanged(0),this._viewEventManager.selectionChanged.addEventListener((e=>{e.isIntermittent||this._dao.timeFilter(e.position)})),this._dao.timeFilter.subscribe((()=>this._callTree.onResultChanged(0))),this._viewEventManager.jmcEnabledStateChanged.addEventListener((e=>{this.showJmc.isChecked(e.currEnabledState),this._callTree.onResultChanged(0)}));const h=new R.AutoCompleteViewModel(null,this._dao.getAutoCompleteSuggestions.bind(this._dao));return this._searchViewModel=new S.SearchControlViewModel(this._callTree,!1,o.Resources.getString("DotNetAllocSearchControlAriaLabel"),this._telemetry,h),this._isOverlayActive.subscribe((e=>{this._searchViewModel.isDisabled(e)})),i.applyBindings(this),this._viewEventManager.detailsViewReady.raiseEvent({Id:p.CallTreeDetailsViewId()}),this._callTree.dataLoadPromise})).then((()=>{this.expandHotPath()}))}get callTree(){return this._callTree}get showJmc(){return this._showJmc}get showNative(){return this._showNative}get searchViewModel(){return this._searchViewModel}get currentOverlay(){return this._currentOverlay}get showHotPathToggleButton(){return this._showHotPathToggleButton}get expandHotPathButton(){return this._expandHotPathButton}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==d.KeyCodes.C)return!0;const o=c.TreeGridUtils.formatTreeGridSelectedToText(this._callTree);return navigator.clipboard.writeText(o),!1}contextMenu(e,t){if("number"!=typeof e.id)return null;const i=t=>{const o=()=>{this._marshaler.crossReference({rowId:t===v.ToolView.Allocations?e.typeId:e.AggregationId,rowType:e.rowType,viewToShow:t})},i=e=>{this._viewEventManager.selectDetailsView(e).then((()=>{o();const t=i=>{i.Id===e&&(o(),this._viewEventManager.detailsViewReady.removeEventListener(t))};this._viewEventManager.detailsViewReady.addEventListener(t)}))};switch(t){case v.ToolView.FunctionsListView:i(p.FunctionListDetailsViewId());break;case v.ToolView.Allocations:i(p.AllocationDetailsViewId())}},l=()=>{const t=e;this._telemetry.goToSourceUsed(),t.sourceFilePosition&&("unsearched"===t.sourceFilePosition.sourceFile.path.toLowerCase()?this._dao.getSourceInfo(t.AggregationId).then((e=>{t.sourceFilePosition=e,e?C.getSourceFileViewerService().openSourcePosition(t.sourceFilePosition):this._automation.getAlertPromise(u.AutomationConstants.DataWarehouseRequestKey,o.Resources.getString("NoSource"))})):C.getSourceFileViewerService().openSourcePosition(t.sourceFilePosition))};let a;a=!e.expandable||e.isExpandableAllocationRow?{label:o.Resources.getString("ContextMenu_ShowInAllocations"),callback:()=>i(v.ToolView.Allocations),disabled:()=>e.isExpandableAllocationRow,type:o.ContextMenu.MenuItemType.command}:{label:o.Resources.getString("ContextMenu_ShowInFunctions"),callback:()=>i(v.ToolView.FunctionsListView),type:o.ContextMenu.MenuItemType.command};const s=[a,{label:o.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>l(),disabled:()=>!e.sourceFilePosition,type:o.ContextMenu.MenuItemType.command},{label:o.Resources.getString("ContextMenu_ExpandHotPath"),callback:()=>this.expandHotPath(),type:o.ContextMenu.MenuItemType.command},{type:o.ContextMenu.MenuItemType.separator},{label:o.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToText(this._callTree);navigator.clipboard.writeText(e)},type:o.ContextMenu.MenuItemType.command},{label:o.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToMarkdown(this._callTree);navigator.clipboard.writeText(e)},type:o.ContextMenu.MenuItemType.command}];return o.ContextMenu.create(s)}computeOverlay(){return this._callTree.dataLoadStatus()===a.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._callTree.dataLoadStatus()===a.DataLoadEvent.DataLoadCompleted&&0===this._callTree.treeAsArray().length?{name:"MessageView",data:o.Resources.getString("NoAllocationDataMessage")}:this._callTree.dataLoadStatus()===a.DataLoadEvent.DataLoadFailed?{name:"MessageView",data:o.Resources.getString("UnableShowDataMessage")}:null}crossReferenceEvent(e){e.viewToShow===v.ToolView.CallTreeView&&(this._telemetry.crossReferenceUsed(),this._marshaler.clearGraphHighlight(),this._callTree.dataLoadPromise.then((()=>this._dao.getNodePath(e.rowId,e.rowType))).then((e=>c.TreeGridUtils.expandNodePath(this._callTree,this._dao,e))).then((e=>{if(null!==e)c.TreeGridUtils.selectRow(this._callTree,e),this._marshaler.clearGraphHighlight(),this._marshaler.updateGraphHighlight(e.id);else{const e=o.Resources.getString("NoRowMessage");this._automation.getAlertPromise(u.AutomationConstants.DataWarehouseRequestKey,e)}}),(t=>{this._logger.error(`Unable to navigate to RowId: ${e.rowId} RowType: ${e.rowType}`),this._logger.error(t.message)})))}expandHotPath(){this._telemetry.hotPathUsed();let e=this._callTree.focusedRow();if(e=e||this._callTree.roots()[0],!e)return Promise.resolve();if(e.rowType===a.RowType.Allocation)return e.expanded()||this._dao.expand(e,this._callTree.header.sortInfo()),Promise.resolve();this._callTree.treeAsArray().forEach((e=>{e instanceof w.CallTreeRowViewModel&&(e.isHotPath(!1),e.isHotItem(!1))}));let t=e?[e]:this._callTree.roots();const o=l=>{const a=l.shift();for(let o=0;o<t.length;++o)if(e=t[o],e.id===a.id){e.isHotItem(a.hi),e.isHotPath(a.hp);break}return l.length>0?a.f?e.expanded()?(t=e.children(),o(l)):this._dao.expand(e,this._callTree.header.sortInfo()).then((()=>{t=e.children()})).then((()=>o(l))):o(l):(i.tasks.schedule((()=>{const t=this._callTree.treeAsArray().indexOf(e);-1!==t&&this._callTree.selectedRows([t])})),Promise.resolve())};return this._dao.getHotPath(e,e.rowType).then((e=>o(e))).then((()=>{this._showHotPathToggleButton.isEnabled(!0),this._showHotPathToggleButton.isChecked(!0)}))}}let y;t.CallTreeViewModel=Y,(new b.DotNetObjectAllocMarshaler).getDoubleClickTimeMs().then((e=>{m.Init(e),y=new Y})),t.getCallTreeViewModel=function(){return y}}.apply(t,i),void 0===l||(e.exports=l)},2027:(e,t,o)=>{var i,l;i=[o,t,o(3028),o(4881),o(4881),o(952),o(8558),o(1521)],l=function(e,t,o,i,l,a,s,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CallTreeDAO=void 0;class n{constructor(e,t,i){this._jmcEnabled=!0,this._nativeEnabled=!0,this._dataWarehouse=e,this._timeFilter=o.observable(t),this._timeFilter.equalityComparer=s.areTimespansEqual,this._marshaler=i}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"totalSize"}getAutoCompleteSuggestions(e,t){return this._currentResult?this._currentResult.getResult({task:"autocomplete",filter:e,count:10},t).then((e=>e.filter((e=>(!this._jmcEnabled||this._jmcEnabled&&e.j===i.JmcState.UserCode)&&(this._nativeEnabled||!e.n))).map((e=>e.t)))):Promise.resolve([])}getNodePath(e,t){return this._currentResult.getResult({task:"getData",rowId:e,rowType:t})}getSourceInfo(e){return this._currentResult.getResult({task:"getSourceInfo",rowId:e})}getRoots(e,t,o){return this._marshaler.isNativeCodeFoldingEnabled().then((e=>(o?.throwIfCancellationRequested(),this._nativeEnabled=!e,{timeDomain:this.timeFilter(),customDomain:{view:"CallTree",FoldNativeFrames:e?"true":"false"}}))).then((e=>(o?.throwIfCancellationRequested(),this._dataWarehouse.getFilteredData(e,a.DotNetAllocAnalyzerId(),o)))).then((e=>{o?.throwIfCancellationRequested(),this._currentResult&&this._currentResult.dispose();const t=this._dataWarehouse.getJmcService().getJmcEnabledState();this._currentResult=e;const i=this._currentResult?this._currentResult.getResult({task:"getRoots"},o):Promise.resolve([]);return Promise.all([i,t])})).then((e=>{o?.throwIfCancellationRequested();const[i,l]=e;this._jmcEnabled=l;const a=i.map((e=>new r.CallTreeRowViewModel(null,e,0,l)));return this.sort(a,t,o),1===a.length?this.expand(a[0],t,o).then((()=>a)):Promise.resolve(a)}))}expand(e,t,o){return e.expand(this._currentResult,t,o)}search(e,t,o,i,l,a,s){const r=l?l.getIdPath():[];return this._currentResult.getResult({task:"search",selectedPath:r,str:e,caseSensitive:t,isRegex:o,isForward:i},s)}sort(e,t,o){const i=n.SortFunc[t.columnId](t.direction),l=e=>{e.children&&(e.children.sort(i),e.children().forEach(l))};return this._currentResult.getResult({task:"sort",column:t.columnId,direction:t.direction},o).then((()=>(e.sort(i),e.forEach(l),e)))}getHotPath(e,t,o){return this._currentResult.getResult({view:"CallTree",task:"expandHotPath",rowId:e.id,rowType:t},o)}}t.CallTreeDAO=n,n.SortFunc={name:e=>l.SortFunctions.stringSort("name",e),total:e=>l.SortFunctions.numericSort("total",e),self:e=>l.SortFunctions.numericSort("self",e),moduleName:e=>l.SortFunctions.stringSort("moduleName",e),totalSize:e=>l.SortFunctions.numericSort("totalSize",e),selfSize:e=>l.SortFunctions.numericSort("selfSize",e),averageSize:e=>l.SortFunctions.numericSort("averageSize",e)}}.apply(t,i),void 0===l||(e.exports=l)},1521:(e,t,o)=>{var i,l;i=[o,t,o(3028),o(5226),o(4881),o(9442)],l=function(e,t,o,i,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CallTreeRowViewModel=void 0;class a{constructor(e,t,i,l){this._selected=o.observable(!1),this._expanded=o.observable(!1),this._haveLoaded=!1,this._isHotPath=o.observable(!1),this._isHotItem=o.observable(!1),this._isHotRoot=o.observable(!1),this._parent=e,this._dto=t,this._depth=i,this._children=o.observableArray([]),this._jmcEnabled=l,this._label=o.pureComputed((()=>this.computeLabel()))}get templateName(){return"CallTreeRowView"}get id(){return this._dto.id}get rowType(){return this._dto.rt}get isHotPath(){return this._isHotPath}get isHotItem(){return this._isHotItem}get isHotRoot(){return this._isHotRoot}get name(){return this._dto.rt===l.RowType.Process?this._dto.n?i.Resources.getString("ProcessNameFormat",this._dto.n,this._dto.pid):i.Resources.getString("ProcessIdFormat",this._dto.pid):this.isExpandableAllocationRow?"":this._dto.n}get isValueCollectionType(){return!this.expandable&&this._dto.ia&&this._dto.iv}get isRefCollectionType(){return!this.expandable&&this._dto.ia&&!this._dto.iv}get isValueType(){return!this.expandable&&!this._dto.ia&&this._dto.iv}get isRefType(){return!this.expandable&&!this._dto.ia&&!this._dto.iv}get label(){return this._label}computeLabel(){if(this._dto.rt===l.RowType.Process)return"";if(this._dto.a===l.AggregateType.BrokenStack)return i.Resources.getString("UnwalkableStackLabel");if(!this._jmcEnabled)switch(this._dto.a){case l.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");case l.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");default:return this.isExpandableAllocationRow?i.Resources.getString("AllocationsLabel"):this.expandable?"":i.Resources.getString("TypesLabel")}if(this._dto.n)switch(this._dto.j){case l.JmcState.SystemCode:return i.Resources.getString("SystemCallLabel");case l.JmcState.LibraryCode:return i.Resources.getString("ExternalCallLabel")}switch(this._dto.a){case l.AggregateType.SystemCode:return i.Resources.getString("SystemCodeLabel");case l.AggregateType.JmcRejected:return i.Resources.getString("ExternalCodeLabel");case l.AggregateType.AsyncMethod:return i.Resources.getString("AsyncMethodLabel");case l.AggregateType.Native:return i.Resources.getString("FoldedNativeLabel");default:return this.isExpandableAllocationRow?i.Resources.getString("AllocationsLabel"):this.expandable?"":i.Resources.getString("TypesLabel")}}get total(){return this._dto.rt===l.RowType.Allocation?null:this._dto.t}get localizedTotal(){return this.total?this.total.toLocaleString(i.Culture.formatRegion):""}get self(){return this._dto.s}get localizedSelf(){return this.self.toLocaleString(i.Culture.formatRegion)}get totalSize(){return this._dto.rt===l.RowType.Allocation?null:this._dto.ts}get localizedTotalSize(){return this.totalSize?this.totalSize.toLocaleString(i.Culture.formatRegion):""}get selfSize(){return this._dto.ss}get localizedSelfSize(){return this.selfSize.toLocaleString(i.Culture.formatRegion)}get averageSize(){return this.expandable?null:this._dto.ss/this._dto.s}get localizedAverageSize(){return this.averageSize?this.averageSize.toLocaleString(i.Culture.formatRegion,{maximumFractionDigits:2}):""}get sourceFilePosition(){return this._dto.sfp}set sourceFilePosition(e){this._dto.sfp=e}get AggregationId(){return this._dto.aId}get typeId(){return this._dto.ty?this._dto.ty:-1}get moduleName(){switch(this._dto.mc){case 0:return i.Resources.getString("UnknownModuleLabel");case 1:return this._dto.mn;default:return i.Resources.getString("MultipleModuleLabel")}}get depth(){return this._depth}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return void 0===this._dto.c||this._dto.c.length>0}get children(){return this._children}invoke(){}expand(e,t,o){let i=Promise.resolve();return this._haveLoaded||(this._haveLoaded=!0,i=e.getResult({task:"expand",id:this._dto.id,path:this.getIdPath()},o).then((i=>{o?.throwIfCancellationRequested();const l=i.map((e=>new a(this,e,this.depth+1,this._jmcEnabled)));return this.children(l),1===l.length?l[0].expand(e,t,o):Promise.resolve()}))),this._expanded(!this._expanded()),i}getIdPath(){if(!this._parent)return[this.id];const e=this._parent.getIdPath();return e.unshift(this.id),e}get isExpandableAllocationRow(){return this._dto.rt===l.RowType.Allocation&&this.expandable}}t.CallTreeRowViewModel=a}.apply(t,i),void 0===l||(e.exports=l)},118:(e,t,o)=>{var i,l;i=[o,t,o(3766)],l=function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocColumnSettingsProvider=void 0,t.DotNetObjectAllocColumnSettingsProvider=class{constructor(e){this._marshaler=new o.DotNetObjectAllocMarshaler,this._templateName=e}getColumnSettings(){return this._marshaler.getColumnSettings(this._templateName)}onColumnChanged(e){this._marshaler.onColumnChanged(this._templateName,e)}}}.apply(t,i),void 0===l||(e.exports=l)},952:(e,t,o)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InsightsViewId=t.ActiveCollectionViewId=t.FunctionListDetailsViewId=t.CallTreeDetailsViewId=t.DotNetAllocAnalyzerId=t.AllocationDetailsViewId=t.CollectionDetailsViewId=void 0,t.CollectionDetailsViewId=function(){return"2AB6F58C-F91F-4436-8D49-0C6E0F5E9657"},t.AllocationDetailsViewId=function(){return"A4C18565-9849-44E4-A6B0-9E9487D2024E"},t.DotNetAllocAnalyzerId=function(){return"DEF9F958-0E21-4364-8DD3-1CFB0C57FC7D"},t.CallTreeDetailsViewId=function(){return"A0A01775-6F3D-4B01-BFBE-FDD0F1F33EA4"},t.FunctionListDetailsViewId=function(){return"3ECF896D-96DC-4348-8A5C-6A853AA5C8CC"},t.ActiveCollectionViewId=function(){return"5979F2F4-B01D-4A63-AAE4-CE5C611EE4F8"},t.InsightsViewId=function(){return"5B496FFD-A4E8-48C1-BF62-F8435DFAD24C"}}.apply(t,[o,t]),void 0===i||(e.exports=i)},9371:(e,t,o)=>{var i,l;i=[o,t,o(8558)],l=function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.DotNetObjectAllocUI_OnAfterDomInsert=o.onAfterDomInsert}.apply(t,i),void 0===l||(e.exports=l)},7886:(e,t,o)=>{var i;i=function(e,t){"use strict";var o,i;Object.defineProperty(t,"__esModule",{value:!0}),t.HeapType=t.ToolView=void 0,(i=t.ToolView||(t.ToolView={}))[i.FunctionsListView=1]="FunctionsListView",i[i.CallTreeView=2]="CallTreeView",i[i.Allocations=3]="Allocations",(o=t.HeapType||(t.HeapType={}))[o.ALL=0]="ALL",o[o.SOH=1]="SOH",o[o.LOH=2]="LOH",o[o.POH=3]="POH"}.apply(t,[o,t]),void 0===i||(e.exports=i)},3766:(e,t,o)=>{var i,l;i=[o,t,o(5226),o(8117)],l=function(e,t,o,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocMarshaler=void 0;let l=null;t.DotNetObjectAllocMarshaler=class{constructor(){null===l&&(l=o.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationMarshaler",{},!0)),this._onGoToAllocation=new i.ObservableEvent(l,"onGoToAllocation"),this._onCrossReferenceEvent=new i.ObservableEvent(l,"onCrossReferenceEvent"),this._graphHighlightEvent=new i.ObservableEvent(l,"GraphHighlightChangedEvent"),this._updateNativeCodeEvent=new i.ObservableEvent(l,"updateNativeCodeEvent"),this._updateCollectionEvent=new i.ObservableEvent(l,"updateCollectionEvent")}get onGoToAllocation(){return this._onGoToAllocation}goToAllocation(e){return l._call("goToAllocation",e)}get onCrossReferenceEvent(){return this._onCrossReferenceEvent}crossReference(e){return l._call("crossReference",e)}updateGraphHighlight(e){return l._call("raiseGraphHighlightChangedEvent",e)}clearGraphHighlight(){return l._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}getDoubleClickTimeMs(){return l._call("getDoubleClickTimeMs")}isNativeCodeFoldingEnabled(){return l._call("isNativeCodeFoldingEnabled")}setNativeCodeFoldingEnabled(e){return l._call("setNativeCodeFolding",{isEnabled:e})}get onUpdateNativeCodeFolding(){return this._updateNativeCodeEvent}getColumnSettings(e){return l._call("getColumnSettings",e)}onColumnChanged(e,t){return l._call("onColumnChanged",e,t)}get onUpdateCollection(){return this._updateCollectionEvent}isCollectionEnabled(){return l._call("isCollectionEnabled")}isPauseResumeSupported(){return l._call("isPauseResumeSupported")}setCollectionEnabled(e){return l._call("setCollectionEnabled",e)}openLink(e){return l._call("openLink",e)}}}.apply(t,i),void 0===l||(e.exports=l)},5758:(e,t,o)=>{var i,l;i=[o,t,o(5226)],l=function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocTelemetryMarshaler=void 0;let i=null;t.DotNetObjectAllocTelemetryMarshaler=class{constructor(){null===i&&(i=o.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationTelemetryMarshaler",{},!0))}searchIsUsed(){i._post("searchIsUsed")}searchOptionsChanged(){i._post("searchOptionsChanged")}crossReferenceUsed(){i._post("crossReferenceUsed")}goToSourceUsed(){i._post("goToSourceUsed")}hotPathUsed(){i._post("hotPathUsed")}collectionToggled(e){i._post("collectionToggled",e)}topInsightLearnMore(e,t,o){i._post("topInsightsLearnMore",e,t,o)}goToAllocationView(e){i._post("goToAllocationView",e)}}}.apply(t,i),void 0===l||(e.exports=l)},8558:(e,t,o)=>{var i,l;i=[o,t,o(3028),o(2560)],l=function(e,t,o,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.areTimespansEqual=t.onAfterDomInsert=void 0,t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=o.utils.domData.get(e,"mediaQuery");if(t){const i=o.utils.domData.get(e,"mediaQueryListener");t.removeListener(i)}let l=45;const a=e.children;for(let e=0;e<a.length;e++)l+=a.item(e).offsetWidth;const s=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},r=window.matchMedia(i.Utilities.formatString("(max-width: {0}px)",l.toString()));s(r),r.addListener(s),o.utils.domData.set(e,"mediaQuery",r),o.utils.domData.set(e,"mediaQueryListener",s)},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)}}.apply(t,i),void 0===l||(e.exports=l)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=o},3028:e=>{"use strict";e.exports=i},5226:e=>{"use strict";e.exports=l}},s={},function e(t){var o=s[t];if(void 0!==o)return o.exports;var i=s[t]={exports:{}};return a[t].call(i.exports,i,i.exports,e),i.exports}(4423);var a,s}));
// SIG // Begin signature block
// SIG // MIIoJwYJKoZIhvcNAQcCoIIoGDCCKBQCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // 8x4c+gP6uwKngFEH62808pwtb7V3waq9gqOcFmwWv9mg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoJMIIaBQIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCBK0E6kFroD/kgA1oFiANEWVTWa1N5WlrH5
// SIG // dkzhWa5HnDBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAIwb+t8T
// SIG // epm638Fht+vSbDmiWIil+1LdvQivoNA+7T9lXXFX3odg
// SIG // DWpvYpVyubI1ZoKaa2XKHllnI8waiyj8x45AzIedJ9Cq
// SIG // o1wCRkoXJXjabCcPE4M5/OnCz6thp4O0w8voXg4MouIF
// SIG // McuP9kCbVt0Nk+2eIfMOyLJgwMlR46h+/gismG2xIb0J
// SIG // LpEnzhDyrFv6WMqh7lrRCyaO2Ybx3Q+r1FVz1d9rUt/i
// SIG // Az7MnWQaPUhU9TFegn6W0EKQPGoEMdbNKBem+v1ubu7V
// SIG // hC41qvUx3+X1qqN2TXV5rc5ahs+nh5eElUUtju6q7q2Y
// SIG // YLirIUdLSQ1KSqOHw1oF4wQhUgahgheTMIIXjwYKKwYB
// SIG // BAGCNwMDATGCF38wghd7BgkqhkiG9w0BBwKgghdsMIIX
// SIG // aAIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUQYLKoZIhvcN
// SIG // AQkQAQSgggFABIIBPDCCATgCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgSNWKKnlQLGjuGvG3vmNX
// SIG // Cxi4oDBMRHOJLWIAV5IgemsCBmhK3xuRkxgSMjAyNTA2
// SIG // MzAxNDQ2NDQuMzJaMASAAgH0oIHRpIHOMIHLMQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQg
// SIG // QW1lcmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hp
// SIG // ZWxkIFRTUyBFU046QTAwMC0wNUUwLUQ5NDcxJTAjBgNV
// SIG // BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wg
// SIG // ghHqMIIHIDCCBQigAwIBAgITMwAAAgh4nVhdksfZUgAB
// SIG // AAACCDANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDAeFw0yNTAxMzAxOTQyNTNaFw0y
// SIG // NjA0MjIxOTQyNTNaMIHLMQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVy
// SIG // YXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046
// SIG // QTAwMC0wNUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29m
// SIG // dCBUaW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3
// SIG // DQEBAQUAA4ICDwAwggIKAoICAQC1y3AI5lIz3Ip1nK5B
// SIG // MUUbGRsjSnCz/VGs33zvY0NeshsPgfld3/Z3/3dS8WKB
// SIG // LlDlosmXJOZlFSiNXUd6DTJxA9ik/ZbCdWJ78LKjbN3t
// SIG // FkX2c6RRpRMpA8sq/oBbRryP3c8Q/gxpJAKHHz8cuSn7
// SIG // ewfCLznNmxqliTk3Q5LHqz2PjeYKD/dbKMBT2TAAWAvu
// SIG // m4z/HXIJ6tFdGoNV4WURZswCSt6ROwaqQ1oAYGvEndH+
// SIG // DXZq1+bHsgvcPNCdTSIpWobQiJS/UKLiR02KNCqB4I9y
// SIG // ajFTSlnMIEMz/Ni538oGI64phcvNpUe2+qaKWHZ8d4T1
// SIG // KghvRmSSF4YF5DNEJbxaCUwsy7nULmsFnTaOjVOoTFWW
// SIG // fWXvBuOKkBcQKWGKvrki976j4x+5ezAP36fq3u6dHRJT
// SIG // LZAu4dEuOooU3+kMZr+RBYWjTHQCKV+yZ1ST0eGkbHXo
// SIG // A2lyyRDlNjBQcoeZIxWCZts/d3+nf1jiSLN6f6wdHaUz
// SIG // 0ADwOTQ/aEo1IC85eFePvyIKaxFJkGU2Mqa6Xzq3qCq5
// SIG // tokIHtjhogsrEgfDKTeFXTtdhl1IPtLcCfMcWOGGAXos
// SIG // VUU7G948F6W96424f2VHD8L3FoyAI9+r4zyIQUmqiESz
// SIG // uQWeWpTTjFYwCmgXaGOuSDV8cNOVQB6IPzPneZhVTjwx
// SIG // bAZlaQIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFKMx4vfO
// SIG // qcUTgYOVB9f18/mhegFNMB8GA1UdIwQYMBaAFJ+nFV0A
// SIG // XmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCG
// SIG // Tmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
// SIG // Y3JsL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0El
// SIG // MjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4wXAYI
// SIG // KwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwVGltZS1T
// SIG // dGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwGA1UdEwEB
// SIG // /wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYD
// SIG // VR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4ICAQBR
// SIG // szKJKwAfswqdaQPFiaYB/ZNAYWDa040XTcQsCaCua5ns
// SIG // G1IslYaSpH7miTLr6eQEqXczZoqeOa/xvDnMGifGNda0
// SIG // CHbQwtpnIhsutrKO2jhjEaGwlJgOMql21r7Ik6XnBza0
// SIG // e3hBOu4UBkMl/LEX+AURt7i7+RTNsGN0cXPwPSbTFE+9
// SIG // z7WagGbY9pwUo/NxkGJseqGCQ/9K2VMU74bw5e7+8IGU
// SIG // hM2xspJPqnSeHPhYmcB0WclOxcVIfj/ZuQvworPbTEEY
// SIG // DVCzSN37c0yChPMY7FJ+HGFBNJxwd5lKIr7GYfq8a0gO
// SIG // iC2ljGYlc4rt4cCed1XKg83f0l9aUVimWBYXtfNebhpf
// SIG // r6Lc3jD8NgsrDhzt0WgnIdnTZCi7jxjsIBilH99pY5/h
// SIG // 6bQcLKK/E6KCP9E1YN78fLaOXkXMyO6xLrvQZ+uCSi1h
// SIG // dTufFC7oSB/CU5RbfIVHXG0j1o2n1tne4eCbNfKqUPTE
// SIG // 31tNbWBR23Yiy0r3kQmHeYE1GLbL4pwknqaip1BRn6WI
// SIG // UMJtgncawEN33f8AYGZ4a3NnHopzGVV6neffGVag4Tdu
// SIG // y+oy1YF+shChoXdMqfhPWFpHe3uJGT4GJEiNs4+28a/w
// SIG // HUuF+aRaR0cN5P7XlOwU1360iUCJtQdvKQaNAwGI29KO
// SIG // wS3QGriR9F2jOGPUAlpeEzCCB3EwggVZoAMCAQICEzMA
// SIG // AAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQELBQAw
// SIG // gYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1p
// SIG // Y3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0
// SIG // eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4
// SIG // MzIyNVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
// SIG // c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
// SIG // BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UE
// SIG // AxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAw
// SIG // ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk
// SIG // 4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX
// SIG // 9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VG
// SIG // Iwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzB
// SIG // RMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2
// SIG // Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/PXfT+
// SIG // jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCOMcg1
// SIG // KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL
// SIG // 64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakX
// SIG // W2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX78
// SIG // 2Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOm
// SIG // TTd0lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07B
// SIG // MzlMjgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIz
// SIG // GHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ
// SIG // +QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AF
// SIG // emzFER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode
// SIG // 2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJ
// SIG // KwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQU
// SIG // KqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+n
// SIG // FV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYM
// SIG // KwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9S
// SIG // ZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcD
// SIG // CDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNV
// SIG // HQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSME
// SIG // GDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8E
// SIG // TzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5j
// SIG // b20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRf
// SIG // MjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoG
// SIG // CCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2
// SIG // LTIzLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt
// SIG // 4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U5
// SIG // 18JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN
// SIG // 3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu
// SIG // 2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2
// SIG // pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnD
// SIG // vBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3DYXMu
// SIG // LGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG
// SIG // +jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+Cljd
// SIG // QDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJ
// SIG // VGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRr
// SIG // akURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+
// SIG // CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8C
// SIG // wYKiexcdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVn
// SIG // K+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL
// SIG // 6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZq
// SIG // ELQdVTNYs6FwZvKhggNNMIICNQIBATCB+aGB0aSBzjCB
// SIG // yzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWlj
// SIG // cm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UE
// SIG // CxMeblNoaWVsZCBUU1MgRVNOOkEwMDAtMDVFMC1EOTQ3
// SIG // MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBT
// SIG // ZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQCNkvu0NKcSjdYK
// SIG // yrhJZcsyXOUTNKCBgzCBgKR+MHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7A0X
// SIG // CDAiGA8yMDI1MDYzMDE0MDA0MFoYDzIwMjUwNzAxMTQw
// SIG // MDQwWjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDsDRcI
// SIG // AgEAMAcCAQACAgQfMAcCAQACAhIXMAoCBQDsDmiIAgEA
// SIG // MDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKg
// SIG // CjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcN
// SIG // AQELBQADggEBAEzH/2rJMJ3Y0HYjavhwTmH4Vd5Ua4Zx
// SIG // YrChjcyr3EkWQqz/KcA2h5Z91mCHhA3TPjylKwjjYLjf
// SIG // oAIXxqZMv1hc1qjjGQYHpYSUXwji0Yqv/i86lY6XBIMt
// SIG // Ei7lCldbjn7gLkA9YnWeD0KylQ9+6vsOEQM/YKRmo16q
// SIG // hxFy4hL5HDdKuV5buCDuPXjrR2sFy5jAvb1reIK1JO8M
// SIG // mml7gxp/UdJr6pS6WoIrvcS7n2FLojVNmEnGPXtfvnGm
// SIG // 7eHin5NC4mcTLt8q+Xt5uTX6TWF7qlnmFmdstM0/eIoR
// SIG // Smkbq2S7DMKExJB6oXhan9Cl54ZBAD5zmmtcbdIUH1kg
// SIG // kwwxggQNMIIECQIBATCBkzB8MQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFt
// SIG // cCBQQ0EgMjAxMAITMwAAAgh4nVhdksfZUgABAAACCDAN
// SIG // BglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0G
// SIG // CyqGSIb3DQEJEAEEMC8GCSqGSIb3DQEJBDEiBCApiyAy
// SIG // q+buVgDy1/kns/QxwdyvuTnJzwT4jLl+2WZenzCB+gYL
// SIG // KoZIhvcNAQkQAi8xgeowgecwgeQwgb0EII//jm8JHa2W
// SIG // 1O9778t9+Ft2Z5NmKqttPk6Q+9RRpmepMIGYMIGApH4w
// SIG // fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAII
// SIG // eJ1YXZLH2VIAAQAAAggwIgQg0/laerKZ90VEljfKDf8B
// SIG // prontbclp+n0Gdtd5M58eRMwDQYJKoZIhvcNAQELBQAE
// SIG // ggIAkwSll9MeG/ZKyy3cHYb2v8359vIF1MArt616VXfs
// SIG // EHcA3yXJk9shVEnJWsOig2BVXh7JYSSYb76UKkOjYbnt
// SIG // 76W4Z6slgJdxDWBJrxGpzkVGnlCcs7w1c1hkwM0QzKpa
// SIG // tuNUBCl7jR4uH7AZxBBaVGkXxM3wLAFtp4awSo+tewA3
// SIG // 9QKNID2/Y66GsARkqhhGyvRe5DvHonvahKGRdUttEtT3
// SIG // h9ycBbEKNoHAAttSDALxgdGf3Fdejn9+mMwLTIWKgu94
// SIG // lhsXK7WEWwMqHSBig05n85NlTbiUtkIQdiwdyvCevQfq
// SIG // n3kNt1ASmrTcYUbwP9liCteNHIW32lNVaJmaX/lm8p7b
// SIG // RtO2xaPgA593dS+VuDZkq3wHpZFoL+r0cAn4ywXkhwyK
// SIG // 4+NCl2TubjymKUn92DWkcEbLwmmMIkQiwkmHnm+Mvwl0
// SIG // 6YQWRvNrbZ7eLC4H+6rnel8ZhLAfcZHlqBvSWMNmotY8
// SIG // GAV9BEOsnzrDMERg2Y/GD3ZW5oDNZ7S/G3ECUt265fuT
// SIG // 898WEC2pXQnpT67JBmtrM5RAp779BadEsehGJTDS1nkK
// SIG // xjdNsEJqiP27YQEkxkwxuv2K+wu4aBrBgiN4UOvVlkUA
// SIG // sWpseAqowSRlGVVZPEnYdNSpmKhhsfDNCCXCt/skVieC
// SIG // QryVigpBB1hj9ogvSvFCQukPwJc=
// SIG // End signature block
