define("insightsViewModel",["diagnosticsHub","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,i,o)=>{return a={6680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},4103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},952:(e,t,i)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InsightsViewId=t.ActiveCollectionViewId=t.FunctionListDetailsViewId=t.CallTreeDetailsViewId=t.DotNetAllocAnalyzerId=t.AllocationDetailsViewId=t.CollectionDetailsViewId=void 0,t.CollectionDetailsViewId=function(){return"2AB6F58C-F91F-4436-8D49-0C6E0F5E9657"},t.AllocationDetailsViewId=function(){return"A4C18565-9849-44E4-A6B0-9E9487D2024E"},t.DotNetAllocAnalyzerId=function(){return"DEF9F958-0E21-4364-8DD3-1CFB0C57FC7D"},t.CallTreeDetailsViewId=function(){return"A0A01775-6F3D-4B01-BFBE-FDD0F1F33EA4"},t.FunctionListDetailsViewId=function(){return"3ECF896D-96DC-4348-8A5C-6A853AA5C8CC"},t.ActiveCollectionViewId=function(){return"5979F2F4-B01D-4A63-AAE4-CE5C611EE4F8"},t.InsightsViewId=function(){return"5B496FFD-A4E8-48C1-BF62-F8435DFAD24C"}}.apply(t,[i,t]),void 0===o||(e.exports=o)},6815:(e,t,i)=>{var o,a;o=[i,t,i(3766),i(4881),i(4881),i(8117),i(8117),i(5758),i(952),i(3028),i(9387),i(7886),i(6680),i(4103)],a=function(e,t,i,o,a,n,l,s,r,c,d,h){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getInsightsViewModel=t.InsightsViewModel=void 0;class g{constructor(){let e;this._marshaler=new i.DotNetObjectAllocMarshaler,this._telemetry=new s.DotNetObjectAllocTelemetryMarshaler,this._viewEventManager=n.getViewEventManager(),this._currentOverlay=c.pureComputed((()=>this.computeOverlay())),l.loadDataWarehouse().then((t=>(e=t,t.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((t=>{this._insightsDAO=new d.InsightsDAO(e,t)})).then((()=>{c.applyBindings(this),this._viewEventManager.detailsViewReady.raiseEvent({Id:r.InsightsViewId()})}))}get topInsights(){return this._insightsDAO.topInsights}linkNavigate(e,t,i){return this._telemetry.topInsightLearnMore(e,t.ruleId,t.ruleType),this._marshaler.openLink(e),!1}investigate(e){if("e6d9c1db-4d2a-4fc3-8780-6404532270bf"!==e.ruleId&&"2ffbc4a2-549f-4f21-a52f-ef41dc4dd5da"!==e.ruleId||(this._telemetry.goToAllocationView(e.ruleId),this._viewEventManager.selectDetailsView(r.AllocationDetailsViewId())),e.typeId){const t=()=>{this._marshaler.crossReference({rowId:e.typeId,viewToShow:h.ToolView.Allocations})};this._viewEventManager.selectDetailsView(r.AllocationDetailsViewId()).then((()=>{t();const e=i=>{i.Id===r.AllocationDetailsViewId()&&(t(),this._viewEventManager.detailsViewReady.removeEventListener(e))};this._viewEventManager.detailsViewReady.addEventListener(e)}))}return!1}get dataLoadStatus(){return this._insightsDAO.dataLoadStatus}computeOverlay(){return this._insightsDAO.dataLoadStatus()===a.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:null}get currentOverlay(){return this._currentOverlay}}let u;t.InsightsViewModel=g,(new i.DotNetObjectAllocMarshaler).getDoubleClickTimeMs().then((e=>{o.Init(e),u=new g})),t.getInsightsViewModel=function(){return u}}.apply(t,o),void 0===a||(e.exports=a)},9387:(e,t,i)=>{var o,a;o=[i,t,i(3028),i(4881),i(952)],a=function(e,t,i,o,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.InsightsDAO=void 0,t.InsightsDAO=class{constructor(e,t){this._topInsights=i.observableArray([]),this._rootDataLoadStatus=i.observable(o.DataLoadEvent.DataLoadStart),this._dataWarehouse=e,this._timeFilter=i.observable(t);const n={timeDomain:this.timeFilter(),customDomain:{view:"Insights"}};this._rootDataLoadStatus(o.DataLoadEvent.DataLoadStart),this._dataWarehouse.getFilteredData(n,a.DotNetAllocAnalyzerId()).then((e=>e.getResult({type:"TopInsights"}))).then((e=>{this._topInsights(e.issues),this._rootDataLoadStatus(o.DataLoadEvent.DataLoadCompleted)}))}get topInsights(){return this._topInsights}get timeFilter(){return this._timeFilter}get dataLoadStatus(){return this._rootDataLoadStatus}}}.apply(t,o),void 0===a||(e.exports=a)},7886:(e,t,i)=>{var o;o=function(e,t){"use strict";var i,o;Object.defineProperty(t,"__esModule",{value:!0}),t.HeapType=t.ToolView=void 0,(o=t.ToolView||(t.ToolView={}))[o.FunctionsListView=1]="FunctionsListView",o[o.CallTreeView=2]="CallTreeView",o[o.Allocations=3]="Allocations",(i=t.HeapType||(t.HeapType={}))[i.ALL=0]="ALL",i[i.SOH=1]="SOH",i[i.LOH=2]="LOH",i[i.POH=3]="POH"}.apply(t,[i,t]),void 0===o||(e.exports=o)},3766:(e,t,i)=>{var o,a;o=[i,t,i(5226),i(8117)],a=function(e,t,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocMarshaler=void 0;let a=null;t.DotNetObjectAllocMarshaler=class{constructor(){null===a&&(a=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationMarshaler",{},!0)),this._onGoToAllocation=new o.ObservableEvent(a,"onGoToAllocation"),this._onCrossReferenceEvent=new o.ObservableEvent(a,"onCrossReferenceEvent"),this._graphHighlightEvent=new o.ObservableEvent(a,"GraphHighlightChangedEvent"),this._updateNativeCodeEvent=new o.ObservableEvent(a,"updateNativeCodeEvent"),this._updateCollectionEvent=new o.ObservableEvent(a,"updateCollectionEvent")}get onGoToAllocation(){return this._onGoToAllocation}goToAllocation(e){return a._call("goToAllocation",e)}get onCrossReferenceEvent(){return this._onCrossReferenceEvent}crossReference(e){return a._call("crossReference",e)}updateGraphHighlight(e){return a._call("raiseGraphHighlightChangedEvent",e)}clearGraphHighlight(){return a._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}getDoubleClickTimeMs(){return a._call("getDoubleClickTimeMs")}isNativeCodeFoldingEnabled(){return a._call("isNativeCodeFoldingEnabled")}setNativeCodeFoldingEnabled(e){return a._call("setNativeCodeFolding",{isEnabled:e})}get onUpdateNativeCodeFolding(){return this._updateNativeCodeEvent}getColumnSettings(e){return a._call("getColumnSettings",e)}onColumnChanged(e,t){return a._call("onColumnChanged",e,t)}get onUpdateCollection(){return this._updateCollectionEvent}isCollectionEnabled(){return a._call("isCollectionEnabled")}isPauseResumeSupported(){return a._call("isPauseResumeSupported")}setCollectionEnabled(e){return a._call("setCollectionEnabled",e)}openLink(e){return a._call("openLink",e)}}}.apply(t,o),void 0===a||(e.exports=a)},5758:(e,t,i)=>{var o,a;o=[i,t,i(5226)],a=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetObjectAllocTelemetryMarshaler=void 0;let o=null;t.DotNetObjectAllocTelemetryMarshaler=class{constructor(){null===o&&(o=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetObjectAllocation.DotNetObjectAllocationTelemetryMarshaler",{},!0))}searchIsUsed(){o._post("searchIsUsed")}searchOptionsChanged(){o._post("searchOptionsChanged")}crossReferenceUsed(){o._post("crossReferenceUsed")}goToSourceUsed(){o._post("goToSourceUsed")}hotPathUsed(){o._post("hotPathUsed")}collectionToggled(e){o._post("collectionToggled",e)}topInsightLearnMore(e,t,i){o._post("topInsightsLearnMore",e,t,i)}goToAllocationView(e){o._post("goToAllocationView",e)}}}.apply(t,o),void 0===a||(e.exports=a)},8117:t=>{"use strict";t.exports=e},4881:e=>{"use strict";e.exports=t},3028:e=>{"use strict";e.exports=i},5226:e=>{"use strict";e.exports=o}},n={},function e(t){var i=n[t];if(void 0!==i)return i.exports;var o=n[t]={exports:{}};return a[t](o,o.exports,e),o.exports}(6815);var a,n}));
// SIG // Begin signature block
// SIG // MIIoKAYJKoZIhvcNAQcCoIIoGTCCKBUCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // kliumBm0Kx4m1ZPN9iHj0e/KvS+VOBHc8xeCcFbjh0eg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoKMIIaBgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCDPOKQAwAo9Y4jqa1c5A3nJKlPM1JMbJ6cG
// SIG // UGOfAheCDzBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAECsCEV7
// SIG // SkYWRG2FNIr2/OXArYeuUHlRsFXbk0smYjD8kPX0MnG8
// SIG // UCuop9NTSqwkX7yTWk+hdSLFWhOZz5Z6URpjpCEz8zok
// SIG // l7w6n7Mf1lQBZX5yZLVL/y3c/qgfWvhSW1X8pIz4/RQb
// SIG // PLoog2Ort+DTXfHd553OB6Z9HOGDJy7uBwjB9mYr1LBG
// SIG // kI8tpf1QCRHh/HA3umyjDNI5VfCSTfRQmx74DBmiTZ3R
// SIG // hLB3FCRPsKa58ZqJWGGmzrnCTaMeed9c4tUUurcC6ggc
// SIG // JRCVuzi7LWO2Aw/QE+jEb+6ed4xaZVzvcuAvuqiQLRRF
// SIG // YA8XTzd+RmEp12ILl0MnMFqS8zmhgheUMIIXkAYKKwYB
// SIG // BAGCNwMDATGCF4Awghd8BgkqhkiG9w0BBwKgghdtMIIX
// SIG // aQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgAF8+dLvIxnF6BJvKNgye
// SIG // mU2HXc+x3SdqHJv8aSsh46ICBmhK1JmcDhgTMjAyNTA2
// SIG // MzAxNDQ1MjYuOTA0WjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOjkyMDAtMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR6jCCByAwggUIoAMCAQICEzMAAAIJCAfg+VyM5lUA
// SIG // AQAAAgkwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjUwMTMwMTk0MjU1WhcN
// SIG // MjYwNDIyMTk0MjU1WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OjkyMDAtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEAwpRKMPcuDN39Uvc9
// SIG // cbTRBE8Fi9bxIosNKA+0lxHb+LHT9MbFconb+iNq5hJf
// SIG // D2LPS3GY87FjhyO3UJES9vBj9wl3L2NGaup1rB2NkGpg
// SIG // mRSxdiJUR+gR8dkZDe2UQyprOwTqOCBgUZQjJFL/Tff7
// SIG // cDswJKVjbDN2/wUMXMIVYLEKrUPDRD1Lokfhlea3UB1E
// SIG // +KY4oWU5CcK2pYs9GW2KVEx+TpIt3dwacfaoj64geoYT
// SIG // Xxj45dDyKdtw+e/a6VumZj6j0/I9dil+8kmcDbsbNz2L
// SIG // xf8NdxrEV5MyGyMiyhD84/Zc5pqxdsI771K8fQGcOxi0
// SIG // l5NvA59V0n+toW5BblBsDxS6dxG0aiFZgWeNsHM+ZkiC
// SIG // Ast0LP4cIRGIVJ3ZwAYDaQ+WrwCzle7FHyaxw2V1+n/Y
// SIG // IG4yAOo9p4UgEiKpfBeS7CgcNET7Q7st49gj8bU5maM2
// SIG // yyvEzLcQ4jAoMU6X4OYmFL8oVeGqmgy8EQbKAUYTv/oc
// SIG // Mmyp2MF8Snnjq7DsEC52jhOQZhSWFgThc93fPCwSvUEQ
// SIG // YHRB+Qi1Ye8JIDCHofenB+fh9MRL5oOre7s7ZV19kle8
// SIG // XVGD8QN7441dxJFe2m0hw+Rx0GU63dxarA/1TmAAlFQT
// SIG // 68RfpFK2Rl8WCJ2U6a2DGBKulCBtQ0+KQlT/Q3GgixiD
// SIG // mBCdYNMCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBRJi+jR
// SIG // xF045b3wL0DNtXczFpPK0jAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // XF58bzg8JOIf421AbJxZRba0rgQWW+8EmX2uZSkTEzXz
// SIG // ZZmgAuG3e1qNCOYTMbBCVMrqR8IeJA+apEWXMyHNIyAA
// SIG // UENcQ1AWvlk8a6f1AKgte4oxQnj2SmFYzax3/wZo8+xW
// SIG // jiONZMbnkYcCzSHENoJgag0eVuE0tobUSWMmQLO43yZm
// SIG // w7U3FDjIRJdTlpcfxZ73EG6LeVT82lMIk+jYnvJej2Y6
// SIG // ELLsYmrLkgJsSiEHbB5yeUKJKsHcql4tRWQ7RE1b213w
// SIG // 7KH807WuHp9qn+PIcxGcFL25M+bJrfPdJ1QCu5M9nK68
// SIG // zd4aZ3xbn7af61y1k78T0HH1l4hLiFHdhoO3kfELcirS
// SIG // Q1PPjw8BApM6GiY2xgiqsfREoBSc861zcIYV+kXPINhF
// SIG // P/ut5pqlnghf5CThYNnicO2rv2mxEoKtxGs8g9VZS/h2
// SIG // l/jARxs0Jh7bzpt0JeMFUzd1qvF/GwkevKoheaxWrJuE
// SIG // cRes2o2Xkhwv6kud9+v+GjA6rFejvOkZTzwmBiTj7X9j
// SIG // Gyju1ySXi/1EDdHN7oseUTE6OunWwE8T1BRBuT4eDx8x
// SIG // o1GxDuw9+S7hAYohvGK5TETpBpd3wUJfW1m4MPQiFEG8
// SIG // KuXE2hMZXxKTHUqMnSaJVE0A+RCyhs9UyWoU4nXdtMJc
// SIG // IuQZN+lyJs7B+GLNeYl0XwIwggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDTTCCAjUCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjo5MjAwLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUAfO+tqz00HeyJ
// SIG // wwkHW9ZIBSkJAkSggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOwN
// SIG // DIYwIhgPMjAyNTA2MzAxMzE1NTBaGA8yMDI1MDcwMTEz
// SIG // MTU1MFowdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA7A0M
// SIG // hgIBADAHAgEAAgIGUjAHAgEAAgISfzAKAgUA7A5eBgIB
// SIG // ADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMC
// SIG // oAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3
// SIG // DQEBCwUAA4IBAQBs/iJuA/ovEN/YkvkNRLce/BqBe8la
// SIG // k0qHZ+gX1iuOSVn7MC3jgJ/leGz3wViLD94yYr6ZSi6Z
// SIG // n2YA6aZCdutYidBCsQW+nViVpMnpMDiuO2+y2atOsP26
// SIG // /fTKgwUChQfhQpZNUgo82CgLahnRMNYX5DwNmlMLEqfZ
// SIG // Ui+IPhMX9xZoKer92rRwkOkKB3tF22XUGkUTuJ+eLZAF
// SIG // thOza3XAxuw7AhEifo2m3cOuKLl08r25slx6NUdgOYEp
// SIG // ejBWNYUxaIkZjzRB6aVbtVdp38S7jU9NyJWMpnXL35J8
// SIG // eo7UPXee2xoUA99n6XpDYYwVAehHId6wllRlfAKIz9/D
// SIG // Cc2pMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
// SIG // bXAgUENBIDIwMTACEzMAAAIJCAfg+VyM5lUAAQAAAgkw
// SIG // DQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzEN
// SIG // BgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgoWGs
// SIG // sIVoSDJzbhixoaYMzRnWD91uO5xHgCh15dMBRYAwgfoG
// SIG // CyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCBoGyweyL30
// SIG // Ai5lDlGYY3VKivG4pHwemVVXaE4zcIUTPjCBmDCBgKR+
// SIG // MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
// SIG // Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAC
// SIG // CQgH4PlcjOZVAAEAAAIJMCIEIFoJJYPIIv8TolmZVP8C
// SIG // lACrvfr1aPRonRIaAi/23ZFhMA0GCSqGSIb3DQEBCwUA
// SIG // BIICAF3MwCWCpKck79Ab4LNJxiejxdWptr7WZK/52M44
// SIG // UyiSUkboHGjFD72Tpe7akpJ7Vz6Hxj8F454MhwZo85DI
// SIG // /64yMKxDFL0iI/VO6hW0QqO3iy16yqPavzj1pIZKYsol
// SIG // 07byOh+/wkIWfXyKdY07pFlefQQ0qwplghQ+RO7f6V8s
// SIG // G49sR0v33JbsrvmEiXJuz/JztV+0vr9wjcckfhxvzeYf
// SIG // myK0msjo9zbS5ZHRjltzgeP3x1HsdkVxn4eoQCYoRUsj
// SIG // RXPlVbhlspk97QgWxMEwj1uzHRwpBF0tzj2iTNIsNMU7
// SIG // 29CEslLI4zPP6NW793YcZtwK0RBnWv2Ube1VBNGLZtKe
// SIG // T2Sm0nn29XM/ZlLTpmwoy1sBz8ofLDACBkC0y/voY/Wf
// SIG // p+TJem0LyKrweCe3ilY/OiZgC1BtS1mxIZ2n09peVNxk
// SIG // KKKDP8BORc0W8ZmaIdlMQEZPbtoFGy8zzsEtg9NyeBOm
// SIG // zTWoqeKf3QvzCmLWLMMVzySflmfP1L5yRlCIYe+gDAS3
// SIG // dbXS09w3cidtiHS7hHewx/a3yjxHnszwrzUH/t1RLG1H
// SIG // 08M388cSczNwUouIjqDtV7qBcw0BJApjwp0c4TW5yAL5
// SIG // HDo7kh5Tj3fnI717/BVmJairau6EuXNadIbJ1PazdCie
// SIG // E0qU5ZRV9U7WCu+OF2hAXl8KS9rx
// SIG // End signature block
