define("blockedTimeDetailsViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,a,o,r)=>{return n={2608:e=>{const t=document.createElement("script");t.id="BlockedEventRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyBibG9ja2VkRXZlbnRSb3ciIHRhYmluZGV4PSItMSIgcm9sZT0icm93IiBkYXRhLWJpbmQ9InRyZWVHcmlkUm93Rm9jdXM6ICRwYXJlbnQuZm9jdXNlZFJvdygpID09PSAkZGF0YSwgY3NzOiB7IHNlbGVjdGVkOiBzZWxlY3RlZCgpIH0iPg0KICAgIDx0ZCBjbGFzcz0ibmFtZSIgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBjbGFzcz0iaW5kZW50Ij4mbmJzcDs8L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgY2xhc3M9ImR1cmF0aW9uIiByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBkdXJhdGlvbkluTXMiIGRhdGEtY29sdW1uaWQ9ImR1cmF0aW9uIj48L3RkPg0KICAgIDx0ZCBjbGFzcz0ibWF4IiByb2xlPSJncmlkY2VsbCIgZGF0YS1jb2x1bW5pZD0ibWF4Ij48L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},7348:e=>{const t=document.createElement("script");t.id="BlockedThreadRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgdGFiaW5kZXg9Ii0xIiByb2xlPSJyb3ciIGRhdGEtYmluZD0idHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLCBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSI+DQogICAgPHRkIGNsYXNzPSJuYW1lIGNvbnRhaW5lciIgcm9sZT0iZ3JpZGNlbGwiIGRhdGEtYmluZD0iY3NzOiB7IHNob3dUcmFja0FkZDogIXRyYWNrQWRkZWQoKSB9IiBkYXRhLWNvbHVtbmlkPSJuYW1lIj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBoYXNFdmVudHMgPyAndmlzaWJsZScgOiAnaGlkZGVuJyB9Ij48L2Rpdj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBuYW1lIj48L3NwYW4+DQogICAgICAgIDxkaXYgY2xhc3M9ImJsb2NrZWRUaHJlYWQtYWRkVHJhY2siIGRhdGEtYmluZD0iY2xpY2s6IGFkZFRyYWNrLCB2aXNpYmxlOiAhdHJhY2tBZGRlZCgpIj48L2Rpdj4NCiAgICA8L3RkPg0KICAgIDx0ZCBjbGFzcz0iZHVyYXRpb24iIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IGR1cmF0aW9uSW5NcyIgZGF0YS1jb2x1bW5pZD0iZHVyYXRpb24iPjwvdGQ+DQogICAgPHRkIGNsYXNzPSJtYXgiIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IG1heEluTXMiIGRhdGEtY29sdW1uaWQ9Im1heCI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},4816:function(e,t,a){var o,r,n=this&&this.__createBinding||(Object.create?function(e,t,a,o){void 0===o&&(o=a),Object.defineProperty(e,o,{enumerable:!0,get:function(){return t[a]}})}:function(e,t,a,o){void 0===o&&(o=a),e[o]=t[a]}),i=this&&this.__exportStar||function(e,t){for(var a in e)"default"===a||Object.prototype.hasOwnProperty.call(t,a)||n(t,e,a)};o=[a,t,a(3028),a(5639),a(4828),a(952),a(8117),a(8117)],r=function(e,t,a,o,r,n,d,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getBlockedTimeDetailsViewModel=t.BlockedTimeDetailsViewModel=void 0,i(o,t);class l{constructor(){d.loadDataWarehouse().then((e=>{this._blockedTimeViewModel=new r.BlockedTimeViewModel(e),s.getViewEventManager().detailsViewReady.raiseEvent({Id:n.blockedTimeDetailsViewId()}),a.applyBindings(this)}))}get mainViewModel(){return this._blockedTimeViewModel}}let c;t.BlockedTimeDetailsViewModel=l,t.getBlockedTimeDetailsViewModel=function(){return c||(c=new l),c}}.apply(t,o),void 0===r||(e.exports=r)},4037:(e,t,a)=>{var o,r;o=[a,t,a(3028),a(8117),a(8117),a(2608)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedEventRowViewModel=void 0,t.BlockedEventRowViewModel=class{constructor(e,t){this._selected=a.observable(!1),this._expanded=a.observable(!1),this._dto=e,this._children=a.observableArray([]),this._parent=t}get parent(){return this._parent}get templateName(){return"BlockedEventRowView"}get id(){return this._dto.id}get depth(){return 1}get durationInMs(){return this._dto.durationInMs}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){r.getViewEventManager().selectionChanged.raiseEvent({position:new o.JsonTimespan(new o.BigNumber(this._dto.start.h,this._dto.start.l),new o.BigNumber(this._dto.end.h,this._dto.end.l)),isIntermittent:!1})}}}.apply(t,o),void 0===r||(e.exports=r)},7490:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(3467),a(4881)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedStackFrame=void 0,t.BlockedStackFrame=class{constructor(e){this._dto=e}get name(){return this._dto.name}get label(){if(void 0===this._dto.jmcState)return"";switch(this._dto.jmcState){case r.JmcState.SystemCode:return a.Resources.getString("SystemCallLabel");case r.JmcState.LibraryCode:return a.Resources.getString("ExternalCallLabel");case r.JmcState.UserCode:default:return""}}get canGoToSource(){return this._dto.fileName&&"number"==typeof this._dto.lineNumber}goToSource(){return this.canGoToSource?(new o.BlockedTimeMarshaler).goToSource(this._dto.fileName,this._dto.lineNumber):Promise.resolve(!1)}}}.apply(t,o),void 0===r||(e.exports=r)},1336:(e,t,a)=>{var o,r;o=[a,t,a(3028),a(3467),a(4037),a(7348)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedThreadRowViewModel=void 0,t.BlockedThreadRowViewModel=class{constructor(e){this._selected=a.observable(!1),this._expanded=a.observable(!1),this._trackAdded=a.observable(!1),this._children=a.observableArray([]),this._haveLoaded=!1,this._marshaler=new o.BlockedTimeMarshaler,this._dto=e,this._marshaler.onTracksAdded.addEventListener((e=>{-1!==e.threadIds.indexOf(this._dto.threadId)&&this._trackAdded(!0)})),this._marshaler.onTracksRemoved.addEventListener((e=>{-1!==e.threadIds.indexOf(this._dto.threadId)&&this._trackAdded(!1)}))}get templateName(){return"BlockedThreadRowView"}get id(){return this._dto.threadId}get depth(){return 0}get name(){return this._dto.threadId.toString()}get durationInMs(){return this._dto.durationInMs}get maxInMs(){return this._dto.maxInMs}get trackAdded(){return this._trackAdded}get hasEvents(){return 0!==this._dto.durationInMs}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){}expand(e,t,a){let o=Promise.resolve();return this._haveLoaded||(this._haveLoaded=!0,o=e.getResult({op:"threadDetails",threadId:this._dto.threadId},a).then((e=>{const t=e.map((e=>new r.BlockedEventRowViewModel(e,this)));this._children(t)}))),this._expanded(!this._expanded()),o}addTrack(e,t){return this.trackAdded()||this._marshaler.addTrack(this._dto.threadId),!1}}}.apply(t,o),void 0===r||(e.exports=r)},5732:(e,t,a)=>{var o,r;o=[a,t,a(7490),a(952),a(1336)],r=function(e,t,a,o,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeDAO=void 0,t.BlockedTimeDAO=class{constructor(e){this._dataWarehouse=e}getRoots(e,t,a){return this._dataWarehouse.getFilteredData({customDomain:{Task:"Summary"}},o.blockedTimeAnalyzer(),a).then((e=>(a?.throwIfCancellationRequested(),this._currentResult=e,this._currentResult.getResult({op:"threadSummary"},a)))).then((e=>e.map((e=>new r.BlockedThreadRowViewModel(e)))))}sort(e,t,a){return Promise.resolve(e)}search(e,t,a,o,r,n,i){return Promise.resolve(null)}expand(e,t,a){return e.expand(this._currentResult,t,a)}queryStacks(e,t){return this._currentResult.getResult({op:"queryStacks",threadId:e.parent.id,eventId:e.id},t).then((e=>({blockedStack:e.blockedStack.map((e=>new a.BlockedStackFrame(e))),readyStack:e.readyStack.map((e=>new a.BlockedStackFrame(e)))})))}}}.apply(t,o),void 0===r||(e.exports=r)},3467:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(8117)],r=function(e,t,a,o){"use strict";let r;Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeMarshaler=void 0,t.BlockedTimeMarshaler=class{constructor(){null===r&&(r=a.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.CpuSampling.BlockedTime.BlockedTimeMarshaler",{},!0)),this._onTracksAdded=new o.ObservableEvent(r,"onTracksAdded"),this._onTracksRemoved=new o.ObservableEvent(r,"onTracksRemoved")}get onTracksAdded(){return this._onTracksAdded}get onTracksRemoved(){return this._onTracksRemoved}addTrack(e){r._post("addTrack",e)}removeTrack(e){return r._call("removeTrack",e)}goToSource(e,t){return r._call("goToSource",e,t)}}}.apply(t,o),void 0===r||(e.exports=r)},7014:(e,t,a)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeSummaryColumnSettingsProvider=void 0,t.BlockedTimeSummaryColumnSettingsProvider=class{getColumnSettings(){return Promise.resolve([{columnId:"0",isHidden:!1,width:75},{columnId:"1",isHidden:!1,width:200},{columnId:"2",isHidden:!1,width:200}])}onColumnChanged(e){}}}.apply(t,[a,t]),void 0===o||(e.exports=o)},4828:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(3028),a(4881),a(4881),a(4881),a(5732),a(7014),a(8117),a(952),a(8117)],r=function(e,t,a,o,r,n,i,d,s,l,c,u){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BlockedTimeViewModel=void 0,t.BlockedTimeViewModel=class{constructor(e){this._blockedStack=o.observableArray([]),this._readyStack=o.observableArray([]),this._dataLoadStatus=o.observable(r.DataLoadEvent.DataLoadCompleted),this._dataLoadPromise=null,this._dao=new d.BlockedTimeDAO(e);const t=new i.TreeGridHeaderViewModel([{id:"name",text:a.Resources.getString("BlockedTimeSummary_NameHeader"),hideable:!1},{id:"duration",text:a.Resources.getString("BlockedTimeSummary_DurationHeader"),hideable:!1},{id:"max",text:a.Resources.getString("BlockedTimeSummary_MaxHeader"),hideable:!1}],new s.BlockedTimeSummaryColumnSettingsProvider,"name");this._summaryViewModel=new n.TreeGridViewModel(this._dao,t,"BlockedTimeSummary_AriaLabel"),this._summaryViewModel.focusedRow.subscribe(this.onSelectionChanged.bind(this)),l.getViewEventManager().jmcEnabledStateChanged.addEventListener((()=>{this._summaryViewModel.onResultChanged(0)})),this._summaryViewModel.onResultChanged(0)}get summaryViewModel(){return this._summaryViewModel}get dataLoadStatus(){return this._dataLoadStatus}get blockedStack(){return this._blockedStack}get readyStack(){return this._readyStack}onSelectionChanged(e){if(null===e||!e.parent)return this._blockedStack([]),void this._readyStack([]);this._dataLoadCancellationTokenSource&&this._dataLoadCancellationTokenSource.cancel(),this._dataLoadCancellationTokenSource=new u.CancellationTokenSource,this._dataLoadCancellationTokenSource.token.onCancellationRequested.addEventListener((()=>{this._dataLoadStatus(r.DataLoadEvent.DataLoadCanceled)}),{once:!0});const t=e;this._dataLoadStatus(r.DataLoadEvent.DataLoadStart),this._dataLoadPromise=this._dao.queryStacks(t,this._dataLoadCancellationTokenSource.token).then((e=>{this._blockedStack(e.blockedStack),this._readyStack(e.readyStack)})).then((()=>{this._dataLoadPromise=null,this._dataLoadStatus(r.DataLoadEvent.DataLoadCompleted)}),(e=>{e.name!==c.errorNameCanceled()&&this._dataLoadStatus(r.DataLoadEvent.DataLoadFailed)}))}}}.apply(t,o),void 0===r||(e.exports=r)},952:(e,t,a)=>{var o;o=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.flameGraphViewModelMappingKey=t.flatFunctionsViewModelMappingKey=t.modulesViewModelMappingKey=t.callTreeViewModelMappingKey=t.callerCalleeViewModelMappingKey=t.functionLimit=t.defaultSampleRate=t.errorNameCanceled=t.blockedTimeDetailsViewId=t.performanceDebuggerDetailsViewId=t.collectionDetailsViewId=t.analysisDetailsViewId=t.blockedTimeAnalyzer=t.cpuSamplingAnalyzer=void 0,t.cpuSamplingAnalyzer=function(){return"DCA8B3EF-28C5-4B08-BAFC-B072F8AA9277"},t.blockedTimeAnalyzer=function(){return"3BA86369-05EE-409B-B598-BCCDFA4EFE2F"},t.analysisDetailsViewId=function(){return"7D95F423-6D5E-488C-B3A9-169D6D297D5C"},t.collectionDetailsViewId=function(){return"DDEDFB2B-8979-4CA9-BED3-7A3E4C495F1C"},t.performanceDebuggerDetailsViewId=function(){return"47660699-1BCE-4442-AEA7-A520683BDA66"},t.blockedTimeDetailsViewId=function(){return"CA734335-A674-41E2-BC61-98564E300942"},t.errorNameCanceled=function(){return"Canceled"},t.defaultSampleRate=function(){return 1e3},t.functionLimit=function(){return 5},t.callerCalleeViewModelMappingKey=function(){return"CallerCalleeView"},t.callTreeViewModelMappingKey=function(){return"CallTreeView"},t.modulesViewModelMappingKey=function(){return"ModulesView"},t.flatFunctionsViewModelMappingKey=function(){return"FlatFunctionsView"},t.flameGraphViewModelMappingKey=function(){return"FlameGraphView"}}.apply(t,[a,t]),void 0===o||(e.exports=o)},5639:(e,t,a)=>{var o,r;o=[a,t,a(8558)],r=function(e,t,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),window.CpuSamplingUI_onAfterDomInsert=a.onAfterDomInsert}.apply(t,o),void 0===r||(e.exports=r)},7886:(e,t,a)=>{var o;o=function(e,t){"use strict";var a,o,r,n,i,d,s,l;Object.defineProperty(t,"__esModule",{value:!0}),t.PerformanceSessionEntryPoint=t.SortColumn=t.CpuToolView=t.ResultStage=t.ResultNotStartedReason=t.ResultPreparationStatus=t.ActivityType=t.ResultTaskType=void 0,(l=t.ResultTaskType||(t.ResultTaskType={}))[l.Expand=1]="Expand",l[l.Search=2]="Search",l[l.GetData=3]="GetData",l[l.Sort=4]="Sort",l[l.ExpandHotPath=5]="ExpandHotPath",l[l.TopFunctions=6]="TopFunctions",l[l.GetNodePath=7]="GetNodePath",l[l.TopInsights=8]="TopInsights",l[l.Autocomplete=9]="Autocomplete",l[l.UpdateRoot=10]="UpdateRoot",l[l.InsightHelp=11]="InsightHelp",l[l.RequestHelp=12]="RequestHelp",l[l.AddSourceThenRequestHelp=13]="AddSourceThenRequestHelp",l[l.GetInsightFunc=14]="GetInsightFunc",l[l.InvokeGetSourceCode=15]="InvokeGetSourceCode",(s=t.ActivityType||(t.ActivityType={}))[s.Unknown=0]="Unknown",s[s.ThreadRun=1]="ThreadRun",s[s.AsyncTask=2]="AsyncTask",(d=t.ResultPreparationStatus||(t.ResultPreparationStatus={}))[d.NotStarted=0]="NotStarted",d[d.InProgress=1]="InProgress",d[d.Completed=2]="Completed",d[d.Canceled=3]="Canceled",d[d.Failed=4]="Failed",(i=t.ResultNotStartedReason||(t.ResultNotStartedReason={}))[i.Unknown=0]="Unknown",i[i.NoValidTimeSelection=1]="NoValidTimeSelection",i[i.NoValidThreadSelection=2]="NoValidThreadSelection",i[i.ToolIsDisabled=3]="ToolIsDisabled",i[i.TargetRunningUnderDebugger=4]="TargetRunningUnderDebugger",(n=t.ResultStage||(t.ResultStage={}))[n.Unknown=0]="Unknown",n[n.Threads=1]="Threads",n[n.Sampling=2]="Sampling",(r=t.CpuToolView||(t.CpuToolView={}))[r.FlatFunctionsView=1]="FlatFunctionsView",r[r.CallerCalleeView=2]="CallerCalleeView",r[r.CallTreeView=3]="CallTreeView",r[r.ModulesView=4]="ModulesView",r[r.FlameGraphView=5]="FlameGraphView",(o=t.SortColumn||(t.SortColumn={}))[o.Id=1]="Id",o[o.FunctionName=2]="FunctionName",o[o.TotalSamples=3]="TotalSamples",o[o.SelfSamples=4]="SelfSamples",o[o.ModuleName=5]="ModuleName",o[o.CategoryName=6]="CategoryName",o[o.CallCount=7]="CallCount",(a=t.PerformanceSessionEntryPoint||(t.PerformanceSessionEntryPoint={}))[a.Profiling=0]="Profiling",a[a.PerformanceDebugger=1]="PerformanceDebugger"}.apply(t,[a,t]),void 0===o||(e.exports=o)},8558:(e,t,a)=>{var o,r;o=[a,t,a(5226),a(3028),a(7886),a(4881),a(8117),a(2560)],r=function(e,t,a,o,r,n,i,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.onAfterDomInsert=t.localizeNumber=t.areToolContextsEqual=t.areTimespansEqual=t.areBigNumbersEqual=t.numberComparator=t.getSortFunction=void 0;let s={};a.Culture.addEventListener("culturechanged",(()=>{s={}})),t.getSortFunction=function(e,t){switch(e){case r.SortColumn.Id:return n.SortFunctions.numericSort("id",t);case r.SortColumn.FunctionName:return n.SortFunctions.stringSort("name",t);case r.SortColumn.SelfSamples:return n.SortFunctions.numericSort("selfSamples",t);case r.SortColumn.TotalSamples:return n.SortFunctions.numericSort("totalSamples",t);case r.SortColumn.ModuleName:return n.SortFunctions.stringSort("moduleName",t);case r.SortColumn.CategoryName:return n.SortFunctions.stringSort("categoryName",t);case r.SortColumn.CallCount:return n.SortFunctions.numericSort("callCount",t);default:throw i.Assert.fail(`Unknown sort column: ${r.SortColumn[e]}`),new Error(`Unknown sort column: ${r.SortColumn[e]}`)}},t.numberComparator=function(e,t){return e-t},t.areBigNumbersEqual=function(e,t){return!e&&!t||e&&t&&e.h===t.h&&e.l===t.l},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)},t.areToolContextsEqual=function(e,t){return!e&&!t||e&&t&&e.rowId===t.rowId&&e.rowType===t.rowType},t.localizeNumber=function(e,t){const o=JSON.stringify(t||{});let r=s[o];if(!r){const e=new Intl.NumberFormat(a.Culture.formatRegion,t);r=t=>e.format(t),s[o]=r}return r(e)},t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=o.utils.domData.get(e,"mediaQuery");if(t){const a=o.utils.domData.get(e,"mediaQueryListener");t.removeListener(a)}let a=45;const r=e.children;for(let e=0;e<r.length;e++)a+=r.item(e).offsetWidth;const n=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},i=window.matchMedia(d.Utilities.formatString("(max-width: {0}px)",a.toString()));n(i),i.addListener(n),o.utils.domData.set(e,"mediaQuery",i),o.utils.domData.set(e,"mediaQueryListener",n)}}.apply(t,o),void 0===r||(e.exports=r)},8117:t=>{"use strict";t.exports=e},2560:e=>{"use strict";e.exports=t},4881:e=>{"use strict";e.exports=a},3028:e=>{"use strict";e.exports=o},5226:e=>{"use strict";e.exports=r}},i={},function e(t){var a=i[t];if(void 0!==a)return a.exports;var o=i[t]={exports:{}};return n[t].call(o.exports,o,o.exports,e),o.exports}(4816);var n,i}));
// SIG // Begin signature block
// SIG // MIIoKAYJKoZIhvcNAQcCoIIoGTCCKBUCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // pZmnrPn9G9Tp1iCKM+LEKCRcuB9bDHyn+WEllNyckG+g
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoKMIIaBgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCAg8mXI9TW5423P+kUdRNs1x3KN80Co8e/k
// SIG // L7kRzX56hjBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBADwQF4ov
// SIG // zy1O7tVUNWUJHqW9xshb5LPXM+UK91XYk/3xWPNFs/DC
// SIG // OKeNJOCds9ueeWRujXSq4kO4WN5xb/6QWh8EnsSlGV/p
// SIG // ii6RM5uL9ufX5vNND2QHuLwZyugrGJJbo/CyjPM4Y1N5
// SIG // fLkEyhFa0o16Uik5gx2Hg6nZxAQtyg/s8mVZslLDO36f
// SIG // vvjymFpm3ggTsbm9+RDmGHOwWBZo6p1xssbi9HGx9Pdz
// SIG // nTPNvZ9UM3IGgK1ouQjA+iebKLqrkM6mY4jhrBRDoBa9
// SIG // Y0DfsxEf7RVcYPTMKOBVpDuOALvNyhZAPDwQDwbEBdnB
// SIG // uabNWM095i0QVp6iRESlmblJRlehgheUMIIXkAYKKwYB
// SIG // BAGCNwMDATGCF4Awghd8BgkqhkiG9w0BBwKgghdtMIIX
// SIG // aQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgkJm3gozAa4dhqkb53eOq
// SIG // 1N90d8ioKyJpGBPkNRIAIyMCBmhK1JmskBgTMjAyNTA2
// SIG // MzAxNDUwNDYuMjA3WjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOjkyMDAtMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR6jCCByAwggUIoAMCAQICEzMAAAIJCAfg+VyM5lUA
// SIG // AQAAAgkwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjUwMTMwMTk0MjU1WhcN
// SIG // MjYwNDIyMTk0MjU1WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OjkyMDAtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEAwpRKMPcuDN39Uvc9
// SIG // cbTRBE8Fi9bxIosNKA+0lxHb+LHT9MbFconb+iNq5hJf
// SIG // D2LPS3GY87FjhyO3UJES9vBj9wl3L2NGaup1rB2NkGpg
// SIG // mRSxdiJUR+gR8dkZDe2UQyprOwTqOCBgUZQjJFL/Tff7
// SIG // cDswJKVjbDN2/wUMXMIVYLEKrUPDRD1Lokfhlea3UB1E
// SIG // +KY4oWU5CcK2pYs9GW2KVEx+TpIt3dwacfaoj64geoYT
// SIG // Xxj45dDyKdtw+e/a6VumZj6j0/I9dil+8kmcDbsbNz2L
// SIG // xf8NdxrEV5MyGyMiyhD84/Zc5pqxdsI771K8fQGcOxi0
// SIG // l5NvA59V0n+toW5BblBsDxS6dxG0aiFZgWeNsHM+ZkiC
// SIG // Ast0LP4cIRGIVJ3ZwAYDaQ+WrwCzle7FHyaxw2V1+n/Y
// SIG // IG4yAOo9p4UgEiKpfBeS7CgcNET7Q7st49gj8bU5maM2
// SIG // yyvEzLcQ4jAoMU6X4OYmFL8oVeGqmgy8EQbKAUYTv/oc
// SIG // Mmyp2MF8Snnjq7DsEC52jhOQZhSWFgThc93fPCwSvUEQ
// SIG // YHRB+Qi1Ye8JIDCHofenB+fh9MRL5oOre7s7ZV19kle8
// SIG // XVGD8QN7441dxJFe2m0hw+Rx0GU63dxarA/1TmAAlFQT
// SIG // 68RfpFK2Rl8WCJ2U6a2DGBKulCBtQ0+KQlT/Q3GgixiD
// SIG // mBCdYNMCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBRJi+jR
// SIG // xF045b3wL0DNtXczFpPK0jAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // XF58bzg8JOIf421AbJxZRba0rgQWW+8EmX2uZSkTEzXz
// SIG // ZZmgAuG3e1qNCOYTMbBCVMrqR8IeJA+apEWXMyHNIyAA
// SIG // UENcQ1AWvlk8a6f1AKgte4oxQnj2SmFYzax3/wZo8+xW
// SIG // jiONZMbnkYcCzSHENoJgag0eVuE0tobUSWMmQLO43yZm
// SIG // w7U3FDjIRJdTlpcfxZ73EG6LeVT82lMIk+jYnvJej2Y6
// SIG // ELLsYmrLkgJsSiEHbB5yeUKJKsHcql4tRWQ7RE1b213w
// SIG // 7KH807WuHp9qn+PIcxGcFL25M+bJrfPdJ1QCu5M9nK68
// SIG // zd4aZ3xbn7af61y1k78T0HH1l4hLiFHdhoO3kfELcirS
// SIG // Q1PPjw8BApM6GiY2xgiqsfREoBSc861zcIYV+kXPINhF
// SIG // P/ut5pqlnghf5CThYNnicO2rv2mxEoKtxGs8g9VZS/h2
// SIG // l/jARxs0Jh7bzpt0JeMFUzd1qvF/GwkevKoheaxWrJuE
// SIG // cRes2o2Xkhwv6kud9+v+GjA6rFejvOkZTzwmBiTj7X9j
// SIG // Gyju1ySXi/1EDdHN7oseUTE6OunWwE8T1BRBuT4eDx8x
// SIG // o1GxDuw9+S7hAYohvGK5TETpBpd3wUJfW1m4MPQiFEG8
// SIG // KuXE2hMZXxKTHUqMnSaJVE0A+RCyhs9UyWoU4nXdtMJc
// SIG // IuQZN+lyJs7B+GLNeYl0XwIwggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDTTCCAjUCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjo5MjAwLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUAfO+tqz00HeyJ
// SIG // wwkHW9ZIBSkJAkSggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOwN
// SIG // DIYwIhgPMjAyNTA2MzAxMzE1NTBaGA8yMDI1MDcwMTEz
// SIG // MTU1MFowdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA7A0M
// SIG // hgIBADAHAgEAAgIGUjAHAgEAAgISfzAKAgUA7A5eBgIB
// SIG // ADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMC
// SIG // oAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3
// SIG // DQEBCwUAA4IBAQBs/iJuA/ovEN/YkvkNRLce/BqBe8la
// SIG // k0qHZ+gX1iuOSVn7MC3jgJ/leGz3wViLD94yYr6ZSi6Z
// SIG // n2YA6aZCdutYidBCsQW+nViVpMnpMDiuO2+y2atOsP26
// SIG // /fTKgwUChQfhQpZNUgo82CgLahnRMNYX5DwNmlMLEqfZ
// SIG // Ui+IPhMX9xZoKer92rRwkOkKB3tF22XUGkUTuJ+eLZAF
// SIG // thOza3XAxuw7AhEifo2m3cOuKLl08r25slx6NUdgOYEp
// SIG // ejBWNYUxaIkZjzRB6aVbtVdp38S7jU9NyJWMpnXL35J8
// SIG // eo7UPXee2xoUA99n6XpDYYwVAehHId6wllRlfAKIz9/D
// SIG // Cc2pMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
// SIG // bXAgUENBIDIwMTACEzMAAAIJCAfg+VyM5lUAAQAAAgkw
// SIG // DQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzEN
// SIG // BgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQg33pd
// SIG // 3MLjABQ17ouYf/uVyHXiwxbtbUrk1OA4xdy4oHowgfoG
// SIG // CyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCBoGyweyL30
// SIG // Ai5lDlGYY3VKivG4pHwemVVXaE4zcIUTPjCBmDCBgKR+
// SIG // MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
// SIG // Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAC
// SIG // CQgH4PlcjOZVAAEAAAIJMCIEIFoJJYPIIv8TolmZVP8C
// SIG // lACrvfr1aPRonRIaAi/23ZFhMA0GCSqGSIb3DQEBCwUA
// SIG // BIICAE+bclwqESfqsSL/7cVOMgd0ZzcNcOlfgoWdQAag
// SIG // rWoD+8H1Q16FdlvDc9yNu8JVAyYI37wevDVD1WMUtFdd
// SIG // WTkpH83lwW48zIMOow5zf7poeyVcJHeSGlpdPxyAEhRv
// SIG // 5QoEO46iroOcUmqg0gfhA56QXu0lvjgyQ2Ya2PEhYHHD
// SIG // 9m3hlisBSbSfWgM7FqDa2yuFOFidhC4FfIEJhc4Pu72Q
// SIG // 1YmLFgPM3IE7UFi316HARlJ3qH25jh+el5Awv/2RnJly
// SIG // mnA4r+WxB7XtG8eR29UQLtsqUrYhL6ni5AlDJ6MQGNPF
// SIG // Cnx1Y8DSwg1Lb5a+EXp7b9bxZ/Lxt9YVctcvtr+VqxGw
// SIG // t7jHkyUotg6ER3KT6F10ro9EcCK+SEx6YdOmJxSGUff3
// SIG // o9b3L57LUZXGHrULmuHX0LBuWXr+AeTBSoo4kq1Q6y74
// SIG // c6t7K+DdhrK7OF/Q9Bk/6h5yzqbJY1/PjZOXIffvqyNx
// SIG // uq8hqJ6QiCD+4jb+skptjrfYBqRQiBZpP5kxnmgoKABH
// SIG // Sr+0Yt+EF0diYIwgveEo0R+rayR0ZFlzNbZbu4juafVF
// SIG // gpHk1DWxuM7+AROSKM3nDbJNpdquQOrJ5j+XWNVG9+Kp
// SIG // hnLES2aX9X5O+GxHhgO42gqXdHvDzp/7Hhe9wIDCgLeF
// SIG // UFmk8qk1cMMhGVn09aKcisITSNcA
// SIG // End signature block
