define("eventsViewerSwimlane",["diagnosticsHub","diagnosticsHub-swimlanes","plugin-vs-v2"],((e,t,i)=>{return s={952:(e,t,i)=>{var s;s=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FilterLimit=t.errorNameCanceled=t.EventCountLimit=t.AnyStacksViewId=t.EventsViewerAnalyzerId=t.EventsListDetailsViewId=void 0,t.EventsListDetailsViewId=function(){return"AC3DC4D0-1FCC-4849-9F63-C8FFB47EC1DC"},t.EventsViewerAnalyzerId=function(){return"D9A8E704-BD31-402F-8990-A33EFB271CF0"},t.AnyStacksViewId=function(){return"FBF21B2D-E165-4C4E-8B10-36F0BC084F20"},t.EventCountLimit=function(){return 2e4},t.errorNameCanceled=function(){return"Canceled"},t.FilterLimit=function(){return 32766}}.apply(t,[i,t]),void 0===s||(e.exports=s)},398:(e,t,i)=>{var s,n;s=[i,t,i(226),i(560),i(560),i(560),i(560),i(117),i(117),i(117),i(117),i(117)],n=function(e,t,i,s,n,a,r,o,h,c,d,l){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BarGraphDataSeries=void 0,t.BarGraphDataSeries=class{constructor(e,t,a,r){this._context={},this._dataWarehouseRequestHandle=1,this._droppedRequest=!1,this._logger=d.getLogger("BarGraphDataSeries"),this._viewEventManager=l.getViewEventManager(),this._minValue=Number.MAX_VALUE,this._maxValue=Number.MIN_VALUE,this._sampledPoints=[],this._data=[],this._width=250,this._aggregationSpan=200,this._newDataEvent=new h.AggregatedEvent,this._dataSeriesInfo={},this.legendData=[],this.topSeriesIds=[],this._msToNano=1e6,this._minBarWidth=4,this._gapPx=2,this._analyzerId=e.AnalyzerId,this._viewport=t,this._title=r.getString("EventsViewerDataSeries"),this._graphResources=r,this._barWidth=this._minBarWidth;const c=n.Utilities.getColorSet();this._colors=c.map((e=>new s.ChartColorScheme(e,e))),this._onThemeChangedBoundFunction=()=>this.onThemeChanged(),i.Theme.addEventListener("themechanged",this._onThemeChangedBoundFunction),this._unitConverter=a,this._marker=document.createElement("div"),this._marker.classList.add("countersDataSeries-marker"),this._context.timeDomain=this._viewport,this._context.customDomain=e.CustomDomain||{},this._context.customDomain.Task="GetCounter",this._context.customDomain.CounterId=e.CounterId;const u=this.calculateNumBuckets();this._context.customDomain.NumBuckets=(0!==u?u:1).toString(),this._viewEventManager.processSelectionChanged.addEventListener((e=>{this._processKeys=e.pkeys,this.requestUpdate()})),o.loadDataWarehouse().then((e=>{this._dataWarehouseHandle=e,this._dataWarehouseRequestHandle=null,this._droppedRequest=!1,this.requestUpdate()}))}get graphLegendData(){return this.legendData}get minValue(){return this._minValue}get maxValue(){return this._maxValue}get marker(){return this._marker}get title(){return this._title}get newDataEvent(){return this._newDataEvent}dispose(){this._newDataEvent.dispose(),i.Theme.removeEventListener("themechanged",this._onThemeChangedBoundFunction)}onDataUpdate(e){this.requestUpdate()}onViewportChanged(e){this._viewport=e,this.requestUpdate()}onThemeChanged(){const e=n.Utilities.getColorSet();this._colors=e.map((e=>new s.ChartColorScheme(e,e))),this.requestUpdate()}draw(e,t){if(0!==this._sampledPoints.length){if(t.chartRect.width!==this._width){this._logger.debug(`swimlane width: ${t.chartRect.width}`);const e=this._width;this._width=t.chartRect.width;const i=this.calculateNumBuckets();if(this._context.customDomain.NumBuckets=(0!==i?i:1).toString(),this.requestUpdate(),250===e)return}this._barWidth=this.calculateBarWidth(),this._sampledPoints.forEach((i=>{this.drawSingleBar(e,t,i)}))}}calculateNumBuckets(){const e=parseInt(c.BigNumber.divide(this._viewport.end,c.BigNumber.convertFromNumber(this._aggregationSpan*this._msToNano)).value,16),t=Math.floor(this._width/(this._minBarWidth+this._gapPx));return Math.min(e,t)}calculateBarWidth(){const e=c.BigNumber.subtract(this._viewport.end,this._viewport.begin),t=parseInt(e.value,16)/(this._width*this._msToNano);return t*this._minBarWidth>=this._aggregationSpan?this._minBarWidth:this._aggregationSpan/t-this._gapPx}drawSingleBar(e,t,i){let s=0,a=t.chartRect.height-n.Utilities.scaleToRange(0,t.gridY.min,t.gridY.max,0,t.chartRect.height);e.save(),e.lineWidth=t.chartRect.height<100?1:2;const r=this.populateBarInfo(t,i);for(const t in r){const i=r[t];e.fillStyle=i.color.lineFillColor,e.strokeStyle=i.color.lineColor;const n=0===s?a:s+a-2;e.fillRect(i.xCoordinate,n,this._barWidth,i.height),a=n,s=i.height}e.restore()}populateBarInfo(e,t){const i={};let s=0;const a=this._barWidth/2;if(t.forEach((t=>{let r=-1*n.Utilities.scaleToRange(t.Value,e.gridY.min,e.gridY.max,0,e.chartRect.height);var o;Math.abs(r)<1&&0!==r&&(r=-1),s+=r,i[t.Id]={color:this._dataSeriesInfo[t.Id],series:t.Series,height:r,xCoordinate:(o=t.Timestamp,n.Utilities.convertToPixel(o,e.gridX,e.chartRect.width,!1)-a)}})),Math.abs(s)>e.chartRect.height){const t=e.chartRect.height/Math.abs(s);for(const e in i)i[e].height*=t}return i}getPointAtTimestamp(e,t=a.PointToFind.Nearest){if(0===this._sampledPoints.length)return null;const i=this.getOccurrencePointIndex(this._sampledPoints.map((e=>e[0].Timestamp)),e,0,this._sampledPoints.length-1,t),s=this._sampledPoints[i];let n=`${this._graphResources.getString("EventsViewerTooltip")}\n`;return s.forEach((e=>{0!==e.Value&&(n+=`${e.Series}: ${this._unitConverter.formatNumber(e.Value)}\n`)})),{timestamp:s[0].Timestamp,tooltip:n,value:Number.NaN}}getOccurrencePointIndex(e,t,i,s,r){const o=(e,t)=>t.greaterOrEqual(e);switch(r){case a.PointToFind.LessThanOrEqual:return n.Utilities.findLessThan(e,t,o,i,s);case a.PointToFind.GreaterThanOrEqual:return n.Utilities.findGreaterThan(e,t,o,i,s);case a.PointToFind.Nearest:default:{i=n.Utilities.findLessThan(e,t,o),s=Math.min(i+1,e.length-1);const a=c.BigNumber.subtract(t,e[i]),r=c.BigNumber.subtract(e[s],t);return a.greater(r)?s:i}}}requestUpdate(){this._dataWarehouseRequestHandle?this._droppedRequest=!0:this._dataWarehouseRequestHandle=window.setTimeout((()=>{this._context.timeDomain=this._viewport,this._dataWarehouseHandle.getFilteredData(this._context,this._analyzerId).then((e=>{if(e&&"getResult"in e&&"function"==typeof e.getResult){let t;return e.getResult({processKeys:this._processKeys}).then((i=>(t=i,e.dispose()))).then((()=>t))}return e})).then((e=>(this.setLegendData(e.s),e.p))).then((e=>this.convertDtoToIPointArray(e))).then((e=>this.cachePoints(e))).then((()=>{this._newDataEvent.invokeEvent(this),this._dataWarehouseRequestHandle=null,this._droppedRequest&&(window.setTimeout((()=>this.requestUpdate()),r.Constants.TimeoutImmediate),this._droppedRequest=!1)}),(e=>{this._logger.error(`Error occurred while communicating with the DataWarehouse: ${JSON.stringify(e)}`)}))}),r.Constants.TimeoutImmediate)}convertDtoToIPointArray(e){return e.map((e=>{let t=0;return e.v.map((i=>{const s=this.topSeriesIds[t],n=Object.keys(s)[0];return t++,{Timestamp:new c.BigNumber(e.t.h,e.t.l),Value:i,Series:s[n],ToolTip:e.tt,Id:n}}))}))}setLegendData(e){let t=0;this.legendData=[],this.topSeriesIds=e,e.forEach((e=>{const i=this._colors[t],s=Object.keys(e)[0],n=e[s];this._dataSeriesInfo[s]=i,t++,this.legendData.push({color:i.lineFillColor,legendText:n,legendTooltip:this._graphResources.getString("EventsViewerLegendTooltip",n)})}))}cachePoints(e){if(this._data=[],this._maxValue=Number.MIN_VALUE,this._minValue=Number.MAX_VALUE,!e||0===e.length||0===e[0].length)return;const t={};Object.keys(this._dataSeriesInfo).forEach((e=>{t[e]=new c.BigNumber(0,0)}));for(let i=0;i<e.length;i++){const s=e[i];let n=0;this._data[i]=s.filter((e=>!(!e.Timestamp||!e.Timestamp.greaterOrEqual(t[e.Id])||(n+=e.Value,t[e.Id]=e.Timestamp,0)))),this._maxValue=Math.max(this._maxValue,n),this._minValue=Math.min(this._minValue,n)}this._sampledPoints=this._data}}}.apply(t,s),void 0===n||(e.exports=n)},677:(e,t,i)=>{var s,n;s=[i,t,i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(117),i(117)],n=function(e,t,i,s,n,a,r,o,h,c,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CustomMultiSeriesGraph=void 0,t.CustomMultiSeriesGraph=class{constructor(e,t){this._defaultColorScheme=new r.ChartColorScheme("rgb(118, 174, 200)","rgba(118, 174, 200, 0.65)"),this._currentTimespan=new d.JsonTimespan(d.BigNumber.zero,d.BigNumber.zero),this._dataSeries=[],this._clientWidth=0,this._clientHeight=0,this._scaleIncreaseRatio=1.1,this._scaleChangedEvent=new c.AggregatedEvent,this._container=document.createElement("div"),this._container.classList.add("graphContainer"),this._container.tabIndex=0,this._container.style.zIndex=i.Constants.GraphContainerZIndex.toString(),this._canvas=document.createElement("canvas"),this._canvas.classList.add("graph-canvas"),this._context=this._canvas.getContext("2d"),this._unitConverter=new s.LocalizedUnitConverter(e.jsonConfig.Units,e.resources),this._currentTimespan=e.timeRange,this._scaleMin=e.scale.minimum,this._scaleMax=e.scale.maximum,this._isScaleFixed=e.scale.isFixed,this._onNewSeriesDataBoundFunction=e=>this.onNewSeriesData(e),e.jsonConfig.Unit&&(e.unit=e.resources[e.jsonConfig.Unit]),this._container.appendChild(this._canvas),e.jsonConfig.Series.forEach((t=>{let i;const s=t.Color?new r.ChartColorScheme(t.Color.Line,t.Color.Fill):this._defaultColorScheme;if(t.DataSource.AnalyzerId.toLowerCase()===o.CountersDataSeries.analyzerId.toLowerCase())i=new o.CountersDataSeries(t.DataSource.CounterId,this._currentTimespan,this._unitConverter,s,e.resources[t.Legend],e.resources[t.LegendTooltip]);else{const n=!e.jsonConfig.RefreshDataOnResizeAndZoom;i=new h.CustomCounterDataSeries(t.DataSource,this._currentTimespan,n,e.resources[t.Legend],e.resources[t.LegendTooltip],s,this._unitConverter)}e.legend.push({legendText:i.title,legendTooltip:i.tooltip,marker:i.marker}),i.newDataEvent.addEventListener(this._onNewSeriesDataBoundFunction),this._dataSeries.push(i)})),t&&t.forEach((e=>{e.newDataEvent.addEventListener(this._onNewSeriesDataBoundFunction),this._dataSeries.push(e)})),this._dataCursor=new n.DataCursor(this._container,this._dataSeries,this._currentTimespan,e.swimlaneId,this._scaleMin,this._scaleMax),this._scaleChangedEvent.addEventListener(this._dataCursor.onScaleChanged.bind(this._dataCursor)),this._container.appendChild(this._dataCursor.container)}get container(){return this._container}get scaleChangedEvent(){return this._scaleChangedEvent}dispose(){this._dataCursor.dispose(),this._dataSeries.forEach((e=>{e.newDataEvent.removeEventListener(this._onNewSeriesDataBoundFunction),e.dispose&&e.dispose()})),this._scaleChangedEvent.dispose()}resize(e){const t=this._container.clientWidth,i=this._container.clientHeight;this._clientWidth===t&&this._clientHeight===i||(this._clientWidth=t,this._clientHeight=i,this._canvas.width=this._clientWidth,this._canvas.height=this._clientHeight,this._dataCursor.resize(e),this.draw())}onDataUpdate(e){this._dataSeries.forEach((t=>{t.onDataUpdate&&t.onDataUpdate(e)}))}addSeriesData(e,t,i,s){}removeInvalidPoints(e){}render(e,t){}onViewportChanged(e){e.isIntermittent||this._currentTimespan.equals(e.currentTimespan)||(this._currentTimespan=e.currentTimespan,this._dataCursor.onViewportChanged(e),this._dataSeries.forEach((e=>{e.onViewportChanged(this._currentTimespan)})),this.draw())}onNewSeriesData(e){let t=!1;if(!this._isScaleFixed&&!isNaN(e.minValue)&&e.minValue<this._scaleMin&&(this._scaleMin=e.minValue,t=!0),this._isScaleFixed||isNaN(e.maxValue)||(this._scaleMax=e.maxValue,t=!0),this.draw(),t){const e=this._unitConverter.scaleValue(this._scaleMax);this._scaleChangedEvent.invokeEvent({minimum:this._scaleMin,maximum:this._scaleMax,unit:e.unit})}}draw(){this._context.clearRect(0,0,this._clientWidth,this._clientHeight),this._context.save();const e={gridX:this._currentTimespan,gridY:new a.MinMaxNumber(this._scaleMin,this._scaleMax),chartRect:new a.RectangleDimension(0,0,this._clientWidth,this._clientHeight)};this._dataSeries.forEach((t=>{t.draw(this._context,e)})),this._context.restore()}}}.apply(t,s),void 0===n||(e.exports=n)},875:(e,t,i)=>{var s,n;s=[i,t,i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(398),i(560),i(585),i(677),i(952)],n=function(e,t,i,s,n,a,r,o,h,c,d,l,u,_){"use strict";function g(e,t,g,m,p,v){const C=new a.SwimlaneConfiguration(e,p,m);C.header.isBodyExpanded=t;const w=C.graph,S=new s.LocalizedUnitConverter(w.jsonConfig.Units,w.resources),E={CounterId:"",AnalyzerId:_.EventsViewerAnalyzerId()},f=[],x=new l.GraphResources(w.resources),T=new c.BarGraphDataSeries(E,C.graph.timeRange,S,x);f.push(T);const D=new u.CustomMultiSeriesGraph(w,f);D.container.setAttribute("aria-label",e.Title);const R=new r.Scale(C.graph.scale,i.ScaleType.Left,S),b=new r.Scale(C.graph.scale,i.ScaleType.Right,S);D.scaleChangedEvent.addEventListener(R.onScaleChanged.bind(R)),D.scaleChangedEvent.addEventListener(b.onScaleChanged.bind(b)),C.header.unit=C.graph.unit;const I=new n.SwimlaneBase(C.header,C.graph.height,p,v);return D.scaleChangedEvent.addEventListener(I.onScaleChanged.bind(I)),I.addMainRegionControl(new o.SelectionOverlay(D,p,v,C.id)),I.addMainRegionControl(new h.GridLineRenderer(p)),I.addLeftRegionControl(R),I.addRightRegionControl(b),I.addTitleControl(new d.CustomLegend(T)),I}Object.defineProperty(t,"__esModule",{value:!0}),t.EventsViewerSwimlaneFactory=void 0,t.EventsViewerSwimlaneFactory=g,window.EventsViewerSwimlaneFactory=g}.apply(t,s),void 0===n||(e.exports=n)},585:(e,t,i)=>{var s,n;s=[i,t,i(226),i(560)],n=function(e,t,i,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.GraphResources=void 0;class n{constructor(e){this._graphResources=e}getString(e,...t){if(this._graphResources){let i=this._graphResources[e];if(void 0!==i)return i=s.Utilities.formatString(i,...t),i}try{return i.Resources.getString.apply(i.Resources,...t)}catch(e){}return e}}t.GraphResources=n,n.FORMAT_REG_EXP=/\{{2}|\{(\d+)\}|\}{2}|\{|\}/g}.apply(t,s),void 0===n||(e.exports=n)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},226:e=>{"use strict";e.exports=i}},n={},function e(t){var i=n[t];if(void 0!==i)return i.exports;var a=n[t]={exports:{}};return s[t](a,a.exports,e),a.exports}(875);var s,n}));
// SIG // Begin signature block
// SIG // MIIoRAYJKoZIhvcNAQcCoIIoNTCCKDECAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // 12URp5rZ2dRo2tGd8B6LR2dvWIEB/VA9OcCgZ/cMAkmg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghomMIIaIgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCA7VlF9kRp6bIBGI/zhhOlt2mHddBHKHMmS
// SIG // DcpC0T3mwTBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAJxdMtXJ
// SIG // pLKm4fJCH29iJu4oVVRRxVIWIIj+rqeeL58yHc1NBldO
// SIG // LWFGCEGvYA9xj59jP3Y16Tw6uK/ht08aRn2cpMs5RJY8
// SIG // hk3JuvsRaYlUPkq9hKd2tQFsfKw5ask1hfhL+/CgPoh+
// SIG // xdyZJg6RwYkIhHvNezmp1ve1IG1Uu9Ari5v0V4bJHgjV
// SIG // deTEw7SUo/01OyTtofm2u5Zo+a+r/oRhjNvZJxlfEB6k
// SIG // O3Tx/M9NNIBKaC+4dNOnyN/yIbAgx+sIjEJ5TF+cZMws
// SIG // cEHChEPhfKKb8nUORyUVJWMCLo229yqklzUb2uO1tiBm
// SIG // VtFq+7kcuhzw6LifV9ARfEAB5pqhghewMIIXrAYKKwYB
// SIG // BAGCNwMDATGCF5wwgheYBgkqhkiG9w0BBwKggheJMIIX
// SIG // hQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBWgYLKoZIhvcN
// SIG // AQkQAQSgggFJBIIBRTCCAUECAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgoNTo0OTeeKiqVL83nNxu
// SIG // xudlQrn9nnlzgxcDaBT5wN0CBmhTAU1zbxgTMjAyNTA2
// SIG // MzAxNDQ0MjcuMjQ5WjAEgAIB9KCB2aSB1jCB0zELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0
// SIG // IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMScwJQYD
// SIG // VQQLEx5uU2hpZWxkIFRTUyBFU046NTkxQS0wNUUwLUQ5
// SIG // NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFNlcnZpY2WgghH+MIIHKDCCBRCgAwIBAgITMwAAAfQX
// SIG // RoXAyz855QABAAAB9DANBgkqhkiG9w0BAQsFADB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNDA3MjUx
// SIG // ODMwNTlaFw0yNTEwMjIxODMwNTlaMIHTMQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
// SIG // bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
// SIG // Hm5TaGllbGQgVFNTIEVTTjo1OTFBLTA1RTAtRDk0NzEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKcIThOm0IAvaquIyRl9gNcqDm35NKnrUPJJI/uZ
// SIG // t+1gcQ5bGeaCZ438x7Kaj4jhFc2dstsoBoDWd/8XWUDe
// SIG // 3/QNVqdQHYeah12WYd0gV/AAbnOvU293CeSgmXFw7Ln8
// SIG // Jl3go/NRMyRCGarlXVfEk5ULngf29TCGLeUSorN7sM3Z
// SIG // X0pdHJB2xs6DvdWEyoOiBMaimKIxq3gqKZyCsTr5K+VW
// SIG // bI9n/eQW9SxhL7oQSJvwuycrLybwWVjba7Kc8l1Z7qPp
// SIG // AxMmcKZKYbEfGb3YvrP6UIqH5nW1tVKs1pal0FYKGF22
// SIG // mJBMmkof4XgbcI9bbnvi3LjnBwD4G8Gb0C5LCmiuOqJL
// SIG // a3oDkeHtInLBogFkfSC/p8uJpQlDQPOBexhBFjhL4m4o
// SIG // O8LK02umW87jLMk4tgM+Kj1d0EZBYMUm6eEeDhCp4p/C
// SIG // c+FyyNcF4QYSKTBnwNwU/OdJ6mps0og+S+acflbXwotD
// SIG // CU0tiwxdT2lWcJclWSFY1RyvKIdh2BvU9uhY0ffyPOYu
// SIG // RMcZoR6cTNmflISXmQOi8+Odpv/sawOMa3WGrOXJuxVI
// SIG // ctuKzy1R/hcvmcsBwKfXPaFk67Y3yCqiyL2LYCXONUPF
// SIG // sW2T0ewdbn7fARbL89nTki5MTwy3F1stegDcu979IqQs
// SIG // QMFBAvYbLItC3QfE4YjX/+APkWfLAgMBAAGjggFJMIIB
// SIG // RTAdBgNVHQ4EFgQUK3RloQrRLD4ndSyc7E2i0ykG35sw
// SIG // HwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIw
// SIG // XwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0JTIw
// SIG // VGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
// SIG // CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9N
// SIG // aWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAx
// SIG // MCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8E
// SIG // DDAKBggrBgEFBQcDCDAOBgNVHQ8BAf8EBAMCB4AwDQYJ
// SIG // KoZIhvcNAQELBQADggIBAN3B0g8SSlA7IGnCH0V+tLoD
// SIG // g0obAasLRFEVG1F3g5mGEmuaBY9+Ebo1t4Dngrfzmwzu
// SIG // Ob36Z2BuTkuWKMMLBcNfYIgiOiVfnHBv6qjNPJ8QEm88
// SIG // FraraK80IiYfbqbBOE1WXimF5m8se1jfbXW1SKwnpVY+
// SIG // z+onzB00i7egZsqEtsZQtnH4CjzwNd70t3rqlJes8Hux
// SIG // gIY34zV4ypROEjVib3aoK79BlESo6pmpjb4ZkiWp3uk2
// SIG // M6XQwnoKvGnZRh/OSNRFipnxEW9ZcysuTjDtnvSJAJb8
// SIG // naVLp9At7DRLadHoZYk9Eq2qvI3GFQx+ANgvzGywSMIp
// SIG // I8IhRkOEpRS09k4G+Br76XFlcwccA6PSEQcKc54G8s24
// SIG // YfeVFTq0C9q21h6xw0hN3YHS9srmh0YGOx2GC7OS7bN9
// SIG // MFPTrofDeeEVLWuhhWRceQOLiE4MiXFXVlWjdKo7NHhI
// SIG // 8BMjVL9HES7h1iQXo5DHt6kQIbwo54a6OwxkVmiJXcn8
// SIG // 2apZ+hbJy0N25fmb1SVk2Cbi/iGSyNkotyKyEX43HJ9v
// SIG // V9gV/789inGLmyIyul32L62UDeFym570qgTQMCD2NsSX
// SIG // geKPTwxBSNq3D2i1Ms+SFeyT9yUaYIN8bFKrxR5Uhurj
// SIG // CFo8B9BkCCMKwts0cvpTWbDip67sshzEEz+48uVPdqhB
// SIG // MIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJmQAAAAAA
// SIG // FTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2Vy
// SIG // dGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMw
// SIG // MTgyMjI1WhcNMzAwOTMwMTgzMjI1WjB8MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
// SIG // BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O
// SIG // 1YLT/e6cBwfSqWxOdcjKNVf2AX9sSuDivbk+F2Az/1xP
// SIG // x2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhgfWpS
// SIG // g0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/Y
// SIG // JlN8OWECesSq/XJprx2rrPY2vjUmZNqYO7oaezOtgFt+
// SIG // jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/dvI2k45GP
// SIG // sjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6
// SIG // BVWYbWg7mka97aSueik3rMvrg0XnRm7KMtXAhjBcTyzi
// SIG // YrLNueKNiOSWrAFKu75xqRdbZ2De+JKRHh09/SDPc31B
// SIG // mkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn42
// SIG // 7DZM9ituqBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n
// SIG // 6Jl8P0zbr17C89XYcz1DTsEzOUyOArxCaC4Q6oRRRuLR
// SIG // vWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2
// SIG // ZItboKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9
// SIG // stQcxWv2XFJRXRLbJbqvUAV6bMURHXLvjflSxIUXk8A8
// SIG // FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
// SIG // AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQAB
// SIG // MCMGCSsGAQQBgjcVAgQWBBQqp1L+ZMSavoKRPEY1Kc8Q
// SIG // /y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacbUzUZ
// SIG // 6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/
// SIG // BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnkuaHRtMBMG
// SIG // A1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQM
// SIG // HgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMB
// SIG // Af8EBTADAQH/MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjR
// SIG // PZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6
// SIG // Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1
// SIG // Y3RzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBa
// SIG // BggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWlj
// SIG // Um9vQ2VyQXV0XzIwMTAtMDYtMjMuY3J0MA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
// SIG // XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x
// SIG // 5MKP+2zRoZQYIu7pZmc6U03dmLq2HnjYNi6cqYJWAAOw
// SIG // Bb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVtI1Tk
// SIG // eFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8Z
// SIG // thISEV09J+BAljis9/kpicO8F7BUhUKz/AyeixmJ5/AL
// SIG // aoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTpkbKpW99J
// SIG // o3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32
// SIG // THJvEKt1MMU0sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEU
// SIG // BHG/ZPkkvnNtyo4JvbMBV0lUZNlz138eW0QBjloZkWsN
// SIG // n6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQ
// SIG // THa1V1QJsWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+
// SIG // y/g75LcVv7TOPqUxUYS8vwLBgqJ7Fx0ViY1w/ue10Cga
// SIG // iQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0l
// SIG // lOZ0dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghi
// SIG // f9lwY1NNje6CbaUFEMFxBmoQtB1VM1izoXBm8qGCA1kw
// SIG // ggJBAgEBMIIBAaGB2aSB1jCB0zELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQg
// SIG // T3BlcmF0aW9ucyBMaW1pdGVkMScwJQYDVQQLEx5uU2hp
// SIG // ZWxkIFRTUyBFU046NTkxQS0wNUUwLUQ5NDcxJTAjBgNV
// SIG // BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wi
// SIG // IwoBATAHBgUrDgMCGgMVAL/i2f1YNLNe13pOIhvUfXP+
// SIG // /gCOoIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEm
// SIG // MCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // IDIwMTAwDQYJKoZIhvcNAQELBQACBQDsDKhAMCIYDzIw
// SIG // MjUwNjMwMDYwODAwWhgPMjAyNTA3MDEwNjA4MDBaMHcw
// SIG // PQYKKwYBBAGEWQoEATEvMC0wCgIFAOwMqEACAQAwCgIB
// SIG // AAICAuECAf8wBwIBAAICEs0wCgIFAOwN+cACAQAwNgYK
// SIG // KwYBBAGEWQoEAjEoMCYwDAYKKwYBBAGEWQoDAqAKMAgC
// SIG // AQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQsF
// SIG // AAOCAQEAj7dRDXeMRnVMPx58K5OGE8OV6wG0eM5eTGIT
// SIG // Z5RC/F38br9l+01H3itcRvkOu77Tsnutoj7Yr4aLk41r
// SIG // u2Ytlo8bOTeHqEbUDI+t/DhauK/vx3RqZS/Mbt33THMm
// SIG // jJtEdPTSZfMEKR5FaHp/R3M+hpzmsEWDC2l/6oMEP5WQ
// SIG // VFE8fKWebQc+q2fO+AwzyRBHVnKJHBPdE0R4TU9sebKT
// SIG // /iFimdSbh4DT6bwNel1Xg9hk/7xbbFET31bAUKYoGXey
// SIG // n/HQtuto/CMvoY0uYuNnW63eX/tYOkFGRStJV3iML5tu
// SIG // uVcx2aDXhmFzUxMCpWLEPSOmtsgCSDuLIfZrnxqaRTGC
// SIG // BA0wggQJAgEBMIGTMHwxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
// SIG // QSAyMDEwAhMzAAAB9BdGhcDLPznlAAEAAAH0MA0GCWCG
// SIG // SAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZI
// SIG // hvcNAQkQAQQwLwYJKoZIhvcNAQkEMSIEIJmNAJyqTY9D
// SIG // xEyU6K7v/+YKFzyIGx5rcVxl0GRuo5zEMIH6BgsqhkiG
// SIG // 9w0BCRACLzGB6jCB5zCB5DCBvQQgP1jCfG4mk+p475JJ
// SIG // wfEO4UkCIvMrOryAb2YOtEQY1mswgZgwgYCkfjB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAfQXRoXA
// SIG // yz855QABAAAB9DAiBCAblmIEokPmE7XdMOLrRRg9dzWE
// SIG // 2cUGVTCtjJFTbsO9HzANBgkqhkiG9w0BAQsFAASCAgB9
// SIG // t9TTLFRzRh3aHFyQW08GNV5meKRxWBOXyqDirVRg+5dP
// SIG // eC6VSNfPkHGRQzEiG/HoYjl919lmRy0SA/IDVsxKVNfM
// SIG // PEwdu2YmopypiFKcxoJ0nvLSw9ME07snkRcoDEGq/ehx
// SIG // kyhI3rirQhbFJBclzssraVtMQmCNToNJnbEK19HZLv9d
// SIG // CNvbmwMCB/oqAZJkbIVZHlLgFGdF1rJgN30b3Xnj/xqD
// SIG // zWeKWWFGIcg+wjO2g4PKwugFo5RuF4JfT4Tz3htI4r1H
// SIG // PUxdt8bh0jVghO4zwVv/dlt/gwxL+sIekt/cTQJqY6uj
// SIG // JQr77JfGO+GDpb8BaXb3Fg8647L3BXCoisv5JTBB8BK+
// SIG // eVNaiqIW+cvpjxAdW76+iNJjMljliVpIfLqO+he89R0V
// SIG // 0DLu9Ift+vtYuEN3Z1guqOiIF3PGj5wAnW+ebncuUzZt
// SIG // HMe8Er08VZXDD3+Qt9Lm4yQz6Q47BHJnAsUn7se6ua9t
// SIG // hLNkGh4DoOu2TRZrnMAZe41LhwvLBx/t5uXOoOkXA90V
// SIG // Gxaxi0zk+VjjTj4H9uHqD+Nd6eQv8tUgan1nWFTojWLV
// SIG // m1P6bBwPgqWchzIoTU2tMIQDeloKJLPZO5dkIYKteMQz
// SIG // YBQnBJF9aXvue8itYIi9JPgTKa49IrnUvrDxm/+mvzqd
// SIG // MMgKO9FT0H7LjJkUktFuDg==
// SIG // End signature block
