define("eventsViewerUI",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,s,i,o)=>{return n={149:e=>{const t=document.createElement("script");t.id="PropertyTableRowView",t.innerHTML=atob("PHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IG5hbWUsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdG9vbHRpcDogdG9vbHRpcCI+PC90ZD4NCjx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiB2YWx1ZSwNCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB0b29sdGlwOiB0b29sdGlwIj48L3RkPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},441:e=>{const t=document.createElement("script");t.id="CollapsibleTableView",t.innerHTML=atob("PGRpdiBjbGFzcz0iY29sbGFwc2libGVUYWJsZUNvbnRhaW5lciIgZGF0YS1iaW5kPSJ2aXNpYmxlOiByb3dzKCkubGVuZ3RoID4gMCwNCiAgICAgICAgICAgICAgIGNvbGxhcHNpYmxlVGFibGVGb2N1c2VkUm93OiB7IHJvd3M6IHJvd3MsIHNlbGVjdGVkOiBzZWxlY3RlZFJvd3MsIGZvY3VzZWQ6IGZvY3VzZWRSb3dJbmRleCB9Ij4NCiAgICA8ZGl2IGNsYXNzPSJzZWN0aW9uVGl0bGUiIHRhYmluZGV4PSIwIiBkYXRhLWJpbmQ9Ig0KICAgICAgICAgYXJpYUV4cGFuZGVkOiB7IGV4cGFuZGFibGU6IHRydWUsIGV4cGFuZGVkOiBleHBhbmRlZCB9LA0KICAgICAgICAgY2xpY2s6IHRvZ2dsZUV4cGFuZGVkLA0KICAgICAgICAgZXZlbnQ6IHsga2V5ZG93bjogdGl0bGVLZXlEb3duIH0iPg0KICAgICAgICA8ZGl2IGRhdGEtYmluZD0iZXhwYW5kZXI6IGV4cGFuZGVkIj48L2Rpdj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWRUZXh0OiBsYWJlbCI+PC9zcGFuPg0KICAgIDwvZGl2Pg0KICAgIDx0YWJsZSBkYXRhLWJpbmQ9InZpc2libGU6IGV4cGFuZGVkKCkiPg0KICAgICAgICA8dGJvZHkgdGFiaW5kZXg9IjAiIGRhdGEtYmluZD0iDQogICAgICAgICAgICAgICBjbGljazogb25DbGljaywNCiAgICAgICAgICAgICAgIGV2ZW50OiB7IGtleWRvd246IG9uS2V5RG93biB9LA0KICAgICAgICAgICAgICAgZHluYW1pY0NvbnRleHRNZW51OiBjb250ZXh0TWVudSI+DQogICAgICAgICAgICA8IS0tIGtvIGZvcmVhY2g6IHJvd3MgLS0+DQogICAgICAgICAgICA8dHIgdGFiaW5kZXg9Ii0xIiByb2xlPSJyb3ciIGRhdGEtYmluZD0iDQogICAgICAgICAgICAgICAgY29sbGFwc2libGVUYWJsZVJvd0ZvY3VzOiAkcGFyZW50LmZvY3VzZWRSb3coKSA9PT0gJGRhdGEsDQogICAgICAgICAgICAgICAgY3NzOiB7IHNlbGVjdGVkOiBzZWxlY3RlZCgpIH0sDQogICAgICAgICAgICAgICAgdGVtcGxhdGU6IHsgbmFtZTogdGVtcGxhdGVOYW1lIH0iPg0KICAgICAgICAgICAgPC90cj4NCiAgICAgICAgICAgIDwhLS0gL2tvIC0tPg0KICAgICAgICA8L3Rib2R5Pg0KICAgIDwvdGFibGU+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},661:e=>{const t=document.createElement("script");t.id="StackTableRowView",t.innerHTML=atob("PHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9InRleHQ6IGFkZHJlc3MsDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdG9vbHRpcDogdG9vbHRpcCI+PC90ZD4="),t.type="text/html",document.head.appendChild(t),e.exports={}},632:e=>{const t=document.createElement("script");t.id="EventsRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJkYXRhR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgZGF0YUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9Ij4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJldmVudE5hbWUiIGRhdGEtYmluZD0idGV4dDogZXZlbnROYW1lIiBkYXRhLWNvbHVtbmlkPSJldmVudE5hbWUiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iZm9ybWF0dGVkTWVzc2FnZSIgZGF0YS1iaW5kPSJ0ZXh0OiBmb3JtYXR0ZWRNZXNzYWdlIiBkYXRhLWNvbHVtbmlkPSJmb3JtYXR0ZWRNZXNzYWdlIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9ImFkanVzdGVkVGltZXN0YW1wTVNlYyIgZGF0YS1iaW5kPSJ0ZXh0OiBhZGp1c3RlZFRpbWVzdGFtcE1TZWMiIGRhdGEtY29sdW1uaWQ9ImFkanVzdGVkVGltZXN0YW1wTVNlYyI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJwcm92aWRlckd1aWQiIGRhdGEtYmluZD0idGV4dDogcHJvdmlkZXJHdWlkIiBkYXRhLWNvbHVtbmlkPSJwcm92aWRlckd1aWQiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iZXZlbnRJZCIgZGF0YS1iaW5kPSJ0ZXh0OiBldmVudElkIiBkYXRhLWNvbHVtbmlkPSJldmVudElkIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InVuaXhUaW1lSW5NaWxsaXNlY29uZHMiIGRhdGEtYmluZD0idGV4dDogdW5peFRpbWVJbk1pbGxpc2Vjb25kcyIgZGF0YS1jb2x1bW5pZD0idW5peFRpbWVJbk1pbGxpc2Vjb25kcyI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJwcm9jZXNzSWQiIGRhdGEtYmluZD0idGV4dDogcHJvY2Vzc0lkIiBkYXRhLWNvbHVtbmlkPSJwcm9jZXNzSWQiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0icHJvY2Vzc05hbWUiIGRhdGEtYmluZD0idGV4dDogcHJvY2Vzc05hbWUiIGRhdGEtY29sdW1uaWQ9InByb2Nlc3NOYW1lIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InRocmVhZElkIiBkYXRhLWJpbmQ9InRleHQ6IHRocmVhZElkIiBkYXRhLWNvbHVtbmlkPSJ0aHJlYWRJZCI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},853:(e,t,s)=>{var i,o;i=[s,t,s(28),s(560)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),s.bindingHandlers.collapsibleTableFocusedRow={init(e,t,o,n,r){let a=-1;e.addEventListener("keydown",(e=>{if(i.KeyCodes.Shift===e.keyCode){const e=t();return void(a=s.unwrap(e.focused))}if(i.KeyCodes.ArrowUp!==e.keyCode&&i.KeyCodes.ArrowDown!==e.keyCode)return;const o=t(),n=s.unwrap(o.rows);if(0===n.length)return;const r=s.unwrap(o.focused);let l=0;if(i.KeyCodes.ArrowUp===e.keyCode&&-1!==r?l=Math.max(r-1,0):i.KeyCodes.ArrowDown===e.keyCode&&-1!==r&&(l=Math.min(r+1,n.length-1)),e.shiftKey){const e=Math.max(Math.min(l,a),0),t=Math.max(l,a),s=[];for(let i=e;i<=t;++i)s.push(i);a>l&&s.reverse(),o.selected(s)}else o.selected([l]);e.preventDefault()}))},update(e,t,i,o,n){const r=t(),a=s.unwrap(r.focused);if(-1===a)return;const l=e.parentElement,d=l.scrollTop,c=l.clientHeight,u=s.unwrap(r.rows),h=e.clientHeight/u.length,g=l.children;let m=0;for(let t=0;t<g.length&&g[t]!==e;t++)m+=g[t].clientHeight;const p=a*h+m;p<d?l.scrollTop=Math.max(p,0):p+h>d+c&&(l.scrollTop=p+h-c)}}}.apply(t,i),void 0===o||(e.exports=o)},736:(e,t,s)=>{var i,o;i=[s,t,s(28),s(117)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),s.bindingHandlers.collapsibleTableRowFocus={previousElement:null,init(e,t,i,o,n){const r=()=>{if(s.bindingHandlers.collapsibleTableRowFocus.previousElement&&s.bindingHandlers.collapsibleTableRowFocus.previousElement!==e){const e=document.createEvent("Event");e.initEvent("blur",!1,!1),s.bindingHandlers.collapsibleTableRowFocus.previousElement.dispatchEvent(e)}const i=t();s.isWriteableObservable(i)&&!i()&&i(!0),s.bindingHandlers.collapsibleTableRowFocus.previousElement=e},a=()=>{const e=t();s.isWriteableObservable(e)&&e()&&e(!1)};e.addEventListener("focus",r),e.addEventListener("blur",a),s.utils.domNodeDisposal.addDisposeCallback(e,(()=>{e.removeEventListener("focus",r),e.removeEventListener("blur",a)}))},update(e,t,o,n,r){if(s.unwrap(t())){let t=e.parentElement;for(;t&&!t.classList.contains("collapsibleTableContainer");)t=t.parentElement;if(t){const s=t.scrollLeft;e.focus(),t.scrollLeft=s}else s.tasks.schedule((()=>{let t=e.parentElement;for(;t&&!t.classList.contains("collapsibleTableContainer");)t=t.parentElement;if(t){const s=t.scrollLeft;e.focus(),t.scrollLeft=s}else i.Assert.fail("Unable to find collapsibleTableContainer. Is this element a CollapsibleTable row?"),e.focus()}))}else e.blur()}}}.apply(t,i),void 0===o||(e.exports=o)},588:function(e,t,s){var i,o,n=this&&this.__createBinding||(Object.create?function(e,t,s,i){void 0===i&&(i=s),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[s]}})}:function(e,t,s,i){void 0===i&&(i=s),e[i]=t[s]}),r=this&&this.__exportStar||function(e,t){for(var s in e)"default"===s||Object.prototype.hasOwnProperty.call(t,s)||n(t,e,s)};i=[s,t,s(28),s(226),s(560),s(881),s(853),s(736),s(64),s(441)],o=function(e,t,s,i,o,n,a,l,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.CollapsibleTableViewModel=void 0;var c=i.ContextMenu;r(a,t),r(l,t),r(d,t),t.CollapsibleTableViewModel=class{constructor(e,t){this._selectedRows=s.observableArray([]),this._focusedRowIndex=s.pureComputed((()=>this.computedFocusedRowIndex())),this._focusedRow=s.pureComputed((()=>this.computeFocusedRow())),this._expanded=s.observable(!0),this._rows=e,this._label=t,this._selectedRows.subscribe(this.onSelectionChanged.bind(this),null,"arrayChange")}get selectedRows(){return this._selectedRows}get label(){return this._label}get expanded(){return this._expanded}get rows(){return this._rows}get focusedRowIndex(){return this._focusedRowIndex}get focusedRow(){return this._focusedRow}onClick(e,t){if(t.which!==o.MouseCodes.Left)return;const i=s.contextFor(t.target);if(!i||i.$data===this)return;const n=i.$data,r=this._rows().indexOf(n);if(t.ctrlKey){const e=this._selectedRows().indexOf(r);-1===e?this._selectedRows.push(r):this._selectedRows.splice(e,1)}else if(t.shiftKey){const e=Math.max(Math.min(this.focusedRowIndex(),r),0),t=Math.max(this.focusedRowIndex(),r),i=this._selectedRows(),o=[];for(let s=e;s<=t;++s)-1===i.indexOf(s)&&o.push(s);this.focusedRowIndex()>r&&o.reverse(),s.utils.arrayPushAll(this._selectedRows(),o),this._selectedRows.valueHasMutated()}else this._selectedRows([r])}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==o.KeyCodes.C)return!0;const s=this.formatSelectedRowsToText();return navigator.clipboard.writeText(s),!1}contextMenu(e,t){const s=e;if("string"!=typeof s.templateName)return null;const o=this._rows().indexOf(s);-1===this._selectedRows().indexOf(o)&&this._selectedRows([o]);const n=[{label:i.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=this.formatSelectedRowsToText();navigator.clipboard.writeText(e)},type:c.MenuItemType.command}];return c.create(n)}toggleExpanded(e,t){const s=this._expanded();this._expanded(!s)}titleKeyDown(e,t){if(t.keyCode===o.KeyCodes.ArrowRight)this._expanded(!0);else if(t.keyCode===o.KeyCodes.ArrowLeft)this._expanded(!1);else{if(t.keyCode!==o.KeyCodes.Space)return!0;this.toggleExpanded(e,null)}return!1}computedFocusedRowIndex(){const e=this._selectedRows();return e.length>0?e[e.length-1]:-1}computeFocusedRow(){const e=this.computedFocusedRowIndex();return-1!==e?this._rows()[e]:null}onSelectionChanged(e){e.forEach((e=>{void 0===e.moved&&this._rows()[e.value]&&("added"===e.status?this._rows()[e.value].selected(!0):"deleted"===e.status&&this._rows()[e.value].selected(!1))}))}formatSelectedRowsToText(){const e=this.selectedRows().sort(((e,t)=>n.SortFunctions.numberComparator(e,t)));let t="";for(let s=0;s<e.length;++s)t+=`${this.rows()[e[s]].tooltip}\r\n`;return t.trim()}}}.apply(t,i),void 0===o||(e.exports=o)},64:(e,t,s)=>{var i,o;i=[s,t,s(28)],o=function(e,t,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),s.bindingHandlers.expander={init:(e,t,s,i,o)=>(e.className="collapsibleTable-expander",{controlsDescendantBindings:!0}),update(e,t,i,o,n){s.unwrap(t())?e.classList.add("expanded"):e.classList.remove("expanded")}},s.virtualElements.allowedBindings.expander=!1}.apply(t,i),void 0===o||(e.exports=o)},355:(e,t,s)=>{var i,o;i=[s,t,s(28),s(117),s(149)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.PropertyTableRowViewModel=void 0,t.PropertyTableRowViewModel=class{constructor(e){this._logger=i.getLogger("PropertyTableRowViewModel"),this._selected=s.observable(!1),this._computeString=s.pureComputed((()=>`${this.name()}\t${this.value()}`)),2===e.length?(this._name=s.observable(e[0]),this._value=s.observable(e[1])):this._logger.error("Expected string array with length 2 for PropertyTableRowViewModel")}get templateName(){return"PropertyTableRowView"}get name(){return this._name}get value(){return this._value}get selected(){return this._selected}get tooltip(){return this._computeString()}}}.apply(t,i),void 0===o||(e.exports=o)},360:(e,t,s)=>{var i,o;i=[s,t,s(28),s(117),s(661)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.StackTableRowViewModel=void 0,t.StackTableRowViewModel=class{constructor(e){this._logger=i.getLogger("StackTableRowViewModel"),this._selected=s.observable(!1),this._computeString=s.pureComputed((()=>this.address())),1===e.length?this._address=s.observable(e[0]):this._logger.error("Expected string array with length 1 for StackTableRowViewModel")}get templateName(){return"StackTableRowView"}get address(){return this._address}get selected(){return this._selected}get tooltip(){return this._computeString()}}}.apply(t,i),void 0===o||(e.exports=o)},952:(e,t,s)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FilterLimit=t.errorNameCanceled=t.EventCountLimit=t.AnyStacksViewId=t.EventsViewerAnalyzerId=t.EventsListDetailsViewId=void 0,t.EventsListDetailsViewId=function(){return"AC3DC4D0-1FCC-4849-9F63-C8FFB47EC1DC"},t.EventsViewerAnalyzerId=function(){return"D9A8E704-BD31-402F-8990-A33EFB271CF0"},t.AnyStacksViewId=function(){return"FBF21B2D-E165-4C4E-8B10-36F0BC084F20"},t.EventCountLimit=function(){return 2e4},t.errorNameCanceled=function(){return"Canceled"},t.FilterLimit=function(){return 32766}}.apply(t,[s,t]),void 0===i||(e.exports=i)},334:(e,t,s)=>{var i,o;i=[s,t,s(28),s(226),s(952),s(560),s(560),s(881),s(881),s(881),s(881),s(881),s(881),s(881),s(881),s(117),s(117),s(117),s(152),s(337),s(766),s(758),s(588),s(355),s(360),s(886),s(680),s(833),s(103)],o=function(e,t,s,i,o,n,r,a,l,d,c,u,h,g,m,p,v,b,I,C,_,w,S,R,A,D){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getEventsListViewModel=t.EventsListViewModel=void 0;var f=i.ContextMenu;class y{constructor(){let e;this._commonProperties=s.pureComputed((()=>this._eventsListDAO.details()?this._eventsListDAO.details().cmp:[])),this._payloadProperties=s.pureComputed((()=>this._eventsListDAO.details()?this._eventsListDAO.details().plp:[])),this._stack=s.pureComputed((()=>this._eventsListDAO.details()?this._eventsListDAO.details().cs:[])),this._showDetails=s.pureComputed((()=>this._eventsListDAO.details()&&(this._eventsListDAO.details().plp.length>0||this._eventsListDAO.details().cmp.length>0||this._eventsListDAO.details().cs.length>0))),this._telemetry=new w.EventsViewerTelemetryMarshaler,this._viewEventManager=v.getViewEventManager(),this._currentOverlay=s.pureComputed((()=>this.computeOverlay())),this._isOverlayActive=s.pureComputed((()=>null!==this._currentOverlay())),this._showInfoBar=!0,this._loadDataWarehousePromise=b.loadDataWarehouse().then((t=>(e=t,e.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((t=>Promise.all([Promise.resolve(t),e.getJmcService().getJmcEnabledState(),E.isNativeCodeEnabled()]))).then((t=>{const[n,a,m]=t;this._eventsListDAO=new I.EventsListDAO(e,n,E);const p=new g.DataGridHeaderViewModel([{id:"eventName",text:i.Resources.getString("EventsListHeaderEventName"),hideable:!1,filterable:c.FilterType.Expandable},{id:"formattedMessage",text:i.Resources.getString("EventsListHeaderDescription"),hideable:!0},{id:"adjustedTimestampMSec",text:i.Resources.getString("EventsListHeaderAdjustedTimestampMSec"),hideable:!1,sortable:c.SortDirection.Asc},{id:"providerGuid",text:i.Resources.getString("EventsListHeaderProviderGuid"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat},{id:"eventId",text:i.Resources.getString("EventsListHeaderEventId"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat},{id:"unixTimeInMilliseconds",text:i.Resources.getString("UnixTimeInMilliseconds"),hideable:!0,sortable:c.SortDirection.Asc},{id:"processId",text:i.Resources.getString("EventsListHeaderProcessId"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat},{id:"processName",text:i.Resources.getString("EventsListHeaderProcessName"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat},{id:"threadId",text:i.Resources.getString("EventsListHeaderThreadId"),hideable:!0,sortable:c.SortDirection.Asc,filterable:c.FilterType.Flat}],new C.EventsListColumnSettingsProvider,this._eventsListDAO.defaultSortColumnId);this._showJmc=new u.ToggleButtonViewModel(void 0,void 0,"ShowJmc","ShowJmc"),this._showJmc.isChecked(a),this._showJmc.isChecked.subscribe((()=>{this._getJmcServicePromise=e.getJmcService().setJmcEnabledState(this._showJmc.isChecked()).then((()=>{const e=this._eventsList.selectedRows();e.length>=1&&this._eventsListDAO.rows()[e[0]].invoke()}))})),this._showNative=new u.ToggleButtonViewModel(void 0,void 0,"ShowNative","ShowNative"),this._showNative.isChecked.subscribe((e=>{E.setNativeCodeEnabled(e).then((()=>{const e=this._eventsList.selectedRows();e.length>=1&&this._eventsListDAO.rows()[e[0]].invoke()}))})),this._showNative.isChecked(m),E.onUpdateNativeCode.addEventListener((e=>{this._showNative.isChecked(e.isEnabled)})),this._eventsListFilter=new d.DataGridFilterViewModel(this._eventsListDAO.filterOptions,p),this._eventsList=new l.DataGridViewModel(this._eventsListDAO,p,"EventsListAriaLabel",this._eventsListFilter),this._clearFilters=new h.ToolbarButtonViewModel(void 0,"ResetFiltersText","ResetFiltersText",(()=>this.eventsListFilter.resetFilters())),this._payloadTable=new S.CollapsibleTableViewModel(s.pureComputed((()=>this._payloadProperties().map((e=>new R.PropertyTableRowViewModel(e))))),"EventsListSideBarPayloadHeader"),this._commonTable=new S.CollapsibleTableViewModel(s.pureComputed((()=>this._commonProperties().map((e=>new R.PropertyTableRowViewModel(e))))),"EventsListSideBarCommonHeader"),this._commonTable.expanded(!1),this._stackTable=new S.CollapsibleTableViewModel(s.pureComputed((()=>this._stack().map((e=>new A.StackTableRowViewModel(e))))),"EventsListSideBarStackHeader"),this._eventsList.onResultChanged(0),this._eventsListDAO.rows.subscribe((()=>{this._eventsList.onResultChanged(0)})),this._eventsListDAO.count.subscribe((e=>{if(this._showInfoBar){const t=document.getElementById("eventsViewerInfoBar");t&&t.parentElement.removeChild(t),e<o.EventCountLimit()?this._infoBar=new r.InformationBarControl(i.Resources.getString("InformationTotalEvents",e.toLocaleString(i.Culture.formatRegion))):this._infoBar=new r.InformationBarControl(i.Resources.getString("InformationClippedEvents",o.EventCountLimit().toLocaleString(i.Culture.formatRegion),e.toLocaleString(i.Culture.formatRegion))),this._infoBar.container.id="eventsViewerInfoBar",this._infoBar.onClose=()=>{const e=document.getElementById("eventsViewerInfoBar");e&&e.parentElement.removeChild(e)};const s=document.createElement("div");s.classList.add("information-link"),this._infoBar.container.appendChild(s);const n=document.createElement("a");n.text=i.Resources.getString("InformationClippedEventsDoNotShow"),n.setAttribute("role","link"),n.setAttribute("aria-label",i.Resources.getString("InformationClippedEventsDoNotShow")),n.classList.add("information-link-text"),n.onclick=()=>{this._showInfoBar=!1,this._infoBar.onClose()},s.appendChild(n),document.getElementById("mainToolbar").insertAdjacentElement("afterend",this._infoBar.container)}this._telemetry.displayedEventCount(e)})),this._eventsList.selectedRows.subscribe((e=>{1===e.length&&(this._eventsList.rows()[e[0]].invoke(),this._telemetry.additionalPropertiesRequested())})),this._isOverlayActive.subscribe((e=>{e&&this._infoBar&&this._infoBar.onClose()})),this._viewEventManager.selectionChanged.addEventListener((e=>{e.isIntermittent||this._eventsListDAO.timeFilter(e.position)})),this._viewEventManager.jmcEnabledStateChanged.addEventListener((e=>{this._showJmc.isChecked()!==e.currEnabledState&&this._showJmc.isChecked(e.currEnabledState)})),s.applyBindings(this),this._viewEventManager.detailsViewReady.raiseEvent({Id:o.EventsListDetailsViewId()})}))}get clearFilters(){return this._clearFilters}get showJmc(){return this._showJmc}get showNative(){return this._showNative}get payloadTable(){return this._payloadTable}get commonTable(){return this._commonTable}get stackTable(){return this._stackTable}get loadingProperties(){return this._eventsListDAO.loadingProperties}get showDetails(){return this._showDetails}get eventsList(){return this._eventsList}get eventsListFilter(){return this._eventsListFilter}get currentOverlay(){return this._currentOverlay}get dao(){return this._eventsListDAO}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==n.KeyCodes.C)return!0;const s=m.DataGridUtils.formatDataGridSelectedToText(this._eventsList);return navigator.clipboard.writeText(s),!1}contextMenu(e,t){const s=e;if("number"!=typeof s.id)return null;const o=e=>{this._showSourceFilePromise=this._eventsListDAO.showSourceFile(e).then()},n=this._eventsList.selectedRows().length>1;return this._eventsListDAO.loadAdditionalDetailsData(s.id).then((e=>{const t=[{label:i.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=m.DataGridUtils.formatDataGridSelectedToText(this._eventsList);navigator.clipboard.writeText(e)},type:f.MenuItemType.command},{type:f.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_TimeFilter_SetStart"),callback:()=>{this._getTimestampPromise=this._eventsListDAO.getTimestampInNanoseconds(s.id).then((e=>{const t=this._eventsListDAO.timeFilter().end;this._viewEventManager.selectionChanged.raiseEvent({position:new p.JsonTimespan(new p.BigNumber(e.h,e.l),t),isIntermittent:!1})}))},type:f.MenuItemType.command},{label:i.Resources.getString("ContextMenu_TimeFilter_SetEnd"),callback:()=>{this._getTimestampPromise=this._eventsListDAO.getTimestampInNanoseconds(s.id).then((e=>{const t=this._eventsListDAO.timeFilter().begin;this._viewEventManager.selectionChanged.raiseEvent({position:new p.JsonTimespan(t,new p.BigNumber(e.h,e.l)),isIntermittent:!1})}))},type:f.MenuItemType.command},{label:i.Resources.getString("ContextMenu_TimeFilter_SetInterval"),callback:()=>{const e=this.eventsList.selectedRows().map((e=>this.eventsList.rows()[e].id));this._getTimestampPromise=this._eventsListDAO.getMinMaxTimestampsInNanoseconds(e).then((e=>{this._viewEventManager.selectionChanged.raiseEvent({position:new p.JsonTimespan(new p.BigNumber(e.min.h,e.min.l),new p.BigNumber(e.max.h,e.max.l)),isIntermittent:!1})}))},type:f.MenuItemType.command,disabled:()=>this.eventsList.selectedRows().length<2},{type:f.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>o(e.sfp),type:f.MenuItemType.command,disabled:()=>n||!e.sfp},{type:f.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_ShowStacks_All"),callback:()=>this.showStacks(s.id,D.MatchFlags.None),type:f.MenuItemType.command},{label:i.Resources.getString("ContextMenu_ShowStacks_Provider"),callback:()=>this.showStacks(s.id,D.MatchFlags.Provider),type:f.MenuItemType.command},{label:i.Resources.getString("ContextMenu_ShowStacks_Task"),callback:()=>this.showStacks(s.id,D.MatchFlags.Provider|D.MatchFlags.Task),type:f.MenuItemType.command},{label:i.Resources.getString("ContextMenu_ShowStacks_Event"),callback:()=>this.showStacks(s.id,D.MatchFlags.Provider|D.MatchFlags.Task|D.MatchFlags.OpCode),type:f.MenuItemType.command}];return f.create(t)}))}computeOverlay(){return this._eventsListDAO.rowDataLoadStatus()===c.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._eventsListDAO.rowDataLoadStatus()===c.DataLoadEvent.DataLoadCompleted&&0===this._eventsList.rows().length?{name:"MessageView",data:i.Resources.getString("NoDataMessage")}:this._eventsListDAO.rowDataLoadStatus()===c.DataLoadEvent.DataLoadCanceled&&this._eventsListDAO.totalFilterCount()>o.FilterLimit()?{name:"MessageView",data:i.Resources.getString("FilterLimitMessage",this._eventsListDAO.totalFilterCount().toLocaleString(i.Culture.formatRegion))}:null}showStacks(e,t){E.showAnyStacks({rowId:e,matches:t}),this._viewEventManager.selectDetailsView(o.AnyStacksViewId())}}let L;t.EventsListViewModel=y;const E=new _.EventsViewerMarshaler;E.getDoubleClickTimeMs().then((e=>{a.Init(e),L=new y})),t.getEventsListViewModel=function(){return L}}.apply(t,i),void 0===o||(e.exports=o)},337:(e,t,s)=>{var i,o;i=[s,t,s(766)],o=function(e,t,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EventsListColumnSettingsProvider=void 0,t.EventsListColumnSettingsProvider=class{constructor(){this._view="Collections",this._marshaler=new s.EventsViewerMarshaler}getColumnSettings(){return this._marshaler.getColumnSettings(this._view)}onColumnChanged(e){this._onColumnChangedPromise=this._marshaler.onColumnChanged(this._view,e)}}}.apply(t,i),void 0===o||(e.exports=o)},152:(e,t,s)=>{var i,o;i=[s,t,s(28),s(226),s(952),s(117),s(117),s(881),s(881),s(471),s(268),s(117)],o=function(e,t,s,i,o,n,r,a,l,d,c,u){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EventsListDAO=void 0;class h{constructor(e,t,i){this._rowDataLoadStatus=s.observable(a.DataLoadEvent.DataLoadStart),this._filterDomain=s.observableArray([]),this._count=s.observable(),this._rows=s.observableArray([]),this._sortInfo={columnId:this.defaultSortColumnId,direction:a.SortDirection.Desc},this._totalFilterCount=s.observable(),this._loadingProperties=s.observable(!1),this._details=s.observable(),this._commonPropertiesLabels=["TaskId","TaskName","OpCode","OpCodeName","Level","LevelName","Version","Keywords","Channel","ProcessorNumber","PointerSize","ActivityId","RelatedActivityId","IsClassicProvider","EventDataLength"],this._dataWarehouse=e,this._logger=n.getLogger("EventsListDAO"),this._marshaler=i,this._rows.subscribe((()=>{this._details(null)})),this._filterOptions=new d.EventsListFilterDAO(e),this._timeFilter=s.observable(t),this._timeFilter.subscribe((e=>{this._logger.debug("Time domain updated, loading new data");const t={timeDomain:e,customDomain:{view:"EventsList"}};this._getFilteredDataPromise=this._dataWarehouse.getFilteredData(t,o.EventsViewerAnalyzerId()).then((e=>(this._currentResult&&this._currentResult.dispose(),this._currentResult=e,this.loadDataFromResult(0,o.EventCountLimit(),this._filterDomain(),this._currentResult)))).then((()=>this._filterOptions.loadFilterOptions(e)))})),this._timeFilter.notifySubscribers(t)}get filterOptions(){return this._filterOptions.filterOptions}get jmcService(){return void 0===this._jmcService&&(this._jmcService=this._dataWarehouse.getJmcService()),this._jmcService}get timeFilter(){return this._timeFilter}get totalFilterCount(){return this._totalFilterCount}get count(){return this._count}get rows(){return this._rows}get defaultSortColumnId(){return"adjustedTimestampMSec"}get rowDataLoadStatus(){return this._rowDataLoadStatus}get loadingProperties(){return this._loadingProperties}get details(){return this._details}get marshaler(){return this._marshaler}invokeRow(e){this._additionalDetailsPromise=e.additionalDetails.then((e=>{this._details(e)}))}getCount(e){return Promise.resolve(this._count())}getRows(e,t){return this.sort(this._rows(),t)}search(e,t,s,i,o,n,r){throw new Error("Method not implemented.")}sort(e,t,s){this._sortInfo=t;const i=h.SortFunc[t.columnId](t.direction);return e.sort(i),Promise.resolve(e)}filter(e,t){return this._filterDomain(e),this.loadDataFromResult(0,o.EventCountLimit(),this._filterDomain(),this._currentResult,t).then((()=>{const e=this._rows();return Promise.resolve(e)}))}getTimestampResult(e){let t=Promise.resolve(this._currentTimestampsResult);if(!this._currentTimestampsResult){const s={customDomain:{view:"Timestamps"}};t=this._dataWarehouse.getFilteredData(s,o.EventsViewerAnalyzerId(),e).then((t=>(e?.throwIfCancellationRequested(),this._currentTimestampsResult=t,t)))}return t}getTimestampInNanoseconds(e){return this._logger.debug(`Getting timestamp in nanoseconds for ${e}`),this.getTimestampResult().then((t=>t.getResult({internalIds:[e]})))}getMinMaxTimestampsInNanoseconds(e){return this._logger.debug(`Getting min and max timestamps in nanoseconds for ${e.toString()}`),this.getTimestampResult().then((t=>t.getResult({internalIds:e})))}loadAdditionalDetailsData(e){this._logger.debug(`Getting additional properties for ${e}`),this._loadingProperties(!0);let t=Promise.resolve(this._currentPropertiesResult);if(!this._currentPropertiesResult){const e={customDomain:{view:"AdditionalProperties"}};t=this._dataWarehouse.getFilteredData(e,o.EventsViewerAnalyzerId()).then((e=>(this._currentPropertiesResult=e,e)))}const s=this.marshaler.isNativeCodeEnabled();return Promise.all([t,s]).then((t=>t[0].getResult({internalId:e,showNative:t[1]}))).then((e=>{let t=[],s=[],o=[],n=null;if(e.plp){const s=JSON.parse(e.plp);t=Object.getOwnPropertyNames(s).map((e=>[e,Object.getOwnPropertyDescriptor(s,e).value]))}return e.cmp&&(s=JSON.parse(e.cmp).map(((e,t)=>[this._commonPropertiesLabels[t],e]))),e.cs&&(o=e.cs.map((e=>("[External Code]"===e?e=i.Resources.getString("ExternalCodeLabel"):"[System Call]"===e?e=i.Resources.getString("SystemCallLabel"):"[Native Code]"===e&&(e=i.Resources.getString("NativeCodeLabel")),[e])))),e.sfp&&(n=e.sfp),this._loadingProperties(!1),{plp:t,cmp:s,cs:o,sfp:n}}))}showSourceFile(e){return r.getSourceFileViewerService().openSourcePosition(e)}loadDataFromResult(e,t,s,i,n){if(this._logger.debug("get event data from result"),this._currentRequestCancellationTokenSource&&this._currentRequestCancellationTokenSource.cancel(),void 0===i)return this._logger.debug("undefined result for eventsListDAO"),Promise.resolve(void 0);this._currentRequestCancellationTokenSource=new u.CancellationTokenSource,this._currentRequestCancellationTokenSource.token.onCancellationRequested.addEventListener((()=>{this._rowDataLoadStatus(a.DataLoadEvent.DataLoadCanceled)}),{once:!0}),this._rowDataLoadStatus(a.DataLoadEvent.DataLoadStart);let r=0;return s.forEach((e=>{r+=e.includeItems.length})),this._totalFilterCount(r+2),this._totalFilterCount()>o.FilterLimit()?(this._logger.debug(`Filter count ${this._totalFilterCount()} exceeds SQLite limit of ${o.FilterLimit()}. Cannot make request.`),this._rowDataLoadStatus(a.DataLoadEvent.DataLoadCanceled),Promise.resolve(void 0)):(this._currentRequestPromise=i.getResult({startIndex:e,numberOfEvents:t,orderByColumn:"time",domain:s},n).then((e=>{this._logger.debug(`Result contains ${e.ec} events out of ${e.tec} total events starting at index ${e.si}`),this._count(e.tec),this._rows(e.ev.map((t=>new c.EventsRowViewModel(t,e.pvgs[t.pvg],e.pvns[t.pvn],e.eids[t.eid],e.ens[t.en],e.ts[t.t],e.pids[t.pid],e.pns[t.pn],e.tids[t.tid],this)))),this.sort(this._rows(),this._sortInfo)})).then((()=>{this.rowDataLoadStatus(a.DataLoadEvent.DataLoadCompleted)}),(e=>{e.name!==o.errorNameCanceled()&&this._rowDataLoadStatus(a.DataLoadEvent.DataLoadFailed)})),this._currentRequestPromise)}}t.EventsListDAO=h,h.SortFunc={eventName:e=>l.SortFunctions.stringSort("eventName",e),adjustedTimestampMSec:e=>l.SortFunctions.numericSort("adjustedTimestampMSec",e),providerGuid:e=>l.SortFunctions.stringSort("providerGuid",e),eventId:e=>l.SortFunctions.numericSort("eventId",e),unixTimeInMilliseconds:e=>l.SortFunctions.numericSort("unixTimeInMilliseconds",e),processId:e=>l.SortFunctions.numericSort("processId",e),processName:e=>l.SortFunctions.natSort("processName",e),threadId:e=>l.SortFunctions.numericSort("threadId",e)}}.apply(t,i),void 0===o||(e.exports=o)},471:(e,t,s)=>{var i,o;i=[s,t,s(28),s(117),s(952)],o=function(e,t,s,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EventsListFilterDAO=void 0,t.EventsListFilterDAO=class{constructor(e){this._filterOptions=s.observableArray([]),this._dataWarehouse=e}get filterOptions(){return this._filterOptions}loadFilterOptions(e){const t={timeDomain:new i.JsonTimespan(i.BigNumber.zero,i.BigNumber.zero),customDomain:{view:"ColumnFilters"}};return this._dataWarehouse.getFilteredData(t,o.EventsViewerAnalyzerId()).then((e=>(this._currentResult&&this._currentResult.dispose(),this._currentResult=e,this._currentResult.getResult({})))).then((e=>(this._filterOptions(e),this._filterOptions())))}}}.apply(t,i),void 0===o||(e.exports=o)},268:(e,t,s)=>{var i,o;i=[s,t,s(28),s(226),s(117),s(632)],o=function(e,t,s,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.EventsRowViewModel=void 0,t.EventsRowViewModel=class{constructor(e,t,i,n,r,a,l,d,c,u){this._selected=s.observable(!1),this._logger=o.getLogger("EventsRowViewModel"),this._dto=e,this._dao=u,this._providerGuid=t,this._eventId=n,this._eventName=`${i}/${r}`,this._unixTimeInMilliseconds=a,this._processId=l,this._processName=d,this._threadId=c}get adjustedTimestampMSec(){return this._dto.atms}get formattedMessage(){return this._dto.fm?this._dto.fm:i.Resources.getString("UnknownDataLabel")}get providerGuid(){return this._providerGuid?this._providerGuid:i.Resources.getString("UnknownDataLabel")}get eventName(){return this._eventName?this._eventName:i.Resources.getString("UnknownDataLabel")}get eventId(){return this._eventId}get unixTimeInMilliseconds(){if(void 0===this._unixTimeInMilliseconds_DateString){const e=new Date(this._unixTimeInMilliseconds);this._unixTimeInMilliseconds_DateString=e.toLocaleString(i.Culture.formatRegion,{timeZone:"UTC",hour12:!1,year:"numeric",day:"numeric",month:"numeric",hour:"numeric",minute:"numeric",second:"numeric",fractionalSecondDigits:3})}return this._unixTimeInMilliseconds_DateString}get processId(){return this._processId}get processName(){return this._processName}get threadId(){return this._threadId}get additionalDetails(){const e=this._dao.marshaler.isNativeCodeEnabled(),t=this._dao.jmcService.getJmcEnabledState();return Promise.all([t,e]).then((e=>{const[t,s]=e;return void 0!==this._additionalDetailsPromise&&this._jmcState===t&&this._showNative===s||(this._jmcState=t,this._showNative=s,this._additionalDetailsPromise=this._dao.loadAdditionalDetailsData(this.id)),this._additionalDetailsPromise}))}get templateName(){return"EventsRowView"}get id(){return this._dto.idx}get selected(){return this._selected}invoke(){this._logger.debug(`EventsRowViewModel: Invoke on row: ${this.id}`),this._dao.invokeRow(this)}}}.apply(t,i),void 0===o||(e.exports=o)},371:function(e,t,s){var i,o,n=this&&this.__createBinding||(Object.create?function(e,t,s,i){void 0===i&&(i=s),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[s]}})}:function(e,t,s,i){void 0===i&&(i=s),e[i]=t[s]}),r=this&&this.__exportStar||function(e,t){for(var s in e)"default"===s||Object.prototype.hasOwnProperty.call(t,s)||n(t,e,s)};i=[s,t,s(334),s(558)],o=function(e,t,s,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),r(s,t),window.EventsViewerUI_onAfterDomInsert=i.onAfterDomInsert}.apply(t,i),void 0===o||(e.exports=o)},886:(e,t,s)=>{var i;i=function(e,t){"use strict";var s;Object.defineProperty(t,"__esModule",{value:!0}),t.MatchFlags=void 0,(s=t.MatchFlags||(t.MatchFlags={}))[s.None=0]="None",s[s.Provider=1]="Provider",s[s.Task=2]="Task",s[s.OpCode=4]="OpCode"}.apply(t,[s,t]),void 0===i||(e.exports=i)},766:(e,t,s)=>{var i,o;i=[s,t,s(226),s(117)],o=function(e,t,s,i){"use strict";let o;Object.defineProperty(t,"__esModule",{value:!0}),t.EventsViewerMarshaler=void 0,t.EventsViewerMarshaler=class{constructor(){o||(o=s.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.EventsViewer.EventsViewerMarshaler",{},!0)),this._onShowAnyStacks=new i.ObservableEvent(o,"onShowAnyStacks"),this._updateNativeCodeEvent=new i.ObservableEvent(o,"updateNativeCodeEvent")}openSymbolSettings(){o._post("openSymbolSettings")}loadModuleSymbols(e){return o._call("loadModuleSymbols",e)}get onShowAnyStacks(){return this._onShowAnyStacks}showAnyStacks(e){return o._call("showAnyStacks",e)}isNativeCodeEnabled(){return o._call("isNativeCodeEnabled")}setNativeCodeEnabled(e){return o._call("setNativeCode",{isEnabled:e})}get onUpdateNativeCode(){return this._updateNativeCodeEvent}getDoubleClickTimeMs(){return o._call("getDoubleClickTimeMs")}onColumnChanged(e,t){return o._call("onColumnChanged",e,t)}getColumnSettings(e){return o._call("getColumnSettings",e)}getLastAnyStacksArgs(){return o._call("getLastAnyStacksArgs")}}}.apply(t,i),void 0===o||(e.exports=o)},758:(e,t,s)=>{var i,o;i=[s,t,s(226)],o=function(e,t,s){"use strict";let i;Object.defineProperty(t,"__esModule",{value:!0}),t.EventsViewerTelemetryMarshaler=void 0,t.EventsViewerTelemetryMarshaler=class{constructor(){i||(i=s.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.EventsViewer.EventsViewerTelemetryMarshaler",{},!0))}additionalPropertiesRequested(){i._post("additionalPropertiesRequested")}displayedEventCount(e){i._post("displayedEventCount",e)}}}.apply(t,i),void 0===o||(e.exports=o)},558:(e,t,s)=>{var i,o;i=[s,t,s(28),s(226),s(560)],o=function(e,t,s,i,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.onAfterDomInsert=t.LocalizeNumber=void 0;const n={};t.LocalizeNumber=function(e,t){const s=JSON.stringify(t||{});let o=n[s];if(!o){const e=new Intl.NumberFormat(i.Culture.formatRegion,t);o=t=>e.format(t),n[s]=o}return o(e)},t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=s.utils.domData.get(e,"mediaQuery");if(t){const i=s.utils.domData.get(e,"mediaQueryListener");t.removeListener(i)}let i=45;const n=e.children;for(let e=0;e<n.length;e++)i+=n.item(e).offsetWidth;const r=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},a=window.matchMedia(o.Utilities.formatString("(max-width: {0}px)",i.toString()));r(a),a.addListener(r),s.utils.domData.set(e,"mediaQuery",a),s.utils.domData.set(e,"mediaQueryListener",r)}}.apply(t,i),void 0===o||(e.exports=o)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=s},28:e=>{"use strict";e.exports=i},226:e=>{"use strict";e.exports=o}},r={},function e(t){var s=r[t];if(void 0!==s)return s.exports;var i=r[t]={exports:{}};return n[t].call(i.exports,i,i.exports,e),i.exports}(371);var n,r}));
// SIG // Begin signature block
// SIG // MIIoUwYJKoZIhvcNAQcCoIIoRDCCKEACAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // SO+FDH3dK0SxVXHqJ7I0ka+LzN22c1RfZl9DAgVZrhig
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAABAO91ZVdDzsYrQAA
// SIG // AAAEAzANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExM1oX
// SIG // DTI1MDkxMTIwMTExM1owdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // n3RnXcCDp20WFMoNNzt4s9fV12T5roRJlv+bshDfvJoM
// SIG // ZfhyRnixgUfGAbrRlS1St/EcXFXD2MhRkF3CnMYIoeMO
// SIG // MuMyYtxr2sC2B5bDRMUMM/r9I4GP2nowUthCWKFIS1RP
// SIG // lM0YoVfKKMaH7bJii29sW+waBUulAKN2c+Gn5znaiOxR
// SIG // qIu4OL8f9DCHYpME5+Teek3SL95sH5GQhZq7CqTdM0fB
// SIG // w/FmLLx98SpBu7v8XapoTz6jJpyNozhcP/59mi/Fu4tT
// SIG // 2rI2vD50Vx/0GlR9DNZ2py/iyPU7DG/3p1n1zluuRp3u
// SIG // XKjDfVKH7xDbXcMBJid22a3CPbuC2QJLowIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFOpuKgJKc+OuNYitoqxfHlrE
// SIG // gXAZMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDI5MjYwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQBRaP+hOC1+dSKhbqCr1LIvNEMrRiOQ
// SIG // EkPc7D6QWtM+/IbrYiXesNeeCZHCMf3+6xASuDYQ+AyB
// SIG // TX0YlXSOxGnBLOzgEukBxezbfnhUTTk7YB2/TxMUcuBC
// SIG // P45zMM0CVTaJE8btloB6/3wbFrOhvQHCILx41jTd6kUq
// SIG // 4bIBHah3NG0Q1H/FCCwHRGTjAbyiwq5n/pCTxLz5XYCu
// SIG // 4RTvy/ZJnFXuuwZynowyju90muegCToTOwpHgE6yRcTv
// SIG // Ri16LKCr68Ab8p8QINfFvqWoEwJCXn853rlkpp4k7qzw
// SIG // lBNiZ71uw2pbzjQzrRtNbCFQAfmoTtsHFD2tmZvQIg1Q
// SIG // VkzM/V1KCjHL54ItqKm7Ay4WyvqWK0VIEaTbdMtbMWbF
// SIG // zq2hkRfJTNnFr7RJFeVC/k0DNaab+bpwx5FvCUvkJ3z2
// SIG // wfHWVUckZjEOGmP7cecefrF+rHpif/xW4nJUjMUiPsyD
// SIG // btY2Hq3VMLgovj+qe0pkJgpYQzPukPm7RNhbabFNFvq+
// SIG // kXWBX/z/pyuo9qLZfTb697Vi7vll5s/DBjPtfMpyfpWG
// SIG // 0phVnAI+0mM4gH09LCMJUERZMgu9bbCGVIQR7cT5YhlL
// SIG // t+tpSDtC6XtAzq4PJbKZxFjpB5wk+SRJ1gm87olbfEV9
// SIG // SFdO7iL3jWbjgVi1Qs1iYxBmvh4WhLWr48uouzCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghomMIIaIgIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAAEA73VlV0POxitAAAAAAQDMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCChoYc9jE8VlSUH
// SIG // HuKaQEYXBGs+kJqXIBkRRrK8nO2HJjBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBADA0vwNReUrAcS3hLYG7ChM6BmH05qlD
// SIG // KarVVL7JM/+kBKClwO5G7L1glUqza5usCDhrXX4y4p0u
// SIG // zQ9SHoLuvpTF0eN9uW0KAJONcgDog0TrVck4Ghw2Fhus
// SIG // 9cj7Aa6vD6gJWmj22JAKwBIZM+ayJEKW6byPHFS4o96Q
// SIG // xCx5/Z3VHjhZZ7jS4RfXZel+u8/TlLVPwxaocxLRHvpT
// SIG // 2JANNffVlxkU4PDCw4oaSmY5vSal3mirN48A9j+WvxEI
// SIG // 4UqZSaDKLxGmNFUq6UqWRGTLC3IX+luWU6uu9eMRAjP8
// SIG // MB6kdnZbqW/Nved9RitwUcZeWQOn6cCo3rI4hudP/tl0
// SIG // ZZ2hghewMIIXrAYKKwYBBAGCNwMDATGCF5wwgheYBgkq
// SIG // hkiG9w0BBwKggheJMIIXhQIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBWgYLKoZIhvcNAQkQAQSgggFJBIIBRTCCAUEC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // +15zna+dfrY7Cf+7lMqJLTv1WqNBppxwQMDJlS2aIgcC
// SIG // BmhTAU1zdhgTMjAyNTA2MzAxNDQ0MjcuODA3WjAEgAIB
// SIG // 9KCB2aSB1jCB0zELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsG
// SIG // A1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9u
// SIG // cyBMaW1pdGVkMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBF
// SIG // U046NTkxQS0wNUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jv
// SIG // c29mdCBUaW1lLVN0YW1wIFNlcnZpY2WgghH+MIIHKDCC
// SIG // BRCgAwIBAgITMwAAAfQXRoXAyz855QABAAAB9DANBgkq
// SIG // hkiG9w0BAQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UE
// SIG // CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYw
// SIG // JAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0Eg
// SIG // MjAxMDAeFw0yNDA3MjUxODMwNTlaFw0yNTEwMjIxODMw
// SIG // NTlaMIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
// SIG // EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExp
// SIG // bWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVTTjo1
// SIG // OTFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0
// SIG // IFRpbWUtU3RhbXAgU2VydmljZTCCAiIwDQYJKoZIhvcN
// SIG // AQEBBQADggIPADCCAgoCggIBAKcIThOm0IAvaquIyRl9
// SIG // gNcqDm35NKnrUPJJI/uZt+1gcQ5bGeaCZ438x7Kaj4jh
// SIG // Fc2dstsoBoDWd/8XWUDe3/QNVqdQHYeah12WYd0gV/AA
// SIG // bnOvU293CeSgmXFw7Ln8Jl3go/NRMyRCGarlXVfEk5UL
// SIG // ngf29TCGLeUSorN7sM3ZX0pdHJB2xs6DvdWEyoOiBMai
// SIG // mKIxq3gqKZyCsTr5K+VWbI9n/eQW9SxhL7oQSJvwuycr
// SIG // LybwWVjba7Kc8l1Z7qPpAxMmcKZKYbEfGb3YvrP6UIqH
// SIG // 5nW1tVKs1pal0FYKGF22mJBMmkof4XgbcI9bbnvi3Ljn
// SIG // BwD4G8Gb0C5LCmiuOqJLa3oDkeHtInLBogFkfSC/p8uJ
// SIG // pQlDQPOBexhBFjhL4m4oO8LK02umW87jLMk4tgM+Kj1d
// SIG // 0EZBYMUm6eEeDhCp4p/Cc+FyyNcF4QYSKTBnwNwU/OdJ
// SIG // 6mps0og+S+acflbXwotDCU0tiwxdT2lWcJclWSFY1Ryv
// SIG // KIdh2BvU9uhY0ffyPOYuRMcZoR6cTNmflISXmQOi8+Od
// SIG // pv/sawOMa3WGrOXJuxVIctuKzy1R/hcvmcsBwKfXPaFk
// SIG // 67Y3yCqiyL2LYCXONUPFsW2T0ewdbn7fARbL89nTki5M
// SIG // Twy3F1stegDcu979IqQsQMFBAvYbLItC3QfE4YjX/+AP
// SIG // kWfLAgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQUK3RloQrR
// SIG // LD4ndSyc7E2i0ykG35swHwYDVR0jBBgwFoAUn6cVXQBe
// SIG // Yl2D9OXSZacbUzUZ6XIwXwYDVR0fBFgwVjBUoFKgUIZO
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
// SIG // cmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUy
// SIG // MDIwMTAoMSkuY3JsMGwGCCsGAQUFBwEBBGAwXjBcBggr
// SIG // BgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0
// SIG // YW1wJTIwUENBJTIwMjAxMCgxKS5jcnQwDAYDVR0TAQH/
// SIG // BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAOBgNV
// SIG // HQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBAN3B
// SIG // 0g8SSlA7IGnCH0V+tLoDg0obAasLRFEVG1F3g5mGEmua
// SIG // BY9+Ebo1t4DngrfzmwzuOb36Z2BuTkuWKMMLBcNfYIgi
// SIG // OiVfnHBv6qjNPJ8QEm88FraraK80IiYfbqbBOE1WXimF
// SIG // 5m8se1jfbXW1SKwnpVY+z+onzB00i7egZsqEtsZQtnH4
// SIG // CjzwNd70t3rqlJes8HuxgIY34zV4ypROEjVib3aoK79B
// SIG // lESo6pmpjb4ZkiWp3uk2M6XQwnoKvGnZRh/OSNRFipnx
// SIG // EW9ZcysuTjDtnvSJAJb8naVLp9At7DRLadHoZYk9Eq2q
// SIG // vI3GFQx+ANgvzGywSMIpI8IhRkOEpRS09k4G+Br76XFl
// SIG // cwccA6PSEQcKc54G8s24YfeVFTq0C9q21h6xw0hN3YHS
// SIG // 9srmh0YGOx2GC7OS7bN9MFPTrofDeeEVLWuhhWRceQOL
// SIG // iE4MiXFXVlWjdKo7NHhI8BMjVL9HES7h1iQXo5DHt6kQ
// SIG // Ibwo54a6OwxkVmiJXcn82apZ+hbJy0N25fmb1SVk2Cbi
// SIG // /iGSyNkotyKyEX43HJ9vV9gV/789inGLmyIyul32L62U
// SIG // DeFym570qgTQMCD2NsSXgeKPTwxBSNq3D2i1Ms+SFeyT
// SIG // 9yUaYIN8bFKrxR5UhurjCFo8B9BkCCMKwts0cvpTWbDi
// SIG // p67sshzEEz+48uVPdqhBMIIHcTCCBVmgAwIBAgITMwAA
// SIG // ABXF52ueAptJmQAAAAAAFTANBgkqhkiG9w0BAQsFADCB
// SIG // iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWlj
// SIG // cm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
// SIG // IDIwMTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgz
// SIG // MjI1WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
// SIG // Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCC
// SIG // AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOTh
// SIG // pkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjKNVf2
// SIG // AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZnhUYj
// SIG // DLWNE893MsAQGOhgfWpSg0S3po5GawcU88V29YZQ3MFE
// SIG // yHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJprx2rrPY2
// SIG // vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxqD89d9P6O
// SIG // U8/W7IVWTe/dvI2k45GPsjksUZzpcGkNyjYtcI4xyDUo
// SIG // veO0hyTD4MmPfrVUj9z6BVWYbWg7mka97aSueik3rMvr
// SIG // g0XnRm7KMtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdb
// SIG // Z2De+JKRHh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZ
// SIG // nkXftnIv231fgLrbqn427DZM9ituqBJR6L8FA6PRc6ZN
// SIG // N3SUHDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEz
// SIG // OUyOArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMY
// SIG // ctenIPDC+hIK12NvDMk2ZItboKaDIV1fMHSRlJTYuVD5
// SIG // C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6
// SIG // bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17a
// SIG // j54WcmnGrnu3tz5q4i6tAgMBAAGjggHdMIIB2TASBgkr
// SIG // BgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQWBBQq
// SIG // p1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cV
// SIG // XQBeYl2D9OXSZacbUzUZ6XIwXAYDVR0gBFUwUzBRBgwr
// SIG // BgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYzaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1Jl
// SIG // cG9zaXRvcnkuaHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMI
// SIG // MBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1Ud
// SIG // DwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQY
// SIG // MBaAFNX2VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRP
// SIG // ME0wS6BJoEeGRWh0dHA6Ly9jcmwubWljcm9zb2Z0LmNv
// SIG // bS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8y
// SIG // MDEwLTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYI
// SIG // KwYBBQUHMAKGPmh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYt
// SIG // MjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3h
// SIG // LB9nATEkW+Geckv8qW/qXBS2Pk5HZHixBpOXPTEztTnX
// SIG // wnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6U03d
// SIG // mLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74py27Y
// SIG // P0h1AdkY3m2CDPVtI1TkeFN1JFe53Z/zjj3G82jfZfak
// SIG // Vqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis9/kpicO8
// SIG // F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4s
// SIG // a3tuPywJeBTpkbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6
// SIG // MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0sHrYUP4KWN1A
// SIG // PMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lU
// SIG // ZNlz138eW0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtq
// SIG // RRFHqfG3rsjoiV5PndLQTHa1V1QJsWkBRH58oWFsc/4K
// SIG // u+xBZj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLB
// SIG // gqJ7Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr
// SIG // 4A245oyZ1uEi6vAnQj0llOZ0dFtq0Z4+7X6gMTN9vMvp
// SIG // e784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQ
// SIG // tB1VM1izoXBm8qGCA1kwggJBAgEBMIIBAaGB2aSB1jCB
// SIG // 0zELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWlj
// SIG // cm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVk
// SIG // MScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046NTkxQS0w
// SIG // NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVAL/i
// SIG // 2f1YNLNe13pOIhvUfXP+/gCOoIGDMIGApH4wfDELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0
// SIG // IFRpbWUtU3RhbXAgUENBIDIwMTAwDQYJKoZIhvcNAQEL
// SIG // BQACBQDsDKhAMCIYDzIwMjUwNjMwMDYwODAwWhgPMjAy
// SIG // NTA3MDEwNjA4MDBaMHcwPQYKKwYBBAGEWQoEATEvMC0w
// SIG // CgIFAOwMqEACAQAwCgIBAAICAuECAf8wBwIBAAICEs0w
// SIG // CgIFAOwN+cACAQAwNgYKKwYBBAGEWQoEAjEoMCYwDAYK
// SIG // KwYBBAGEWQoDAqAKMAgCAQACAwehIKEKMAgCAQACAwGG
// SIG // oDANBgkqhkiG9w0BAQsFAAOCAQEAj7dRDXeMRnVMPx58
// SIG // K5OGE8OV6wG0eM5eTGITZ5RC/F38br9l+01H3itcRvkO
// SIG // u77Tsnutoj7Yr4aLk41ru2Ytlo8bOTeHqEbUDI+t/Dha
// SIG // uK/vx3RqZS/Mbt33THMmjJtEdPTSZfMEKR5FaHp/R3M+
// SIG // hpzmsEWDC2l/6oMEP5WQVFE8fKWebQc+q2fO+AwzyRBH
// SIG // VnKJHBPdE0R4TU9sebKT/iFimdSbh4DT6bwNel1Xg9hk
// SIG // /7xbbFET31bAUKYoGXeyn/HQtuto/CMvoY0uYuNnW63e
// SIG // X/tYOkFGRStJV3iML5tuuVcx2aDXhmFzUxMCpWLEPSOm
// SIG // tsgCSDuLIfZrnxqaRTGCBA0wggQJAgEBMIGTMHwxCzAJ
// SIG // BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
// SIG // DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
// SIG // dCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB9BdGhcDL
// SIG // PznlAAEAAAH0MA0GCWCGSAFlAwQCAQUAoIIBSjAaBgkq
// SIG // hkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwLwYJKoZIhvcN
// SIG // AQkEMSIEIH2OBCN687JiZzjPIlIdCS+tLFoLIWKGEICX
// SIG // +zJxXmLyMIH6BgsqhkiG9w0BCRACLzGB6jCB5zCB5DCB
// SIG // vQQgP1jCfG4mk+p475JJwfEO4UkCIvMrOryAb2YOtEQY
// SIG // 1mswgZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UE
// SIG // CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYw
// SIG // JAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0Eg
// SIG // MjAxMAITMwAAAfQXRoXAyz855QABAAAB9DAiBCAblmIE
// SIG // okPmE7XdMOLrRRg9dzWE2cUGVTCtjJFTbsO9HzANBgkq
// SIG // hkiG9w0BAQsFAASCAgBx1KKDJbwwGRNXVLVBQHf1mWMl
// SIG // 4y9dUzhVvugWlDR4GvqCXXoS2wlgmh48HXzYrAuUeHnU
// SIG // I8AXTyCrSjFpAqYzvq89tYHEdpDa0O42zNejgWvt3Axj
// SIG // zH8w8ERyI9pXfJIYBTRTGct38AYZlK7Ly+hZKARgOes9
// SIG // TKt1nHQ7unhZY9S8pqdqjA8YMSrVj/MV5uvVQ9GIETZ6
// SIG // 38aM83tdOhPof6K89FROSqoacvTYk/bfjJW8oiuVkDLj
// SIG // /BDn8UUrAMBekVHZhQgQoi7jaYd5NvgdI+AKD044FyZE
// SIG // 3Yu36x6PyGK2TBDMYopd91E7EEwtH+KnTZkzrOvG+IKZ
// SIG // apqGKbxrpS/d8dOr7JisR/kvLY/msSD9PmIz5sszUESx
// SIG // tn3SV2UQEOTMwTRV+YfchLBQvMlN8GhxERgFEzsO/sSB
// SIG // qzUET4RnwrDUFtu0CxaYtwIPDgKXC6XXcCjTGAeU8viN
// SIG // UWnFrO4q20O8AWRjw8fk1O4qepv8rRZnGudjjrpvk0OF
// SIG // 70T97hPr6/sDDwmWNqrg5sY0uP0EdHuYGn7uvwGNz8Bq
// SIG // kBIrMmJKolVmD/DrRdGF0NKgIojZY67NGAoM+RO0wIGe
// SIG // 7CSpkrLku/drVCTLD4wzG67l2OoynmCq+OyrzpfHxQi+
// SIG // FXfsZjbBTLK+odJO1hVysyDLUqjGbps5mrBYGVDReQ==
// SIG // End signature block
