define("dotNetAsyncUI",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,i,s,r)=>{return a={946:e=>{const t=document.createElement("script");t.id="ActivityRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGFyaWFFeHBhbmRlZDogeyBleHBhbmRhYmxlOiBleHBhbmRhYmxlLCBleHBhbmRlZDogZXhwYW5kZWQgfSwNCiAgICBjc3M6IHsgc2VsZWN0ZWQ6IHNlbGVjdGVkKCkgfSwNCiAgICBhdHRyOiB7ICdhcmlhLWxldmVsJzogZGVwdGggKyAxIH0iPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9Im5hbWUgY29udGFpbmVyIiBkYXRhLWNvbHVtbmlkPSJuYW1lIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJyb3dJbmRlbnQ6IGRlcHRoIj4mbmJzcDs8L3NwYW4+DQogICAgICAgIDxkaXYgZGF0YS1iaW5kPSJ0cmVlR3JpZEV4cGFuZGVyOiBleHBhbmRlZCwgc3R5bGU6IHsgdmlzaWJpbGl0eTogZXhwYW5kYWJsZSA/ICd2aXNpYmxlJyA6ICdoaWRkZW4nIH0iPjwvZGl2Pg0KICAgICAgICA8ZGl2IGNsYXNzPSJ0eXBlSWNvbiIgZGF0YS1iaW5kPSJjc3M6IHsgaW5jcmVhc2U6IGlzQWJvdmVWYXJpYW5jZSwgZGVjcmVhc2U6IGlzQmVsb3dWYXJpYW5jZSB9LCB0b29sdGlwOiB2YXJpYW5jZVRvb2x0aXAiPjwvZGl2Pg0KICAgICAgICA8c3BhbiBjbGFzcz0idHJlZUdyaWRDZWxsLWxhYmVsIiBkYXRhLWJpbmQ9InRleHQ6IGxhYmVsIj48L3NwYW4+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iY291bnQiIGRhdGEtYmluZD0idGV4dDogY291bnQiIGRhdGEtY29sdW1uaWQ9ImNvdW50Ij48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InN0YXJ0VGltZSIgZGF0YS1iaW5kPSJsb2NhbGl6ZWROdW1iZXI6IHt2YWx1ZTogc3RhcnRUaW1lLCBvcHRpb25zOiB7bWluaW11bUZyYWN0aW9uRGlnaXRzOiAyLCBtYXhpbXVtRnJhY3Rpb25EaWdpdHM6IDJ9fSIgZGF0YS1jb2x1bW5pZD0ic3RhcnRUaW1lIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InN0b3BUaW1lIiBkYXRhLWNvbHVtbmlkPSJzdG9wVGltZSI+DQogICAgICAgIDxzcGFuIGNsYXNzPSJ0cmVlR3JpZENlbGwtbGFiZWwiIGRhdGEtYmluZD0idGV4dDogYXN5bmNTdGF0ZUxhYmVsIj48L3NwYW4+DQogICAgICAgIDwhLS0ga28gaWY6IGlzQXN5bmNDb21wbGV0ZSAtLT4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJsb2NhbGl6ZWROdW1iZXI6IHt2YWx1ZTogc3RvcFRpbWUsIG9wdGlvbnM6IHttaW5pbXVtRnJhY3Rpb25EaWdpdHM6IDIsIG1heGltdW1GcmFjdGlvbkRpZ2l0czogMn19Ij48L3NwYW4+DQogICAgICAgIDwhLS0gL2tvIC0tPg0KICAgICAgICA8IS0tIGtvIGlmbm90OiBpc0FzeW5jQ29tcGxldGUgLS0+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogJycsIHN0eWxlOiB7IGRpc3BsYXk6ICdub25lJyB9Ij48L3NwYW4+DQogICAgICAgIDwhLS0gL2tvIC0tPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0idG90YWxUaW1lIiBkYXRhLWNvbHVtbmlkPSJ0b3RhbFRpbWUiPg0KICAgICAgICA8c3BhbiBjbGFzcz0idHJlZUdyaWRDZWxsLWxhYmVsIiBkYXRhLWJpbmQ9InRleHQ6IGFzeW5jU3RhdGVMYWJlbCI+PC9zcGFuPg0KICAgICAgICA8IS0tIGtvIGlmOiBpc0FzeW5jQ29tcGxldGUgLS0+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0ibG9jYWxpemVkTnVtYmVyOiB7dmFsdWU6IHRvdGFsVGltZSwgb3B0aW9uczoge21pbmltdW1GcmFjdGlvbkRpZ2l0czogMiwgbWF4aW11bUZyYWN0aW9uRGlnaXRzOiAyfX0iPjwvc3Bhbj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiBpc0FnZ3JlZ2F0ZWQgfHwgaXNWYXJpYW5jZSB8fCBpc0RldGFpbHMgPyBhZ2dyZWdhdGVkVGltZUxhYmVsIDogJycsIHN0eWxlOiB7IGRpc3BsYXk6IGlzQWdncmVnYXRlZCB8fCBpc1ZhcmlhbmNlIHx8IGlzRGV0YWlscyA/ICdpbmxpbmUnIDogJ25vbmUnIH0iPjwvc3Bhbj4NCiAgICAgICAgPCEtLSAva28gLS0+DQogICAgICAgIDwhLS0ga28gaWZub3Q6IGlzQXN5bmNDb21wbGV0ZSAtLT4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJ0ZXh0OiAnJywgc3R5bGU6IHsgZGlzcGxheTogJ25vbmUnIH0iPjwvc3Bhbj4NCiAgICAgICAgPCEtLSAva28gLS0+DQogICAgPC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},486:(e,t,i)=>{var s,r;s=[i,t,i(226),i(28),i(886),i(946)],r=function(e,t,i,s,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ActivityRowViewModel=void 0;class a{constructor(e,t,i,r){this._selected=s.observable(!1),this._expanded=s.observable(!1),this._isChildDataLoaded=!1,this._isWithinAggregation=!1,this._dao=e,this._dto=t,this._depth=i,this._isWithinAggregation=r,this._name=s.pureComputed((()=>this.computeName()),this),this._label=s.pureComputed((()=>this.computeLabel()),this),this._asyncStateLabel=s.pureComputed((()=>this.computeAsyncStateLabel()),this),this._varianceTooltip=s.pureComputed((()=>this.computeVarianceTooltip()),this),this._children=s.observableArray([])}get templateName(){return"ActivityRowView"}get id(){return this._dto.id}get depth(){return this._depth}get label(){return this._label}get name(){return this._name}get totalTime(){return this._dto.tt}get startTime(){return this._dto.s}get stopTime(){return this._dto.st}get count(){return this._dto.co}get asyncStateLabel(){return this._asyncStateLabel}get isAggregated(){return this.hasFlag(r.ActivityOptions.Aggregation)}get isVariance(){return this.hasFlag(r.ActivityOptions.Variance)}get isDetails(){return this.hasFlag(r.ActivityOptions.Details)}get isIncomplete(){return this.hasFlag(r.ActivityOptions.Incomplete)}get isBelowVariance(){return this._isWithinAggregation&&this.hasFlag(r.ActivityOptions.BelowVariance)}get isAboveVariance(){return this._isWithinAggregation&&this.hasFlag(r.ActivityOptions.AboveVariance)}get varianceTooltip(){return this._varianceTooltip}get aggregatedTimeLabel(){return i.Resources.getString("AggregatedTimeLabel")}get isAsyncComplete(){return this._dto.st>0&&this._dto.tt>=0}get hasSourceInfo(){return(this._dto.f&r.ActivityOptions.HasSourceInfo)===r.ActivityOptions.HasSourceInfo}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return this._dto.c}get children(){return this._children}invoke(){this._dao.showSourceFile(this.id)}expand(e,t,i){let s=Promise.resolve();return this._isChildDataLoaded||(this._isChildDataLoaded=!0,s=e.getResult({task:"expand",id:this._dto.id,path:this.getIdPath()},i).then((async s=>{i?.throwIfCancellationRequested();const r=s.map((e=>new a(this._dao,e,this.depth+1,this.isAggregated&&!this.isVariance)));return await this._dao.sort(r,t,i),this.children(r),1===r.length&&!r[0].isDetails||2===r.length&&r[1].isDetails?r[0].expand(e,t,i):Promise.resolve()}))),this._expanded(!this._expanded()),s}getIdPath(){return[this.id]}computeName(){return this.hasFlag(r.ActivityOptions.Variance)?i.Resources.getString("VarianceContainerRowName",this._dto.co):this.hasFlag(r.ActivityOptions.Incomplete)?i.Resources.getString("IncompleteContainerRowName",this._dto.co):this.hasFlag(r.ActivityOptions.Details)?"":this._dto.n}computeLabel(){return this.hasFlag(r.ActivityOptions.CallerName)?i.Resources.getString("TaskCallerActivityLabel"):this.hasFlag(r.ActivityOptions.IdentifiedTask)?i.Resources.getString("TaskActivityLabel"):this.hasFlag(r.ActivityOptions.Details)&&!this.hasFlag(r.ActivityOptions.Variance)?i.Resources.getString("TaskDetailsLabel"):""}computeAsyncStateLabel(){return this.isAsyncComplete?"":i.Resources.getString("TaskPendingLabel")}computeVarianceTooltip(){return this.isBelowVariance?i.Resources.getString("BelowVarianceTooltip"):this.isAboveVariance?i.Resources.getString("AboveVarianceTooltip"):""}hasFlag(e){return(this._dto.f&e)===e}}t.ActivityRowViewModel=a}.apply(t,s),void 0===r||(e.exports=r)},778:(e,t,i)=>{var s;s=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ActivityTreeColumnSettingsProvider=void 0,t.ActivityTreeColumnSettingsProvider=class{getColumnSettings(){return Promise.resolve([{columnId:"name",isHidden:!1,width:500},{columnId:"count",isHidden:!1,width:70},{columnId:"startTime",isHidden:!1,width:140},{columnId:"stopTime",isHidden:!1,width:140},{columnId:"totalTime",isHidden:!1,width:140}])}onColumnChanged(e){}}}.apply(t,[i,t]),void 0===s||(e.exports=s)},670:(e,t,i)=>{var s,r;s=[i,t,i(28),i(952),i(881),i(117),i(117),i(486)],r=function(e,t,i,s,r,a,o,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.ActivityTreeDAO=void 0;class c{constructor(e,t,s){this._dataWarehouse=e,this._timeFilter=i.observable(t),this._marshaller=s}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"startTime"}async getRoots(e,t,i){const r={timeDomain:this.timeFilter(),customDomain:{view:"ActivityTree"}},a=await this._dataWarehouse.getFilteredData(r,s.DotNetAsyncAnalyzer(),i);i?.throwIfCancellationRequested(),this._currentResult&&await this._currentResult.dispose(),this._currentResult=a;const o=await this._currentResult.getResult({task:"expand",id:0,path:[]},i);i?.throwIfCancellationRequested();const c=o.map((e=>new n.ActivityRowViewModel(this,e,0,!1)));return await this.sort(c,t,i),c}sort(e,t,i){const s=c.SortFunc[t.columnId];if(s){const i=(e,i)=>{if(0!==e.depth){if(e.isAggregated&&!i.isAggregated)return-1;if(!e.isAggregated&&i.isAggregated)return 1;if(e.isDetails&&!i.isDetails)return 1;if(!e.isDetails&&i.isDetails)return-1;if(e.isVariance&&!i.isVariance)return 1;if(!e.isVariance&&i.isVariance)return-1}return s(t.direction)(e,i)},r=e=>{e.children&&(e.children.sort(i),e.children().forEach(r))};return e.sort(i),e.forEach(r),Promise.resolve(e)}return a.Assert.fail(`Unknown sort column: ${t.columnId}`),Promise.resolve(e)}search(e,t,i,s,r,a,o){throw new Error("Not implemented")}expand(e,t,i){return e.expand(this._currentResult,t,i)}getSourceInfo(e){return this._currentResult.getResult({task:"sourceInfo",id:e,path:[]}).then((e=>e.sfp))}async showSourceFile(e){const t=await this.getSourceInfo(e);await o.getSourceFileViewerService().openSourcePosition(t)}}t.ActivityTreeDAO=c,c.SortFunc={name:e=>r.SortFunctions.stringSort("name",e),count:e=>r.SortFunctions.numericSort("count",e),startTime:e=>r.SortFunctions.numericSort("startTime",e),stopTime:e=>r.SortFunctions.numericSort("stopTime",e),totalTime:e=>r.SortFunctions.numericSort("totalTime",e)}}.apply(t,s),void 0===r||(e.exports=r)},952:(e,t,i)=>{var s;s=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetAsyncAnalyzer=t.ActivityDetailsViewId=void 0,t.ActivityDetailsViewId=function(){return"67cabac5-0ec5-486f-9dd0-6f524c7390fb"},t.DotNetAsyncAnalyzer=function(){return"62070e76-dd33-417e-9665-a4ca5e510ee7"}}.apply(t,[i,t]),void 0===s||(e.exports=s)},940:(e,t,i)=>{var s,r;s=[i,t,i(28),i(226),i(952),i(560),i(881),i(881),i(881),i(881),i(881),i(117),i(117),i(778),i(670),i(766),i(680),i(833),i(103)],r=function(e,t,i,s,r,a,o,n,c,l,d,g,u,h,I,m){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getActivityTreeViewModel=t.DotNetAsyncViewModel=void 0;class p{constructor(){let e;this._currentOverlay=i.pureComputed((()=>this.computeOverlay())),this._isOverlayActive=i.pureComputed((()=>null!==this._currentOverlay())),g.loadDataWarehouse().then((t=>(e=t,e.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((t=>{this._activityTreeDao=new I.ActivityTreeDAO(e,t,b);const a=new o.TreeGridHeaderViewModel([{id:"name",text:s.Resources.getString("ActivityTreeHeaderName"),hideable:!1,sortable:l.SortDirection.Desc},{id:"count",text:s.Resources.getString("ActivityTreeHeaderCount"),hideable:!0,sortable:l.SortDirection.Desc},{id:"startTime",text:s.Resources.getString("ActivityTreeHeaderStartTime"),hideable:!0,sortable:l.SortDirection.Asc},{id:"stopTime",text:s.Resources.getString("ActivityTreeHeaderStopTime"),hideable:!0,sortable:l.SortDirection.Desc},{id:"totalTime",text:s.Resources.getString("ActivityTreeHeaderTotalTime"),hideable:!0,sortable:l.SortDirection.Desc}],new h.ActivityTreeColumnSettingsProvider,this._activityTreeDao.defaultSortColumnId);this._activityTree=new c.TreeGridViewModel(this._activityTreeDao,a,"ActivityTreeAriaLabel"),this._activityTree.onResultChanged(0);const n=u.getViewEventManager();n.selectionChanged.addEventListener((e=>{e.isIntermittent||this._activityTreeDao.timeFilter().equals(e.position)||(this._activityTreeDao.timeFilter(e.position),this._activityTree.onResultChanged(0))})),i.applyBindings(this),n.detailsViewReady.raiseEvent({Id:r.ActivityDetailsViewId()})}))}get activityTree(){return this._activityTree}get currentOverlay(){return this._currentOverlay}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==a.KeyCodes.C)return!0;const i=n.TreeGridUtils.formatTreeGridSelectedToText(this._activityTree);return navigator.clipboard.writeText(i),!1}contextMenu(e,t){const i=e;if("number"!=typeof i.id)return null;const r=()=>{this._activityTreeDao.showSourceFile(i.id)},a=[{label:s.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>r(),disabled:()=>!i.id||!i.hasSourceInfo,type:s.ContextMenu.MenuItemType.command},{type:s.ContextMenu.MenuItemType.separator},{label:s.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=n.TreeGridUtils.formatTreeGridSelectedToText(this._activityTree);navigator.clipboard.writeText(e)},type:s.ContextMenu.MenuItemType.command},{label:s.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=n.TreeGridUtils.formatTreeGridSelectedToMarkdown(this._activityTree);navigator.clipboard.writeText(e)},type:s.ContextMenu.MenuItemType.command}];return s.ContextMenu.create(a)}computeOverlay(){return this._activityTree.dataLoadStatus()===l.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._activityTree.dataLoadStatus()===l.DataLoadEvent.DataLoadCompleted&&0===this._activityTree.treeAsArray().length?{name:"MessageView",data:s.Resources.getString("NoDataMessage")}:null}}let v;t.DotNetAsyncViewModel=p;const b=new m.DotNetAsyncMarshaler;b.getDoubleClickTimeMs().then((e=>{d.Init(e),v=new p})),t.getActivityTreeViewModel=function(){return v}}.apply(t,s),void 0===r||(e.exports=r)},371:function(e,t,i){var s,r,a=this&&this.__createBinding||(Object.create?function(e,t,i,s){void 0===s&&(s=i),Object.defineProperty(e,s,{enumerable:!0,get:function(){return t[i]}})}:function(e,t,i,s){void 0===s&&(s=i),e[s]=t[i]}),o=this&&this.__exportStar||function(e,t){for(var i in e)"default"===i||Object.prototype.hasOwnProperty.call(t,i)||a(t,e,i)};s=[i,t,i(940),i(558)],r=function(e,t,i,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),o(i,t),window.DotNetAsyncUI_onAfterDomInsert=s.onAfterDomInsert}.apply(t,s),void 0===r||(e.exports=r)},886:(e,t,i)=>{var s;s=function(e,t){"use strict";var i;Object.defineProperty(t,"__esModule",{value:!0}),t.ActivityOptions=void 0,(i=t.ActivityOptions||(t.ActivityOptions={}))[i.None=0]="None",i[i.FullNameFound=1]="FullNameFound",i[i.ExactStopTime=2]="ExactStopTime",i[i.IdentifiedTask=4]="IdentifiedTask",i[i.CallerName=8]="CallerName",i[i.HasSourceInfo=16]="HasSourceInfo",i[i.HasProcessedAggregation=32]="HasProcessedAggregation",i[i.Aggregation=64]="Aggregation",i[i.Variance=128]="Variance",i[i.BelowVariance=256]="BelowVariance",i[i.AboveVariance=512]="AboveVariance",i[i.Details=1024]="Details",i[i.Incomplete=2048]="Incomplete"}.apply(t,[i,t]),void 0===s||(e.exports=s)},766:(e,t,i)=>{var s,r;s=[i,t,i(226)],r=function(e,t,i){"use strict";let s;Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetAsyncMarshaler=void 0,t.DotNetAsyncMarshaler=class{constructor(){s||(s=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetAsync.DotNetAsyncMarshaler",{},!0))}getDoubleClickTimeMs(){return s._call("getDoubleClickTimeMs")}}}.apply(t,s),void 0===r||(e.exports=r)},558:(e,t,i)=>{var s,r;s=[i,t,i(28),i(560)],r=function(e,t,i,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.areTimespansEqual=t.onAfterDomInsert=void 0,t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=i.utils.domData.get(e,"mediaQuery");if(t){const s=i.utils.domData.get(e,"mediaQueryListener");t.removeListener(s)}const r=e.children;let a=45;for(let e=0;e<r.length;e++)a+=r.item(e).offsetWidth;const o=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},n=window.matchMedia(s.Utilities.formatString("(max-width: {0}px)",a.toString()));o(n),n.addListener(o),i.utils.domData.set(e,"mediaQuery",n),i.utils.domData.set(e,"mediaQueryListener",o)},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)}}.apply(t,s),void 0===r||(e.exports=r)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=i},28:e=>{"use strict";e.exports=s},226:e=>{"use strict";e.exports=r}},o={},function e(t){var i=o[t];if(void 0!==i)return i.exports;var s=o[t]={exports:{}};return a[t].call(s.exports,s,s.exports,e),s.exports}(371);var a,o}));
// SIG // Begin signature block
// SIG // MIIoRAYJKoZIhvcNAQcCoIIoNTCCKDECAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // /638FTtLYDycm6/XVXfJ1zVFwEx56kqmoMEcXUV+F6Og
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghomMIIaIgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCA+zoN4S1fO9Rzi/ysrwZoms9BtvQ40x8kZ
// SIG // pjXgeKBljzBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBACCjWII/
// SIG // 4JgzWI1VOhXxJYlfo+eCRIduiKGEJBpkB8tAB9Hyvve1
// SIG // zj/0jfTE+X078HKJPizGQ1HOKe9Bx6quUcY62Kt3xe0I
// SIG // xxa5dsoBA5uneuZYaLXTFV8IQZR5edX+mVILgfXkbKFc
// SIG // dZ4OlUUs8Mg5fuW86F1CZupZ4sTJi5J53BYLt0wCpjjV
// SIG // MeFF433uGRZ3FRJv6p7HFpTxmZTqIFbKb0F1zDz67qYD
// SIG // piUZUS2yj040+eMYjwFvUkyeHAC1gStVzj2owxjQ9aoJ
// SIG // +DSTGmx0C3ljwAWR8lTTs6tVyEwKyTSrWFjWSJv6kZIp
// SIG // J3xt8nUpnJBZy/MwjRzxLLzlLYqhghewMIIXrAYKKwYB
// SIG // BAGCNwMDATGCF5wwgheYBgkqhkiG9w0BBwKggheJMIIX
// SIG // hQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBWgYLKoZIhvcN
// SIG // AQkQAQSgggFJBIIBRTCCAUECAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgHf7YREd1zrUkdslX4LVT
// SIG // Yiko14pbZGEas2k1EotdWh0CBmgtv9PyjhgTMjAyNTA2
// SIG // MzAxNDQxNTIuOTU2WjAEgAIB9KCB2aSB1jCB0zELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0
// SIG // IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMScwJQYD
// SIG // VQQLEx5uU2hpZWxkIFRTUyBFU046NkIwNS0wNUUwLUQ5
// SIG // NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFNlcnZpY2WgghH+MIIHKDCCBRCgAwIBAgITMwAAAfaD
// SIG // LyZqVF0iwQABAAAB9jANBgkqhkiG9w0BAQsFADB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNDA3MjUx
// SIG // ODMxMDRaFw0yNTEwMjIxODMxMDRaMIHTMQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
// SIG // bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
// SIG // Hm5TaGllbGQgVFNTIEVTTjo2QjA1LTA1RTAtRDk0NzEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBANFCXizEfzfVjwWYbilRRfnliWevFro3Y+F+iUdO
// SIG // XMTuQnqTV6Ne61Ws8Fi5JuQI2lYdfWVYwwoR84psbKGl
// SIG // 8TbvCA4ICsKV76QACLb+FMedHvUtrlcHyr+e6fSShvkO
// SIG // 1TjUobo5dTQjJHIEqz3Znf/M3LJoc3DaGy6JqwgCDkWf
// SIG // CMIWMuLIlUJX9TSoZcgM5pFiQ9DfutCIqIBQc4N8iErL
// SIG // 66DsdMdcUotj4kSEJU1xO+DIIGQyAyqh/4W/RU9pCv51
// SIG // f2l47qPSzK60Zp+OKGGAA3v6zveRfkht7rroX/h+CK4l
// SIG // 69IfabQOksByT0tlZmzVgo0FquRuGJK3KmzzGse7zV1M
// SIG // Lu0+uRPHxT3dSLhPUbBuEzAFe15FwaKZjzX7y9IY8YOO
// SIG // JKUJ9/OFeOqPs3UKsuSvXQ5Vpvyer2baecgNT8g98Ph2
// SIG // xrm0tJ4hENS+sBjqz38yJtBXTp/sRaOPBEZfhccP9zr1
// SIG // zOQmNRKp8xM5z48yXOzicISVUd1UAx4wXBBUzr0vRNHY
// SIG // jbtXqHMPmQpM+D7v6EL/oKlPm38S/HuzxZLX0Q5TOhcj
// SIG // s4z+M7iNuYA/LTvcyYOoOn0aWmXON/ZgG5Jd8wlc0yw4
// SIG // HIb+ksUGoybb76EGmcUH9LUYj3G69h1nzKKqnfbokNIU
// SIG // 1BIRuOBQUk3lD2XhHp0QlmnQluBvAgMBAAGjggFJMIIB
// SIG // RTAdBgNVHQ4EFgQUSMGbCbjnCX0nD1nF2bgQOAfPSvIw
// SIG // HwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIw
// SIG // XwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0JTIw
// SIG // VGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
// SIG // CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9N
// SIG // aWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAx
// SIG // MCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8E
// SIG // DDAKBggrBgEFBQcDCDAOBgNVHQ8BAf8EBAMCB4AwDQYJ
// SIG // KoZIhvcNAQELBQADggIBANd5AYqx9XB7tVmEdcrI9dua
// SIG // JhrUND2kJBM8Bm+9MbakqCPrL0IobIHU2MWj36diFRXY
// SIG // I2jGgYvNcAfP57vOuhXxSinYXad8JzGfdT6T+DqHuzXH
// SIG // +qiApIErsIHSHUL6hNIfFUOUFubA1eENCZ4+H+yh2MeD
// SIG // YjPAuI08PEkLbLsVokx9h4pH90GAe9Wu3Qfc4BzpFtIY
// SIG // FBHljvZodsFqmEv0OPAEozqmMP4WueKFTn39tlmqB/vx
// SIG // 8XfTUxFP+L5b7ESDFk9I7JzSO9Y1QK0+EPQbelUoVs8q
// SIG // q2hOkilKGaxMAaVbCNCzINl94Ti25Qtb8TN/sDMjofe2
// SIG // hTrO7BZ7nprSNjH4/KoNegWUycV5aT7q1qxvjgY+AaEw
// SIG // 5AvQMV2Ad8hLbsDLO6UVi8sSMcP8FfUxylBpvsflRNDz
// SIG // i8JK0jII7pUl5KXxCx1loglbJSWxSCAf+AJb/o0CUigC
// SIG // bqPQhK25tqng5P84yWJWGlRjMirmGfrkkVSgdqpBD3BM
// SIG // xtXTvcyGtTKd9ifs81tz+7LiX48OtrN4Qzi5PupTEDkd
// SIG // OMftqNexty3Hi5JMSZuNRK3Yk4wJnQpXp/cpeh4DKRku
// SIG // KJIxQiV/gqThV+4AQNz1cUFrm4rAEGy+R4ExQbUDRM3A
// SIG // nYdRmMP+p88zTbftBkJ56GwXXXzgIqpM7yLal47xsitU
// SIG // MIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJmQAAAAAA
// SIG // FTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2Vy
// SIG // dGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMw
// SIG // MTgyMjI1WhcNMzAwOTMwMTgzMjI1WjB8MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
// SIG // BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O
// SIG // 1YLT/e6cBwfSqWxOdcjKNVf2AX9sSuDivbk+F2Az/1xP
// SIG // x2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhgfWpS
// SIG // g0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/Y
// SIG // JlN8OWECesSq/XJprx2rrPY2vjUmZNqYO7oaezOtgFt+
// SIG // jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/dvI2k45GP
// SIG // sjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6
// SIG // BVWYbWg7mka97aSueik3rMvrg0XnRm7KMtXAhjBcTyzi
// SIG // YrLNueKNiOSWrAFKu75xqRdbZ2De+JKRHh09/SDPc31B
// SIG // mkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn42
// SIG // 7DZM9ituqBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n
// SIG // 6Jl8P0zbr17C89XYcz1DTsEzOUyOArxCaC4Q6oRRRuLR
// SIG // vWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2
// SIG // ZItboKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9
// SIG // stQcxWv2XFJRXRLbJbqvUAV6bMURHXLvjflSxIUXk8A8
// SIG // FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
// SIG // AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQAB
// SIG // MCMGCSsGAQQBgjcVAgQWBBQqp1L+ZMSavoKRPEY1Kc8Q
// SIG // /y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacbUzUZ
// SIG // 6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/
// SIG // BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnkuaHRtMBMG
// SIG // A1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQM
// SIG // HgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMB
// SIG // Af8EBTADAQH/MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjR
// SIG // PZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6
// SIG // Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1
// SIG // Y3RzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBa
// SIG // BggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWlj
// SIG // Um9vQ2VyQXV0XzIwMTAtMDYtMjMuY3J0MA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
// SIG // XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x
// SIG // 5MKP+2zRoZQYIu7pZmc6U03dmLq2HnjYNi6cqYJWAAOw
// SIG // Bb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVtI1Tk
// SIG // eFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8Z
// SIG // thISEV09J+BAljis9/kpicO8F7BUhUKz/AyeixmJ5/AL
// SIG // aoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTpkbKpW99J
// SIG // o3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32
// SIG // THJvEKt1MMU0sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEU
// SIG // BHG/ZPkkvnNtyo4JvbMBV0lUZNlz138eW0QBjloZkWsN
// SIG // n6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQ
// SIG // THa1V1QJsWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+
// SIG // y/g75LcVv7TOPqUxUYS8vwLBgqJ7Fx0ViY1w/ue10Cga
// SIG // iQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0l
// SIG // lOZ0dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghi
// SIG // f9lwY1NNje6CbaUFEMFxBmoQtB1VM1izoXBm8qGCA1kw
// SIG // ggJBAgEBMIIBAaGB2aSB1jCB0zELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQg
// SIG // T3BlcmF0aW9ucyBMaW1pdGVkMScwJQYDVQQLEx5uU2hp
// SIG // ZWxkIFRTUyBFU046NkIwNS0wNUUwLUQ5NDcxJTAjBgNV
// SIG // BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wi
// SIG // IwoBATAHBgUrDgMCGgMVABVPXkqXcbNGtOiRSLhhRyI/
// SIG // yPt+oIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEm
// SIG // MCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // IDIwMTAwDQYJKoZIhvcNAQELBQACBQDsDPbnMCIYDzIw
// SIG // MjUwNjMwMTE0MzM1WhgPMjAyNTA3MDExMTQzMzVaMHcw
// SIG // PQYKKwYBBAGEWQoEATEvMC0wCgIFAOwM9ucCAQAwCgIB
// SIG // AAICBLcCAf8wBwIBAAICEz8wCgIFAOwOSGcCAQAwNgYK
// SIG // KwYBBAGEWQoEAjEoMCYwDAYKKwYBBAGEWQoDAqAKMAgC
// SIG // AQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQsF
// SIG // AAOCAQEAV2grh6EFLn5u1Aq1P+P5In+id23mdtcOVzKh
// SIG // oKw6QZ8itEDPg7xBB9AO2K1I2Th4HrZEJjLnV/BAfbAA
// SIG // ycf7T1NjYXeChtBV35AoEd7PteBls0xS7cUJ/D8HpphI
// SIG // EoEGF2TGsxW+Nx4bKoJC58TofwmEaHtHbV3pO59PIiZ8
// SIG // qqlX2dRS5P3DkxBknRyjJveSNkMZJSSlBlZeO3/RLjH5
// SIG // B462zGDhbiw9+LKTBgngplVq7xcZ+CTimQ/HMpGFj1eY
// SIG // hXpNOVlYVlg3vCoD+kq3+y+CzAItGB6OvRUGuqgzuEpa
// SIG // zliGqGoitWlwUpWOvjVhVS9PEKCggwDMVQ6p/+iMbDGC
// SIG // BA0wggQJAgEBMIGTMHwxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
// SIG // QSAyMDEwAhMzAAAB9oMvJmpUXSLBAAEAAAH2MA0GCWCG
// SIG // SAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZI
// SIG // hvcNAQkQAQQwLwYJKoZIhvcNAQkEMSIEIL602VUIXAs9
// SIG // af5had0DhT/DzhzP3g3uu/IO/qjVmaQBMIH6BgsqhkiG
// SIG // 9w0BCRACLzGB6jCB5zCB5DCBvQQgK2FM8ZRepuVEi0uH
// SIG // /DVy//GqDRFXbAmUZhfi5UIxtqIwgZgwgYCkfjB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAfaDLyZq
// SIG // VF0iwQABAAAB9jAiBCD0EzICnwCLRnsOtmhmW1ZWzoZy
// SIG // IgE8aAK9m0XdZftx2DANBgkqhkiG9w0BAQsFAASCAgBs
// SIG // AQ+Xn5ClabZ0kFIaG3uveyxUBhMv1f6qUGd9+KG8MPjl
// SIG // 7kFG0eu6MDOy6rdYxwPwQnoXvihvypzF1lPRvl+9unZL
// SIG // mYYWPgnDaKqzeimDWuV7Kxc+H+8LBHiXtFtfr+C5Qdz0
// SIG // MIfsKssRMk4k3+xUkWVAdgMIa5hXD0xKi6t0XeRuEDPk
// SIG // LaywvtyBnDxUga06zySOjmPCgjz5Sr7xSShjWxX1oW2H
// SIG // 9H++nbEeKuZcAW5Uw32X9+1c/CTl2yDNmfSrT9wEwHMX
// SIG // VrbjAwruL6qcHd7j3sm8jFup1xoPAvdM3233MKcCDHYN
// SIG // 2pjbN5v5N7qrC1W8FBABP+STL5+VEVi05yE+PLaIYDVD
// SIG // 2H4elxQzbLeT7Laq2bYB/AffFT4pMyfcfpiPobi0whrP
// SIG // pCKxXr+zrudaArRPjxl//N3WVPsEdAgCcY8jYYK4TMvC
// SIG // rOlJ7oZW7wGIDgq6ZwIP4IfT9bP3W0vu9Iag/KyMbYbV
// SIG // +Bihb8HGDwbj6hZnuRIqufQp7DN7z/DEZwcUvabj0Irg
// SIG // 3zkYeNz+eIRMR40iPa3OJPAeU9Bbb+DLyCJ29ZG/ez3Z
// SIG // IGPUC1VScQhyV1VtafXcZowNbJujSSC7bXFmsS//fWOA
// SIG // Xx3mH/4bs2IYb+ers20Li0a/lm0yCIfacO676H8LaWwF
// SIG // 1PVFJZ13PZCVJ3idrIVrRQ==
// SIG // End signature block
