define("BenchmarkDotNetUI",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,r,i,n)=>{return o={360:e=>{const t=document.createElement("script");t.id="BenchmarkRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InRleHQ6IG5hbWUiPjwvc3Bhbj4NCiAgICA8L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InN0YXJ0VGltZSIgZGF0YS1iaW5kPSJ0ZXh0OiBzdGFydFRpbWVGb3JtYXR0ZWQiIGRhdGEtY29sdW1uaWQ9InN0YXJ0VGltZSI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJzdG9wVGltZSIgZGF0YS1jb2x1bW5pZD0ic3RvcFRpbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InRleHQ6IHN0b3BUaW1lRm9ybWF0dGVkIj48L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJtZWFuIiBkYXRhLWJpbmQ9ImxvY2FsaXplZE5hbm9zOiB7dmFsdWU6IG1lYW4sIHVuaXQ6IHVuaXR9IiBkYXRhLWNvbHVtbmlkPSJtZWFuIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9ImVycm9yIiBkYXRhLWJpbmQ9ImxvY2FsaXplZE5hbm9zOiB7dmFsdWU6IGVycm9yLCB1bml0OiB1bml0fSIgZGF0YS1jb2x1bW5pZD0iZXJyb3IiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ic3RkZGV2IiBkYXRhLWJpbmQ9ImxvY2FsaXplZE5hbm9zOiB7dmFsdWU6IHN0ZGRldiwgdW5pdDogdW5pdH0iIGRhdGEtY29sdW1uaWQ9InN0ZGRldiI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJudW0iIGRhdGEtYmluZD0idGV4dDogbnVtIiBkYXRhLWNvbHVtbmlkPSJudW0iPjwvdGQ+DQo8L3RyPg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},706:(e,t,r)=>{var i,n;i=[r,t,r(28),r(226),r(952),r(560),r(881),r(881),r(881),r(881),r(881),r(117),r(117),r(117),r(756),r(497),r(766),r(680),r(833),r(103)],n=function(e,t,r,i,n,o,s,a,c,d,m,l,u,h,g,I,p){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getBenchmarkViewModel=t.BenchmarkDotNetViewModel=void 0;class b{constructor(){let e;this._currentOverlay=r.pureComputed((()=>this.computeOverlay())),l.loadDataWarehouse().then((t=>(e=t,e.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((t=>{this._benchmarkDao=new I.BenchmarkDAO(e,t,k);const o=new s.TreeGridHeaderViewModel([{id:"name",text:i.Resources.getString("BenchmarkHeaderName"),hideable:!1,sortable:d.SortDirection.Desc},{id:"startTime",text:i.Resources.getString("BenchmarkHeaderStartTime"),hideable:!0,sortable:d.SortDirection.Asc},{id:"stopTime",text:i.Resources.getString("BenchmarkHeaderStopTime"),hideable:!0,sortable:d.SortDirection.Desc},{id:"mean",text:i.Resources.getString("BenchmarkHeaderMean"),hideable:!0,sortable:d.SortDirection.Desc},{id:"error",text:i.Resources.getString("BenchmarkHeaderError"),hideable:!0,sortable:d.SortDirection.Desc},{id:"stddev",text:i.Resources.getString("BenchmarkHeaderStdDev"),hideable:!0,sortable:d.SortDirection.Desc},{id:"num",text:i.Resources.getString("BenchmarkHeaderNum"),hideable:!0,sortable:d.SortDirection.Desc}],new g.BenchmarkColumnSettingsProvider,this._benchmarkDao.defaultSortColumnId);this._benchmark=new c.TreeGridViewModel(this._benchmarkDao,o,"BenchmarkAriaLabel"),this._benchmark.onResultChanged(0);const a=h.getViewEventManager();a.selectionChanged.addEventListener((e=>{e.isIntermittent||this._benchmarkDao.timeFilter().equals(e.position)||(this._benchmarkDao.timeFilter(e.position),this._benchmark.onResultChanged(0))})),r.applyBindings(this),a.detailsViewReady.raiseEvent({Id:n.BenchmarkDotNetViewId()})}))}get benchmark(){return this._benchmark}get currentOverlay(){return this._currentOverlay}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==o.KeyCodes.C)return!0;const r=a.TreeGridUtils.formatTreeGridSelectedToText(this._benchmark);return navigator.clipboard.writeText(r),!1}contextMenu(e,t){const r=e;if("number"!=typeof r.id)return null;const n=()=>{this._benchmarkDao.showSourceFile(r.id)},o=()=>{this._benchmarkDao.raiseSelectionTimeChanged(u.JsonTimespan.fromNumber(r.startTimeNs,r.stopTimeNs))},s=[{label:i.Resources.getString("ContextMenu_Select"),callback:()=>o(),disabled:()=>!1,type:i.ContextMenu.MenuItemType.command},{label:i.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>n(),disabled:()=>!1,type:i.ContextMenu.MenuItemType.command},{type:i.ContextMenu.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=a.TreeGridUtils.formatTreeGridSelectedToText(this._benchmark);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command},{label:i.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=a.TreeGridUtils.formatTreeGridSelectedToMarkdown(this._benchmark);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command}];return i.ContextMenu.create(s)}computeOverlay(){return this._benchmark.dataLoadStatus()===d.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._benchmark.dataLoadStatus()===d.DataLoadEvent.DataLoadCompleted&&0===this._benchmark.treeAsArray().length?{name:"MessageView",data:i.Resources.getString("NoDataMessage")}:null}}let v;t.BenchmarkDotNetViewModel=b;const k=new p.BenchmarkDotNetMarshaler;k.getDoubleClickTimeMs().then((e=>{m.Init(e),v=new b})),t.getBenchmarkViewModel=function(){return v}}.apply(t,i),void 0===n||(e.exports=n)},756:(e,t,r)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BenchmarkColumnSettingsProvider=void 0,t.BenchmarkColumnSettingsProvider=class{getColumnSettings(){return Promise.resolve([{columnId:"name",isHidden:!1,width:500},{columnId:"startTime",isHidden:!1,width:140},{columnId:"stopTime",isHidden:!1,width:140},{columnId:"mean",isHidden:!1,width:140},{columnId:"error",isHidden:!1,width:140},{columnId:"stddev",isHidden:!1,width:140},{columnId:"num",isHidden:!1,width:140}])}onColumnChanged(e){}}}.apply(t,[r,t]),void 0===i||(e.exports=i)},497:(e,t,r)=>{var i,n;i=[r,t,r(28),r(952),r(881),r(117),r(117),r(813),r(560),r(117)],n=function(e,t,r,i,n,o,s,a,c,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BenchmarkDAO=void 0;class m{constructor(e,t,i){this._dataWarehouse=e,this._timeFilter=r.observable(t),this._marshaller=i}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"startTime"}async getRoots(e,t,r){const n={timeDomain:this.timeFilter(),customDomain:{view:"Benchmarks"}},o=await this._dataWarehouse.getFilteredData(n,i.BenchmarkDotNetAnalyzer(),r);r?.throwIfCancellationRequested(),this._currentResult&&await this._currentResult.dispose(),this._currentResult=o;const s=await this._currentResult.getResult({task:"listBenchmarks",id:0,path:[]},r);r?.throwIfCancellationRequested();const d=[];s.forEach((e=>{d.push(e.mean),d.push(e.stddev),d.push(e.error)}));const m=new c.NanosecondTimeUnitConverter(3).findLowestUnit(d),l=s.map((e=>new a.BenchmarkRowViewModel(this,e,0,m)));return await this.sort(l,t,r),l}sort(e,t,r){const i=m.SortFunc[t.columnId];if(i){const r=(e,r)=>i(t.direction)(e,r),n=e=>{e.children&&(e.children.sort(r),e.children().forEach(n))};return e.sort(r),e.forEach(n),Promise.resolve(e)}return o.Assert.fail(`Unknown sort column: ${t.columnId}`),Promise.resolve(e)}search(e,t,r,i,n,o,s){throw new Error("Not implemented")}expand(e,t,r){return Promise.resolve(void 0)}getSourceInfo(e){return this._currentResult.getResult({task:"sourceInfo",id:e,path:[]}).then((e=>e.sfp))}raiseSelectionTimeChanged(e){d.getViewEventManager().selectionChanged.raiseEvent({position:e,isIntermittent:!1})}async showSourceFile(e){const t=await this.getSourceInfo(e);await s.getSourceFileViewerService().openSourcePosition(t)}}t.BenchmarkDAO=m,m.SortFunc={name:e=>n.SortFunctions.stringSort("name",e),count:e=>n.SortFunctions.numericSort("count",e),startTime:e=>n.SortFunctions.numericSort("startTimeNs",e),stopTime:e=>n.SortFunctions.numericSort("stopTimeNs",e),mean:e=>n.SortFunctions.numericSort("mean",e),error:e=>n.SortFunctions.numericSort("error",e),stddev:e=>n.SortFunctions.numericSort("stddev",e),num:e=>n.SortFunctions.numericSort("num",e)}}.apply(t,i),void 0===n||(e.exports=n)},813:(e,t,r)=>{var i,n;i=[r,t,r(28),r(117),r(560),r(360)],n=function(e,t,r,i,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BenchmarkRowViewModel=void 0,t.BenchmarkRowViewModel=class{constructor(e,t,i,n){this._selected=r.observable(!1),this._expanded=r.observable(!1),this._dao=e,this._dto=t,this._depth=i,this._children=r.observableArray([]),this._unit=n}get templateName(){return"BenchmarkRowView"}get id(){return this._dto.id}get depth(){return this._depth}get name(){return this._dto.n}get startTimeFormatted(){return n.RulerUtilities.formatTime(i.BigNumber.convertFromNumber(this._dto.s))}get stopTimeFormatted(){return n.RulerUtilities.formatTime(i.BigNumber.convertFromNumber(this._dto.st))}get startTimeNs(){return this._dto.s}get stopTimeNs(){return this._dto.st}get mean(){return this._dto.mean}get error(){return this._dto.error}get stddev(){return this._dto.stddev}get unit(){return this._unit.Unit}get num(){return this._dto.num}get hasSourceInfo(){return!0}get selected(){return this._selected}get expanded(){return this._expanded}get children(){return this._children}invoke(){this._dao.raiseSelectionTimeChanged(i.JsonTimespan.fromNumber(this.startTimeNs,this.stopTimeNs))}}}.apply(t,i),void 0===n||(e.exports=n)},952:(e,t,r)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BenchmarkDotNetAnalyzer=t.BenchmarkDotNetViewId=void 0,t.BenchmarkDotNetViewId=function(){return"7fe46d40-4840-48a3-950c-3572a3adfa03"},t.BenchmarkDotNetAnalyzer=function(){return"a2ba596e-89de-4252-b082-29dc3681b632"}}.apply(t,[r,t]),void 0===i||(e.exports=i)},371:function(e,t,r){var i,n,o=this&&this.__createBinding||(Object.create?function(e,t,r,i){void 0===i&&(i=r),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[r]}})}:function(e,t,r,i){void 0===i&&(i=r),e[i]=t[r]}),s=this&&this.__exportStar||function(e,t){for(var r in e)"default"===r||Object.prototype.hasOwnProperty.call(t,r)||o(t,e,r)};i=[r,t,r(706),r(558)],n=function(e,t,r,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),s(r,t),window.BenchmarkDotNetUI_onAfterDomInsert=i.onAfterDomInsert}.apply(t,i),void 0===n||(e.exports=n)},766:(e,t,r)=>{var i,n;i=[r,t,r(226)],n=function(e,t,r){"use strict";let i;Object.defineProperty(t,"__esModule",{value:!0}),t.BenchmarkDotNetMarshaler=void 0,t.BenchmarkDotNetMarshaler=class{constructor(){i||(i=r.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.BenchmarkDotNet.BenchmarkDotNetMarshaler",{},!0))}getDoubleClickTimeMs(){return i._call("getDoubleClickTimeMs")}}}.apply(t,i),void 0===n||(e.exports=n)},558:(e,t,r)=>{var i,n;i=[r,t,r(28),r(560)],n=function(e,t,r,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.areTimespansEqual=t.onAfterDomInsert=void 0,t.onAfterDomInsert=function(){const e=document.getElementById("mainToolbar"),t=r.utils.domData.get(e,"mediaQuery");if(t){const i=r.utils.domData.get(e,"mediaQueryListener");t.removeListener(i)}const n=e.children;let o=45;for(let e=0;e<n.length;e++)o+=n.item(e).offsetWidth;const s=t=>{t.matches?e.classList.add("limitedSpace"):e.classList.remove("limitedSpace")},a=window.matchMedia(i.Utilities.formatString("(max-width: {0}px)",o.toString()));s(a),a.addListener(s),r.utils.domData.set(e,"mediaQuery",a),r.utils.domData.set(e,"mediaQueryListener",s)},t.areTimespansEqual=function(e,t){return!e&&!t||e&&t&&e.equals(t)}}.apply(t,i),void 0===n||(e.exports=n)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=r},28:e=>{"use strict";e.exports=i},226:e=>{"use strict";e.exports=n}},s={},function e(t){var r=s[t];if(void 0!==r)return r.exports;var i=s[t]={exports:{}};return o[t].call(i.exports,i,i.exports,e),i.exports}(371);var o,s}));
// SIG // Begin signature block
// SIG // MIIoRAYJKoZIhvcNAQcCoIIoNTCCKDECAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // jwI1RUhLVy+8229hfADBEmi9RTiZQCnyOeg+dZ9DsFSg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghomMIIaIgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCA+t8GKOimwDyaKSJLkpxVjT7AeqtMewrB6
// SIG // mMokmuW5KjBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAEosXWsS
// SIG // 9yOmsD9bmqdIrt18gCNz4K6A1RRdhAZnP+3ZPeOQFGyI
// SIG // zABF/khzxed2lvVRy/I6ETdxahgkJvoOI/em6rm9ffyF
// SIG // SKIh89ZVnqLV6/l5gfTyQ+ge86qF4TMaEjsJwk0kbmuO
// SIG // 6C7EvTmEjfbNtmN0hMWTocHhm2xg+b57XxmyuixxHK0k
// SIG // KZ7w4g+blhcPxp50dKMWa5G+3BzUD5xY49e2bLGOqLka
// SIG // s7CCbJVia+gUs3ZV8sZtwfU5PD62Cyjgxdc0W93AoRTk
// SIG // O/++m5+NcJ7yuhq8lCiZ110RXIdRXRpaKvDga1Q+XEst
// SIG // K7bePHz8Wy+6VHyR2jBB/6/xX9ahghewMIIXrAYKKwYB
// SIG // BAGCNwMDATGCF5wwgheYBgkqhkiG9w0BBwKggheJMIIX
// SIG // hQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBWgYLKoZIhvcN
// SIG // AQkQAQSgggFJBIIBRTCCAUECAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgqBThlGD7ngh7Q4C8dKA4
// SIG // deZVrbHrIjW0iWcX1kTe88sCBmhSvkLxhBgTMjAyNTA2
// SIG // MzAxNDQ4MzQuMzE0WjAEgAIB9KCB2aSB1jCB0zELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0
// SIG // IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMScwJQYD
// SIG // VQQLEx5uU2hpZWxkIFRTUyBFU046MkQxQS0wNUUwLUQ5
// SIG // NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFNlcnZpY2WgghH+MIIHKDCCBRCgAwIBAgITMwAAAf1z
// SIG // +WhazQxh7QABAAAB/TANBgkqhkiG9w0BAQsFADB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNDA3MjUx
// SIG // ODMxMTZaFw0yNTEwMjIxODMxMTZaMIHTMQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
// SIG // bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
// SIG // Hm5TaGllbGQgVFNTIEVTTjoyRDFBLTA1RTAtRDk0NzEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKFlrPg/jruCY2J0R0XnbtDExWMzSRFT5yC83NNk
// SIG // d6m57o74WYJIafqf5cpmC85EMhts6cWHHk4yBex4kFm7
// SIG // ehVtwEZAa7YSVM9OWZyqXBd9ZaVBG/IFF4g9sSKaPGDP
// SIG // kg9EvoUz9UwgP8Ht/MmdwRLZmbXFZ2i0afwL7KoPuSiN
// SIG // CsOkwyaSsEy5dFVtP9t7CopHlg0px0Hk6aztMyJv27Wo
// SIG // EmJt1f/M15X8cu7PxFRXUoJRxrFKvBGbqVDvF2x88+7V
// SIG // Ecog95DsTZ8OaMdXmV/3P15luB+m+MjZmRdME2bsN+8g
// SIG // NTySjskkq161hIfh+vvlm+vtZbTAj6DCR1LTz9wp9AjX
// SIG // Db6z8ibQ2nKo5yE6y867B3Ti6o7B9tvWZL53ZNCKsQQ2
// SIG // YDKGPhH+33xUT9qT5KxdRfSHAZGM/IS/kI1/ruMuFKqu
// SIG // FLU+1UZ7Kr0f8f/kCxNKXEhIf1xNcNX3KeiZqvEZxxF4
// SIG // pMnDCzf2vymMaUj9xXxWy2bn/qiK8hS9IBA8rWqRp9Tj
// SIG // Y1ZIiqVT9rqlSGI+FYgo8uaS1HHjHqoioGKoaZlBwhNl
// SIG // rLCy4XUAR3aZdvPpPmWOpuHTxZxKBnCR7jHCGZ8OHDsI
// SIG // saI0Tq/jau9XCY+0OC9F8D77kx0LdKB+0SjEIJrMuwlQ
// SIG // +7+eXToXR13WLMjuvXQHSvp1pcmHAgMBAAGjggFJMIIB
// SIG // RTAdBgNVHQ4EFgQU6QzFwOGVvPsi9vt7wOkZlO6BCqQw
// SIG // HwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIw
// SIG // XwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0JTIw
// SIG // VGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
// SIG // CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9N
// SIG // aWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAx
// SIG // MCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8E
// SIG // DDAKBggrBgEFBQcDCDAOBgNVHQ8BAf8EBAMCB4AwDQYJ
// SIG // KoZIhvcNAQELBQADggIBAGPYWF/k+QJgq2Bmh/ek3UeU
// SIG // +dvzzThu8kmHqKb+H5Zw1kC4QZa2rwIPqY5Tb+V0l2ay
// SIG // hr/HuLOXSeVnYXwvcsBUKuE5l51Hrz17Zbm2ZPtNgVyu
// SIG // v9t4TNE0irNipYWIqs20XvEGzHylxA7bzKB0mU+6/sCN
// SIG // iII2EMJGvtz/VV4BEcLuOv3M8/CEf2avrzuedtyZXerL
// SIG // Fbs7PbsCKyYX3GAY+dJl1kQXDIc2oy41g4HIodA7spD3
// SIG // AaaEy5Ti/C6V6KKp6/kC2BOAaVHqdyckjGHz89oXzi94
// SIG // NNlhH7DsafADW3HYqjN9XZt70oXhJJoxwNs7jPk4J+I+
// SIG // Z/gJ8uyDg2EJCKzVYS3TC9PXrtXSD4aduJRbZ1k2DWhU
// SIG // znzKhWtwG/CgyonJqdALYUTWVYNATwC+fPgdFHKARis0
// SIG // vY7HMDk7tSZjZYrDipFVFZEieRaP3LXw0j3Qk1WiF1xe
// SIG // 5eNJNXDP19jtCXQEve0+/JWI7cPz8m7s1+bIcQYf0akz
// SIG // 7wsgISMQVSnzf4X7OAiKBWqlidK//EgdQhrMsiHD3xID
// SIG // KPHHqtcOWaNCX58hYuhrqPs9yzxZf3sUGkbmxK7AFE38
// SIG // gWOf+ZYsr4wIMg2JxAfLxzu3OxYNrRneYRoGLPgDqFsd
// SIG // uPl3MsaVJAGow4ZMvQ5fvCWU47bOgXE/bGE5jqHZP0oC
// SIG // MIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJmQAAAAAA
// SIG // FTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2Vy
// SIG // dGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMw
// SIG // MTgyMjI1WhcNMzAwOTMwMTgzMjI1WjB8MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
// SIG // BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O
// SIG // 1YLT/e6cBwfSqWxOdcjKNVf2AX9sSuDivbk+F2Az/1xP
// SIG // x2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhgfWpS
// SIG // g0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/Y
// SIG // JlN8OWECesSq/XJprx2rrPY2vjUmZNqYO7oaezOtgFt+
// SIG // jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/dvI2k45GP
// SIG // sjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6
// SIG // BVWYbWg7mka97aSueik3rMvrg0XnRm7KMtXAhjBcTyzi
// SIG // YrLNueKNiOSWrAFKu75xqRdbZ2De+JKRHh09/SDPc31B
// SIG // mkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn42
// SIG // 7DZM9ituqBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n
// SIG // 6Jl8P0zbr17C89XYcz1DTsEzOUyOArxCaC4Q6oRRRuLR
// SIG // vWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2
// SIG // ZItboKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9
// SIG // stQcxWv2XFJRXRLbJbqvUAV6bMURHXLvjflSxIUXk8A8
// SIG // FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
// SIG // AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQAB
// SIG // MCMGCSsGAQQBgjcVAgQWBBQqp1L+ZMSavoKRPEY1Kc8Q
// SIG // /y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacbUzUZ
// SIG // 6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/
// SIG // BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnkuaHRtMBMG
// SIG // A1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQM
// SIG // HgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMB
// SIG // Af8EBTADAQH/MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjR
// SIG // PZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6
// SIG // Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1
// SIG // Y3RzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBa
// SIG // BggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWlj
// SIG // Um9vQ2VyQXV0XzIwMTAtMDYtMjMuY3J0MA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
// SIG // XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x
// SIG // 5MKP+2zRoZQYIu7pZmc6U03dmLq2HnjYNi6cqYJWAAOw
// SIG // Bb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVtI1Tk
// SIG // eFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8Z
// SIG // thISEV09J+BAljis9/kpicO8F7BUhUKz/AyeixmJ5/AL
// SIG // aoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTpkbKpW99J
// SIG // o3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32
// SIG // THJvEKt1MMU0sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEU
// SIG // BHG/ZPkkvnNtyo4JvbMBV0lUZNlz138eW0QBjloZkWsN
// SIG // n6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQ
// SIG // THa1V1QJsWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+
// SIG // y/g75LcVv7TOPqUxUYS8vwLBgqJ7Fx0ViY1w/ue10Cga
// SIG // iQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0l
// SIG // lOZ0dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghi
// SIG // f9lwY1NNje6CbaUFEMFxBmoQtB1VM1izoXBm8qGCA1kw
// SIG // ggJBAgEBMIIBAaGB2aSB1jCB0zELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQg
// SIG // T3BlcmF0aW9ucyBMaW1pdGVkMScwJQYDVQQLEx5uU2hp
// SIG // ZWxkIFRTUyBFU046MkQxQS0wNUUwLUQ5NDcxJTAjBgNV
// SIG // BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wi
// SIG // IwoBATAHBgUrDgMCGgMVAKI9FrVVUFDUiqKra44p0QLA
// SIG // VHaDoIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEm
// SIG // MCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // IDIwMTAwDQYJKoZIhvcNAQELBQACBQDsDQ3wMCIYDzIw
// SIG // MjUwNjMwMTMyMTUyWhgPMjAyNTA3MDExMzIxNTJaMHcw
// SIG // PQYKKwYBBAGEWQoEATEvMC0wCgIFAOwNDfACAQAwCgIB
// SIG // AAICF14CAf8wBwIBAAICE2UwCgIFAOwOX3ACAQAwNgYK
// SIG // KwYBBAGEWQoEAjEoMCYwDAYKKwYBBAGEWQoDAqAKMAgC
// SIG // AQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQsF
// SIG // AAOCAQEAXK9CI1u5YL8rff3z5sgEsHcrQncMq07FyIn3
// SIG // to/A8UkPWrK3vf/4kidBymMDtsltrilkrEYD0cqHagoz
// SIG // VE7EImBkEuOvgKNhzZd9fiPISWMnmgUuy1dDxZW9oKBQ
// SIG // T5CyQSc4zVafQxhIe4OTEEJkvXeHNe6RE8tEbW8xGTF+
// SIG // KPuhbX6o5UUupf1OEcmNPYkFskWqWGhmsRLuiywMJEdq
// SIG // Z8Zf8yaEZ4+1CQz8w+Y82b8YxeXHtVLg28RWKY5Wj+Bs
// SIG // 7FBmBlUXw3fwICZbD/90c6mYDMHCIR5HmrCqM2xy0iKS
// SIG // Tm+OohvRkORUyT3RkLi7gymSBVoS+B01Cf2fCqba4zGC
// SIG // BA0wggQJAgEBMIGTMHwxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
// SIG // QSAyMDEwAhMzAAAB/XP5aFrNDGHtAAEAAAH9MA0GCWCG
// SIG // SAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZI
// SIG // hvcNAQkQAQQwLwYJKoZIhvcNAQkEMSIEIEqKvvsepaLI
// SIG // xBG41oEO/GACwP9DU/BewnKaYj0ndst3MIH6BgsqhkiG
// SIG // 9w0BCRACLzGB6jCB5zCB5DCBvQQggChIDclKMLyH8f3g
// SIG // 32ErqR5HhdaehhcIygbPJUQeDUcwgZgwgYCkfjB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAf1z+Wha
// SIG // zQxh7QABAAAB/TAiBCBt8UN+fBvoLZp+bzRwGJ15dZsW
// SIG // LUpAOXpne2Fl875uQjANBgkqhkiG9w0BAQsFAASCAgAL
// SIG // ARgdSDCTG1htEH9qyq9G+aen++MgvrIQX5zyoF1fJKO2
// SIG // rFgOvw92ib7z6gAqlMi4U1Et8lVNtbZ1IXXQDgBdoQnX
// SIG // qhk/ejI337WLO4DGSy9OpprAlELqpsjz1TySnTrQOMpV
// SIG // VpZHCo4c5xkppL/eItafiz49tXseM37w+qXUqL4h9C2a
// SIG // 8TS61Ljgj2VWk74Pfp8I8qyYgpPzt0N24ZnZvjnat0HQ
// SIG // 4MIZ7r+AtV8pZZcM0oU8oswljim4/qiCnkavMCqtIX16
// SIG // PxYZmQdFE6W06PSuGKswu3b3mIHnXlEOs3wPaDouRuI8
// SIG // KYIIPFdICA1+kj3OwGsGYrcL3PQs8Pm9Bj/2jxNhjygd
// SIG // TJnC7SWbgPMTHm9Pp384gCxowQcIqhqOsZdbLBxwD1w3
// SIG // gvsBNGRfhhE/n2TJwxt6KiM1xBbnSJUdqXHMRGwkhNeI
// SIG // UxErECEzv+spfksUeUnVnOxthou9S6/1Mnia3KS2sZ1H
// SIG // U0bEtKkcYdnQ33Xxlida9DaDMLgh8hz/0CW5ik23G+vN
// SIG // BSJgN0odHtMIKmeeztss6q/xRM7BSEqWDuJcIXQfW1Ad
// SIG // 7+9ogWcQ3+sTyoVPWcIIafcylUHP6D4xxEALG3fswx4D
// SIG // 0K9dQlBeb6fiT4PcCp3AON3R4OCVouJ9q2LRrXd4/Y8N
// SIG // 0+EhG9sw3umzbBcJJS7h5Q==
// SIG // End signature block
