define("databaseUI",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,r,i,s)=>{return o={680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},325:e=>{const t=document.createElement("script");t.id="QueryRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ic3RhcnRUaW1lIiBkYXRhLWJpbmQ9ImxvY2FsaXplZE51bWJlcjoge3ZhbHVlOiBzdGFydFRpbWUsIG9wdGlvbnM6IHttaW5pbXVtRnJhY3Rpb25EaWdpdHM6IDMsIG1heGltdW1GcmFjdGlvbkRpZ2l0czogM319IiBkYXRhLWNvbHVtbmlkPSJzdGFydFRpbWUiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0icXVlcnkiIGRhdGEtY29sdW1uaWQ9InF1ZXJ5Ij4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJyb3dJbmRlbnQ6IGRlcHRoIj4mbmJzcDs8L3NwYW4+DQogICAgICAgIDxkaXYgZGF0YS1iaW5kPSJ0cmVlR3JpZEV4cGFuZGVyOiBleHBhbmRlZCwgc3R5bGU6IHsgdmlzaWJpbGl0eTogZXhwYW5kYWJsZSA/ICd2aXNpYmxlJyA6ICdoaWRkZW4nIH0iPjwvZGl2Pg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InRleHQ6IHF1ZXJ5Ij48L3NwYW4+DQogICAgPC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJkdXJhdGlvbiIgZGF0YS1iaW5kPSJ0ZXh0OiBkdXJhdGlvbkRpc3BsYXkiIGRhdGEtY29sdW1uaWQ9ImR1cmF0aW9uIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InJlY29yZHNBZmZlY3RlZCIgZGF0YS1iaW5kPSJ0ZXh0OiByZWNvcmRzQWZmZWN0ZWREaXNwbGF5IiBkYXRhLWNvbHVtbmlkPSJyZWNvcmRzQWZmZWN0ZWQiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0icmVhZENvdW50IiBkYXRhLWJpbmQ9InRleHQ6IHJlYWRDb3VudERpc3BsYXkiIGRhdGEtY29sdW1uaWQ9InJlYWRDb3VudCI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJkYXRhYmFzZSIgZGF0YS1iaW5kPSJ0ZXh0OiBkYXRhYmFzZSIgZGF0YS1jb2x1bW5pZD0iZGF0YWJhc2UiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iY29ubmVjdGlvblN0ciIgZGF0YS1iaW5kPSJ0ZXh0OiBjb25uZWN0aW9uU3RyIiBkYXRhLWNvbHVtbmlkPSJjb25uZWN0aW9uU3RyIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9InF1ZXJ5U291cmNlIiBkYXRhLWJpbmQ9InRleHQ6IHF1ZXJ5U291cmNlIiBkYXRhLWNvbHVtbmlkPSJxdWVyeVNvdXJjZSI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},952:(e,t,r)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseAnalyzerId=t.QueryListDetailsViewId=void 0,t.QueryListDetailsViewId=function(){return"11197EBE-BE05-4A13-BBB9-C482C634CDEE"},t.DatabaseAnalyzerId=function(){return"4EF1311E-9AD5-4A55-B683-1CC2191E4346"}}.apply(t,[r,t]),void 0===i||(e.exports=i)},120:(e,t,r)=>{var i,s;i=[r,t,r(226),r(117)],s=function(e,t,r,i){"use strict";let s;Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseMarshaler=void 0,t.DatabaseMarshaler=class{constructor(){s||(s=r.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.Database.DatabaseMarshaler",{},!0)),this._graphHighlightEvent=new i.ObservableEvent(s,"GraphHighlightChangedEvent")}getDoubleClickTimeMs(){return s._call("getDoubleClickTimeMs")}getColumnSettings(){return s._call("getColumnSettings")}onColumnChanged(e){return s._call("onColumnChanged",e)}updateGraphHighlight(e,t,r){return s._call("raiseGraphHighlightChangedEvent",e,t,r)}clearGraphHighlight(){return s._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}}}.apply(t,i),void 0===s||(e.exports=s)},71:(e,t,r)=>{var i,s;i=[r,t,r(226)],s=function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseTelemetryMarshaler=void 0;let i=null;t.DatabaseTelemetryMarshaler=class{constructor(){i||(i=r.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.Database.DatabaseTelemetryMarshaler",{},!0))}goToSourceUsed(){i._post("goToSourceUsed")}initialColumnVisibility(e,t){i._post("initialColumnVisibility",e,t)}columnVisibilityChanged(e,t){i._post("columnVisibilityChanged",e,t)}sessionLoaded(e,t,r,s,o){i._post("sessionLoaded",e,t,r,s,o)}}}.apply(t,i),void 0===s||(e.exports=s)},371:function(e,t,r){var i,s,o=this&&this.__createBinding||(Object.create?function(e,t,r,i){void 0===i&&(i=r),Object.defineProperty(e,i,{enumerable:!0,get:function(){return t[r]}})}:function(e,t,r,i){void 0===i&&(i=r),e[i]=t[r]}),a=this&&this.__exportStar||function(e,t){for(var r in e)"default"===r||Object.prototype.hasOwnProperty.call(t,r)||o(t,e,r)};i=[r,t,r(566)],s=function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),a(r,t)}.apply(t,i),void 0===s||(e.exports=s)},566:(e,t,r)=>{var i,s;i=[r,t,r(28),r(226),r(952),r(560),r(881),r(881),r(881),r(881),r(881),r(117),r(117),r(117),r(398),r(505),r(120),r(71),r(680),r(833),r(103)],s=function(e,t,r,i,s,o,a,n,d,c,l,u,h,g,m,b,I,p){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getQueryListViewModel=t.QueryListViewModel=void 0;class y{constructor(){let e;this._marshaler=new I.DatabaseMarshaler,this._telemetry=new p.DatabaseTelemetryMarshaler,this._currentOverlay=r.pureComputed((()=>this.computeOverlay())),u.loadDataWarehouse().then((t=>(e=t,e.getContextService().getGlobalContext()))).then((e=>e.getTimeDomain())).then((t=>{this._queryListDAO=new m.QueryListDAO(e,t);const o=new d.TreeGridHeaderViewModel([{id:"startTime",text:i.Resources.getString("QueryListHeaderStartTime"),hideable:!0,sortable:n.SortDirection.Asc},{id:"query",text:i.Resources.getString("QueryListHeaderQuery"),hideable:!1,sortable:n.SortDirection.Desc},{id:"duration",text:i.Resources.getString("QueryListHeaderDuration"),hideable:!1,sortable:n.SortDirection.Desc},{id:"recordsAffected",text:i.Resources.getString("QueryListHeaderRecordsAffected"),hideable:!0,sortable:n.SortDirection.Desc},{id:"readCount",text:i.Resources.getString("QueryListHeaderReadCount"),hideable:!0,sortable:n.SortDirection.Desc},{id:"database",text:i.Resources.getString("QueryListHeaderDatabase"),hideable:!0,sortable:n.SortDirection.Desc},{id:"connectionStr",text:i.Resources.getString("QueryListHeaderConnectionStr"),hideable:!0,sortable:n.SortDirection.Desc},{id:"querySource",text:i.Resources.getString("QueryListHeaderQuerySource"),hideable:!0,sortable:n.SortDirection.Desc}],new b.QueryListColumnSettingsProvider,this._queryListDAO.defaultSortColumnId);this._queryList=new a.TreeGridViewModel(this._queryListDAO,o,"QueryListAriaLabel");const c=h.getViewEventManager();this._queryList.onResultChanged(0),this._queryList.dataLoadPromise.then((()=>this.createSessionLoadedEvent(this._queryList.roots()))),this._queryList.focusedRow.subscribe((()=>{this._marshaler.clearGraphHighlight()})),c.selectionChanged.addEventListener((e=>{e.isIntermittent||(this._queryListDAO.timeFilter(e.position),this._queryList.onResultChanged(0))})),r.applyBindings(this),c.detailsViewReady.raiseEvent({Id:s.QueryListDetailsViewId()})}))}get queryList(){return this._queryList}get currentOverlay(){return this._currentOverlay}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==o.KeyCodes.C)return!0;const r=c.TreeGridUtils.formatTreeGridSelectedToText(this._queryList,!1);return navigator.clipboard.writeText(r),!1}showSourceFile(e){return this._telemetry.goToSourceUsed(),g.getSourceFileViewerService().openSourcePosition(e.sourceFilePosition)}contextMenu(e,t){const r=e;if("number"!=typeof r.id)return null;const s=[{label:i.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>this.showSourceFile(r),disabled:()=>!r.sourceFilePosition,type:i.ContextMenu.MenuItemType.command},{type:i.ContextMenu.MenuItemType.separator},{label:i.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToText(this._queryList,!1);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command},{label:i.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=c.TreeGridUtils.formatTreeGridSelectedToMarkdown(this._queryList,!1);navigator.clipboard.writeText(e)},type:i.ContextMenu.MenuItemType.command}];return i.ContextMenu.create(s)}computeOverlay(){return this._queryList.dataLoadStatus()===n.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._queryList.dataLoadStatus()===n.DataLoadEvent.DataLoadCompleted&&0===this._queryList.treeAsArray().length?{name:"MessageView",data:i.Resources.getString("NoDataMessage")}:null}createSessionLoadedEvent(e){let t=0,r=0,i=0,s=0;const o={};e.forEach((e=>{"Microsoft.EntityFrameworkCore"===e.querySource?t++:"SqlClientDiagnosticListener"===e.querySource&&r++,null!==o[e.database]&&void 0!==o[e.database]||(o[e.database]=1,e.isSQLite&&i++),e.isBroken()&&s++})),this._telemetry.sessionLoaded(t,r,Object.keys(o).length,i,s)}}let S;t.QueryListViewModel=y,(new I.DatabaseMarshaler).getDoubleClickTimeMs().then((e=>{l.Init(e),S=new y})),t.getQueryListViewModel=function(){return S}}.apply(t,i),void 0===s||(e.exports=s)},505:(e,t,r)=>{var i,s;i=[r,t,r(120)],s=function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.QueryListColumnSettingsProvider=void 0,t.QueryListColumnSettingsProvider=class{constructor(){this._marshaler=new r.DatabaseMarshaler}getColumnSettings(){return this._marshaler.getColumnSettings()}onColumnChanged(e){this._marshaler.onColumnChanged(e)}}}.apply(t,i),void 0===s||(e.exports=s)},398:(e,t,r)=>{var i,s;i=[r,t,r(28),r(952),r(405),r(881),r(117)],s=function(e,t,r,i,s,o,a){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.QueryListDAO=void 0;class n{constructor(e,t){this._dataWarehouse=e,this._timeFilter=r.observable(t)}get timeFilter(){return this._timeFilter}get defaultSortColumnId(){return"startTime"}getRoots(e,t,r){const o={timeDomain:this._timeFilter(),customDomain:{view:"QueryList"}};return this._dataWarehouse.getFilteredData(o,i.DatabaseAnalyzerId(),r).then((e=>(r?.throwIfCancellationRequested(),this._currentResult&&this._currentResult.dispose(),this._currentResult=e,this._currentResult?this._currentResult.getResult({task:"getRoots"},r):[]))).then((e=>e.map((e=>new s.QueryRowViewModel(e)))))}expand(e,t,r){return e.expand(this._currentResult,t,r)}search(e,t,r,i,s,o,a){throw new Error("Method not implemented.")}sort(e,t,r){return this._currentResult?this._currentResult.getResult({task:"sortColumn",sortInfo:t},r).then((()=>{r?.throwIfCancellationRequested();const i=n.SortFunc[t.columnId](t.direction),s=e=>{e.children&&(e.children.sort(i),e.children().forEach(s))};return"startTime"===t.columnId||"query"===t.columnId||"duration"===t.columnId||"database"===t.columnId||"connectionStr"===t.columnId||"querySource"===t.columnId||"recordsAffected"===t.columnId||"readCount"===t.columnId?(e.sort(i),e.forEach(s),Promise.resolve(e)):(a.Assert.fail("Unknown sort column: ${sortInfo.columnId}"),Promise.resolve(e))})):Promise.resolve(e)}}t.QueryListDAO=n,n.SortFunc={startTime:e=>o.SortFunctions.numericSort("startTime",e),query:e=>o.SortFunctions.stringSort("query",e),duration:e=>o.SortFunctions.numericSort("duration",e),recordsAffected:e=>o.SortFunctions.numericSort("recordsAffected",e),readCount:e=>o.SortFunctions.numericSort("readCount",e),database:e=>o.SortFunctions.stringSort("database",e),connectionStr:e=>o.SortFunctions.stringSort("connectionStr",e),querySource:e=>o.SortFunctions.stringSort("querySource",e)}}.apply(t,i),void 0===s||(e.exports=s)},405:(e,t,r)=>{var i,s;i=[r,t,r(226),r(28),r(120),r(325)],s=function(e,t,r,i,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.QueryRowViewModel=void 0;class o{constructor(e,t,r=0){this._selected=i.observable(!1),this._expanded=i.observable(!1),this._children=i.observableArray([]),this._marshaler=new s.DatabaseMarshaler,this._haveLoaded=!1,this._parent=t,this._dto=e,this._depth=r}get query(){return this._dto.q?this._dto.q:this._dto.tt?this._dto.tt:r.Resources.getString("UnknownDataLabel")}get durationDisplay(){return-1===this._dto.d?r.Resources.getString("UnknownDataLabel"):this._dto.d.toFixed(3)}get duration(){return this._dto.d}get database(){return this._dto.db?this._dto.db:r.Resources.getString("UnknownDataLabel")}get connectionStr(){return this._dto.cn?this._dto.cn:r.Resources.getString("UnknownDataLabel")}get querySource(){return this._dto.qs?this._dto.qs:r.Resources.getString("UnknownDataLabel")}get isSQLite(){return this._dto.sl}get startTime(){return this._dto.s/1e9}get endTime(){return this._dto.e/1e6}get sourceFilePosition(){return this._dto.sfp}get recordsAffected(){return this._dto.ra}get recordsAffectedDisplay(){return-1===this._dto.ra?r.Resources.getString("UnknownDataLabel"):this._dto.ra.toString()}get readCount(){return this._dto.rc}get readCountDisplay(){return-1===this._dto.rc?r.Resources.getString("UnknownDataLabel"):this._dto.rc.toString()}get isPartOfTransaction(){return!this._parent}isBroken(){return!this._dto.tt&&!this._dto.q||-1===this._dto.d||!this._dto.db||!this._dto.cn||!this._dto.qs||-1===this._dto.s||-1===this._dto.e}get templateName(){return"QueryRowView"}get id(){return this._dto.id}get depth(){return this._depth}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return!this._dto.c||this._dto.c.length>0}get children(){return this._children}invoke(){this._marshaler.updateGraphHighlight(this.id,this._dto.s,this._dto.e)}expand(e,t,r){let i=Promise.resolve(void 0);return this._haveLoaded||(this._haveLoaded=!0,i=e.getResult({task:"expand",transactionId:this._dto.id},r).then((e=>{const t=e.map((e=>new o(e,this,this.depth+1)));this.children(t)}))),this._expanded(!this._expanded()),i}}t.QueryRowViewModel=o}.apply(t,i),void 0===s||(e.exports=s)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=r},28:e=>{"use strict";e.exports=i},226:e=>{"use strict";e.exports=s}},a={},function e(t){var r=a[t];if(void 0!==r)return r.exports;var i=a[t]={exports:{}};return o[t].call(i.exports,i,i.exports,e),i.exports}(371);var o,a}));
// SIG // Begin signature block
// SIG // MIIoQwYJKoZIhvcNAQcCoIIoNDCCKDACAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // Hw9Z/TqsUY94ecNerzu6zMntE04Q4tXKNTC4tLlFWLGg
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xgholMIIaIQIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCBereM6/SoEV6Buof2NhiiESgLnC7T3xSjX
// SIG // Yi15uW7yCDBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBABPIZfRH
// SIG // yDtU3mHnR5NgQnJO2rc9qGKdS3deRUMG5e3ljSZ195AY
// SIG // 1pI+XhLw2Hr3Wb1D2/0Ev9kmqFuAciVg9XZgKnmV+5YZ
// SIG // mHvghZEME8yrRpt2QWiCqTt2kxCIukLE4cDMN1aaWYlf
// SIG // 9onKvahtEWqF/4ibeQqVxCXGSqfDf0EIH2zVy/ZCY9gC
// SIG // 1cQMSAbVBftDMUarxRRbBMoZoXngcocyX9/4mlwm025u
// SIG // mULUDA+wkUhrrQxF6jsC8xOhe8dJl7txjH4V07Ujajo7
// SIG // GcPifuA4FYLOhIVKFtjhLtk+xKsi3kt5HlhIQnPmoxDF
// SIG // N/va0roYG2xwhgGFP751KheVU1OhghevMIIXqwYKKwYB
// SIG // BAGCNwMDATGCF5swgheXBgkqhkiG9w0BBwKggheIMIIX
// SIG // hAIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBWQYLKoZIhvcN
// SIG // AQkQAQSgggFIBIIBRDCCAUACAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgebDkhtgcxQiD9YzJVHrT
// SIG // sajzDB5ymmopkITr0HEZp9ICBmhTGUyz6RgSMjAyNTA2
// SIG // MzAxNDUwMDMuNDlaMASAAgH0oIHZpIHWMIHTMQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQg
// SIG // SXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjo1NTFBLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaCCEf4wggcoMIIFEKADAgECAhMzAAACAdFF
// SIG // WZgQzEJPAAEAAAIBMA0GCSqGSIb3DQEBCwUAMHwxCzAJ
// SIG // BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
// SIG // DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
// SIG // dCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI0MDcyNTE4
// SIG // MzEyMloXDTI1MTAyMjE4MzEyMlowgdMxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVs
// SIG // YW5kIE9wZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMe
// SIG // blNoaWVsZCBUU1MgRVNOOjU1MUEtMDVFMC1EOTQ3MSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
// SIG // AgEAtWrf+HzDu7sk50y5YHheCIJG0uxRSFFcHNek+Td9
// SIG // ZmyJj20EEjaU8JDJu5pWc4pPAsBI38NEAJ1b+KBnlStq
// SIG // U8uvXF4qnEShDdi8nPsZZQsTZDKWAgUM2iZTOiWIuZcF
// SIG // s5ZC8/+GlrVLM5h1Y9nfMh5B4DnUQOXMremAT9MkvUhg
// SIG // 3uaYgmqLlmYyODmba4lXZBu104SLAFsXOfl/TLhpToT4
// SIG // 6y7lI9sbI9uq3/Aerh3aPi2knHvEEazilXeooXNLCwdu
// SIG // +Is6o8kQLouUn3KwUQm0b7aUtsv1X/OgPmsOJi6yN3LY
// SIG // WyHISvrNuIrJ4iYNgHdBBumQYK8LjZmQaTKFacxhmXJ0
// SIG // q2gzaIfxF2yIwM+V9sQqkHkg/Q+iSDNpMr6mr/OwknOE
// SIG // IjI0g6ZMOymivpChzDNoPz9hkK3gVHZKW7NV8+UBXN4G
// SIG // 0aBX69fKUbxBBLyk2cC+PhOoUjkl6UC8/c0huqj5xX8m
// SIG // +YVIk81e7t6I+V/E4yXReeZgr0FhYqNpvTjGcaO2WrkP
// SIG // 5XmsYS7IvMPIf4DCyIJUZaqoBMToAJJHGRe+DPqCHg6b
// SIG // mGPm97MrOWv16/Co6S9cQDkXp9vMSSRQWXy4KtJhZfmu
// SIG // Dz2vr1jw4NeixwuIDGw1mtV/TdSI+vpLJfUiLl/b9w/t
// SIG // JB92BALQT8e1YH8NphdOo1xCwkcCAwEAAaOCAUkwggFF
// SIG // MB0GA1UdDgQWBBSwcq9blqLoPPiVrym9mFmFWbyyUjAf
// SIG // BgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
// SIG // BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
// SIG // c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBU
// SIG // aW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYI
// SIG // KwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
// SIG // Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEw
// SIG // KDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQM
// SIG // MAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAOjQAyz0cVztTFGqXX5JLRxFK
// SIG // /O/oMe55uDqEC8Vd1gbcM28KBUPgvUIPXm/vdDN2IVBk
// SIG // WHmwCp4AIcy4dZtkuUmd0fnu6aT9Mvo1ndsLp2YJcMoF
// SIG // LEt3TtriLaO+i4Grv0ZULtWXUPAW/Mn5Scjgn0xZduGP
// SIG // BD/Xs3J7+get9+8ZvBipsg/N7poimYOVsHxLcem7V5Xd
// SIG // MNsytTm/uComhM/wgR5KlDYTVNAXBxcSKMeJaiD3V1+H
// SIG // hNkVliMl5VOP+nw5xWF55u9h6eF2G7eBPqT+qSFQ+rQC
// SIG // QdIrN0yG1QN9PJroguK+FJQJdQzdfD3RWVsciBygbYaZ
// SIG // lT1cGJI1IyQ74DQ0UBdTpfeGsyrEQ9PI8QyqVLqb2q7L
// SIG // tI6DJMNphYu+jr//0spr1UVvyDPtuRnbGQRNi1COwJcj
// SIG // 9OYmlkFgKNeCfbDT7U3uEOvWomekX60Y/m5utRcUPVeA
// SIG // PdhkB+DxDaev3J1ywDNdyu911nAVPgRkyKgMK3USLG37
// SIG // EdlatDk8FyuCrx4tiHyqHO3wE6xPw32Q8e/vmuQPoBZu
// SIG // X3qUeoFIsyZEenHq2ScMunhcqW32SUVAi5oZ4Z3nf7dA
// SIG // gNau21NEPwgW+2wkrNqDg7Hp8yHyoOKbgEBu6REQbvSf
// SIG // Z5Kh4PV+S2gxf2uq6GoYDnlqABOMYwz309ISi0bPMh8w
// SIG // ggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAV
// SIG // MA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0
// SIG // aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAx
// SIG // ODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7V
// SIG // gtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
// SIG // ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKD
// SIG // RLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gm
// SIG // U3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36M
// SIG // EBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+y
// SIG // OSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoF
// SIG // VZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJi
// SIG // ss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGa
// SIG // RnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+Autuqfjbs
// SIG // Nkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afo
// SIG // mXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9
// SIG // ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
// SIG // i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
// SIG // 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV
// SIG // 2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0C
// SIG // AwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEw
// SIG // IwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
// SIG // LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnp
// SIG // cjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8G
// SIG // CCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYD
// SIG // VR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9
// SIG // lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoG
// SIG // CCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcN
// SIG // AQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pc
// SIG // FLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHk
// SIG // wo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
// SIG // vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4
// SIG // U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2
// SIG // EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8Atq
// SIG // gcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mj
// SIG // dAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZM
// SIG // cm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQE
// SIG // cb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2f
// SIG // pCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBM
// SIG // drVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L
// SIG // +DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJ
// SIG // C4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
// SIG // 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
// SIG // 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDWTCC
// SIG // AkECAQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBP
// SIG // cGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGll
// SIG // bGQgVFNTIEVTTjo1NTFBLTA1RTAtRDk0NzElMCMGA1UE
// SIG // AxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaIj
// SIG // CgEBMAcGBSsOAwIaAxUA1+26cR/yH100DiNFGWhuAv2r
// SIG // YBqggYMwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UE
// SIG // CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYw
// SIG // JAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0Eg
// SIG // MjAxMDANBgkqhkiG9w0BAQsFAAIFAOwMwEAwIhgPMjAy
// SIG // NTA2MzAwNzUwMjRaGA8yMDI1MDcwMTA3NTAyNFowdzA9
// SIG // BgorBgEEAYRZCgQBMS8wLTAKAgUA7AzAQAIBADAKAgEA
// SIG // AgIApwIB/zAHAgEAAgISuzAKAgUA7A4RwAIBADA2Bgor
// SIG // BgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIB
// SIG // AAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUA
// SIG // A4IBAQBK0JdgLT48/Sx6TZfhgJ0Eki/EWvMmGf77AA8S
// SIG // 4fHQsX/oeOSWDcWSOQOjzqoZo93K95oqDGkHUxIR8O0b
// SIG // Y+7LJfI7siqc+esb3CSbNlj9V1EdmL8qJTcaTp+ZOh5g
// SIG // RcZVT1fKQJC3BWtSaWJQDwS1m0HzVEUP+XnlCuAq6yad
// SIG // LUky/IQ4u068U333QeeYaCGXttMqwYrbyJfjpM9aHJyV
// SIG // Al7UGRiN47EOWWbstXTJS/BwqqJlOv8syaY9K2ONHpVx
// SIG // XdDlaJf0EeWNaCGtp1CuEd+jH8j7RBuy6bu+ahB/2BFJ
// SIG // 9lzjoNixZJZIrcdrU53OyOZFVCWYNNMYPXl1M5u8MYIE
// SIG // DTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEm
// SIG // MCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // IDIwMTACEzMAAAIB0UVZmBDMQk8AAQAAAgEwDQYJYIZI
// SIG // AWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG
// SIG // 9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgmBPcqcJqLKvR
// SIG // zLrtwgdph4mmhTEFTlVEs0EfX3UvkAgwgfoGCyqGSIb3
// SIG // DQEJEAIvMYHqMIHnMIHkMIG9BCBYa7I6TJQRcmx0HaST
// SIG // WZdJgowdrl9+Zrr0pIdqHtc4IzCBmDCBgKR+MHwxCzAJ
// SIG // BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
// SIG // DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
// SIG // dCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAACAdFFWZgQ
// SIG // zEJPAAEAAAIBMCIEIBvqXpUAAr3+L75psXwjQ0eYKe7a
// SIG // 2rLykZ1qynNx5kxZMA0GCSqGSIb3DQEBCwUABIICAEUN
// SIG // byBM3f5ml25rUpiITn8nVDs+TX+3nHXlwJcyq2zvkdDe
// SIG // Ouuj97L+GYTSBBkabacpZurksbD49V9sE82p+2DKkVjZ
// SIG // m/eaEM1+ZBJ1tvdTlkW1gKzN0OHA9dkbVGeU1Bf71OyV
// SIG // QCX+0PhjobBOiCPnyqqjnIoPOpRHzMBXoLM4IJ6VrPAq
// SIG // 6gaUckFLijE5mA7mrrIrFlK/bjBBRNQdR1W3VguNPsT8
// SIG // 06CqnwUP3NKjcMl5NXIDJRqRpZc9tg1Ff7FByeeem9B5
// SIG // DNxnf4jFKivqMizU9cT1rI0ls95kcZT4tm0MNocBXIxx
// SIG // wV137h0vpjOyr1+nXKiFGReUg7wX4J74r6+f6mdnXkuB
// SIG // oD38obT+zLUGvkxHYCwXYWyG8WgH5JVevRE4ZZAbh2yL
// SIG // 3hUHgA+FZIQiPJbzBu+669Ygj7DP/C+n9mlKNysNUjSg
// SIG // 1mCN226+OYNzDX1YCX8ypo3k+OIIjDpff/pUqwa/JlNc
// SIG // nEQVi3T6hzaE6Z8Z/NAEq72oMKmF1WmJ3brPguN1wRF3
// SIG // O/H9H+AUlC6CBglXvWXXByhJzqxHflPjgsZDR8JlhDba
// SIG // 7OeXVDydulZMhSoqphhX4Lk27JXNkoW6CJaTxErUkbLK
// SIG // /7jZapi7Ufcj1VO3wZToR/Sajf0cjvHuYLEU92ewpkIJ
// SIG // Fpn5b/msmaptK6mKfbtV
// SIG // End signature block
