define("databaseSwimlane",["diagnosticsHub","diagnosticsHub-swimlanes","plugin-vs-v2"],((e,t,i)=>{return a={989:(e,t,i)=>{var a,r;a=[i,t,i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(560),i(7),i(952)],r=function(e,t,i,a,r,n,s,h,o,l,g,d,u,c){"use strict";function m(e,t,m,p,_,v){const b=new d.SwimlaneConfiguration(e,_,p);b.header.isBodyExpanded=t;const C=b.graph,T=new i.LocalizedUnitConverter(C.jsonConfig.Units,C.resources),E=[],w=new h.CustomCounterDataSeries({CounterId:"",AnalyzerId:c.DatabaseAnalyzerId()},b.graph.timeRange,!1,b.graph.resources.DatabaseQueriesCountSeries,"",new r.ChartColorScheme("rgb(118, 174, 200)","rgba(118, 174, 200, 0.65)"),T);E.push(w);const S=new u.HighlightDataSeries(w,b.graph.timeRange);E.push(S);const y=new s.MultiSeriesGraph(b.graph,E);y.container.setAttribute("aria-label",e.Title);const D=new o.Scale(b.graph.scale,a.ScaleType.Left,T),f=new o.Scale(b.graph.scale,a.ScaleType.Right,T);y.scaleChangedEvent.addEventListener(D.onScaleChanged.bind(D)),y.scaleChangedEvent.addEventListener(f.onScaleChanged.bind(f)),b.header.unit=b.graph.unit;const H=new g.SwimlaneBase(b.header,b.graph.height,_,v);return y.scaleChangedEvent.addEventListener(H.onScaleChanged.bind(H)),H.addMainRegionControl(new l.SelectionOverlay(y,_,v,b.id)),H.addMainRegionControl(new n.GridLineRenderer(_)),H.addLeftRegionControl(D),H.addRightRegionControl(f),H}Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseSwimlaneFactory=void 0,t.DatabaseSwimlaneFactory=m,window.DatabaseSwimlaneFactory=m}.apply(t,a),void 0===r||(e.exports=r)},7:(e,t,i)=>{var a,r;a=[i,t,i(560),i(560),i(560),i(117),i(117),i(120)],r=function(e,t,i,a,r,n,s,h){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.HighlightDataSeries=void 0,t.HighlightDataSeries=class{constructor(e,t){this._timestamps=[],this._queryId=-1,this._startTime=-1,this._endTime=-1,this._onHighlightChangedHandler=this.onHighlightChanged.bind(this),this._newDataEvent=new n.AggregatedEvent,this._marshaler=new h.DatabaseMarshaler,this._databaseCounterDataSeries=e,this._currentTimespan=t,this._colorScheme=new a.ChartColorScheme("#903F8B","#903F8B"),this._marker=document.createElement("div"),this._marker.style.backgroundColor=this._colorScheme.lineColor,this._marker.style.width="1px",this._marker.style.height="100%",this._marshaler.graphHighlightEvent.addEventListener(this._onHighlightChangedHandler)}onHighlightChanged(e){null===e?(this._queryId=-1,this._startTime=-1,this._endTime=-1):(this._queryId=e.queryId,this._startTime=e.startTime,this._endTime=e.endTime,-1!==this._queryId&&-1!==this._startTime&&-1!==this._endTime?(this._timestamps.push(s.BigNumber.convertFromNumber(this._startTime)),this._timestamps.push(s.BigNumber.convertFromNumber(this._endTime))):this._timestamps=[]),this.requestUpdate()}requestUpdate(){this._newDataEvent.invokeEvent(this)}get minValue(){return Number.NaN}get maxValue(){return Number.NaN}get tooltip(){return""}get title(){return""}get marker(){return this._marker}draw(e,t){if(this._timestamps.length<2||t.gridX.elapsed.equals(s.BigNumber.zero)||t.chartRect.width<=0)return;e.save(),e.lineWidth=1,e.fillStyle=this._colorScheme.lineFillColor,e.strokeStyle=this._colorScheme.lineColor;const a=e=>r.Utilities.convertToPixel(e,t.gridX,t.chartRect.width,!1),n=e=>t.chartRect.height-r.Utilities.scaleToRange(e,t.gridY.min,t.gridY.max,0,t.chartRect.height),h=this._databaseCounterDataSeries.getPointAtTimestamp(this._timestamps[0],i.PointToFind.GreaterThanOrEqual),o=this._databaseCounterDataSeries.getPointAtTimestamp(this._timestamps[1],i.PointToFind.LessThanOrEqual);if(null===h||null===o)return;const l=a(h.timestamp);let g=a(o.timestamp);const d=g-l,u=d<1?t.gridY.max:n(h.value),c=d<1?t.gridY.max:n(o.value);g=d<1?g+1:g,e.beginPath(),e.moveTo(l,u),e.lineTo(g,c),e.stroke(),e.lineTo(g,n(t.gridY.min)),e.lineTo(l,t.chartRect.height),e.closePath(),e.fill(),e.closePath(),e.restore()}get newDataEvent(){return this._newDataEvent}dispose(){this._marshaler.graphHighlightEvent.removeEventListener(this._onHighlightChangedHandler),this._newDataEvent.dispose()}onViewportChanged(e){this._currentTimespan=e,this.requestUpdate()}getPointAtTimestamp(e,t=i.PointToFind.Nearest){if(0===this._timestamps.length)return null;const a=this.getOccurrencePointIndex(this._timestamps,e,0,this._timestamps.length-1,t);return{timestamp:this._timestamps[a],tooltip:"",value:Number.NaN,color:this._colorScheme}}getOccurrencePointIndex(e,t,a,n,h){const o=(e,t)=>t.greaterOrEqual(e);switch(h){case i.PointToFind.LessThanOrEqual:return r.Utilities.findLessThan(e,t,o,a,n);case i.PointToFind.GreaterThanOrEqual:return r.Utilities.findGreaterThan(e,t,o,a,n);case i.PointToFind.Nearest:default:{const i=r.Utilities.findLessThan(e,t,o),a=Math.min(i+1,e.length-1),n=s.BigNumber.subtract(t,e[i]),h=s.BigNumber.subtract(e[a],t);return n.greater(h)?a:i}}}}}.apply(t,a),void 0===r||(e.exports=r)},952:(e,t,i)=>{var a;a=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseAnalyzerId=t.QueryListDetailsViewId=void 0,t.QueryListDetailsViewId=function(){return"11197EBE-BE05-4A13-BBB9-C482C634CDEE"},t.DatabaseAnalyzerId=function(){return"4EF1311E-9AD5-4A55-B683-1CC2191E4346"}}.apply(t,[i,t]),void 0===a||(e.exports=a)},120:(e,t,i)=>{var a,r;a=[i,t,i(226),i(117)],r=function(e,t,i,a){"use strict";let r;Object.defineProperty(t,"__esModule",{value:!0}),t.DatabaseMarshaler=void 0,t.DatabaseMarshaler=class{constructor(){r||(r=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.Database.DatabaseMarshaler",{},!0)),this._graphHighlightEvent=new a.ObservableEvent(r,"GraphHighlightChangedEvent")}getDoubleClickTimeMs(){return r._call("getDoubleClickTimeMs")}getColumnSettings(){return r._call("getColumnSettings")}onColumnChanged(e){return r._call("onColumnChanged",e)}updateGraphHighlight(e,t,i){return r._call("raiseGraphHighlightChangedEvent",e,t,i)}clearGraphHighlight(){return r._call("clearGraphHighlight")}get graphHighlightEvent(){return this._graphHighlightEvent}}}.apply(t,a),void 0===r||(e.exports=r)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},226:e=>{"use strict";e.exports=i}},r={},function e(t){var i=r[t];if(void 0!==i)return i.exports;var n=r[t]={exports:{}};return a[t](n,n.exports,e),n.exports}(989);var a,r}));
// SIG // Begin signature block
// SIG // MIIoTwYJKoZIhvcNAQcCoIIoQDCCKDwCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // LRY1ZEOyAUzBhNmBcJnyBWl5E9cooFAtGY9pUsafYOKg
// SIG // gg2FMIIGAzCCA+ugAwIBAgITMwAABAO91ZVdDzsYrQAA
// SIG // AAAEAzANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExM1oX
// SIG // DTI1MDkxMTIwMTExM1owdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // n3RnXcCDp20WFMoNNzt4s9fV12T5roRJlv+bshDfvJoM
// SIG // ZfhyRnixgUfGAbrRlS1St/EcXFXD2MhRkF3CnMYIoeMO
// SIG // MuMyYtxr2sC2B5bDRMUMM/r9I4GP2nowUthCWKFIS1RP
// SIG // lM0YoVfKKMaH7bJii29sW+waBUulAKN2c+Gn5znaiOxR
// SIG // qIu4OL8f9DCHYpME5+Teek3SL95sH5GQhZq7CqTdM0fB
// SIG // w/FmLLx98SpBu7v8XapoTz6jJpyNozhcP/59mi/Fu4tT
// SIG // 2rI2vD50Vx/0GlR9DNZ2py/iyPU7DG/3p1n1zluuRp3u
// SIG // XKjDfVKH7xDbXcMBJid22a3CPbuC2QJLowIDAQABo4IB
// SIG // gjCCAX4wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFOpuKgJKc+OuNYitoqxfHlrE
// SIG // gXAZMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQLEyRNaWNy
// SIG // b3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQx
// SIG // FjAUBgNVBAUTDTIzMDAxMis1MDI5MjYwHwYDVR0jBBgw
// SIG // FoAUSG5k5VAF04KqFzc3IrVtqMp1ApUwVAYDVR0fBE0w
// SIG // SzBJoEegRYZDaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jcmwvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNybDBhBggrBgEFBQcBAQRVMFMwUQYIKwYB
// SIG // BQUHMAKGRWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvY2VydHMvTWljQ29kU2lnUENBMjAxMV8yMDEx
// SIG // LTA3LTA4LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQBRaP+hOC1+dSKhbqCr1LIvNEMrRiOQ
// SIG // EkPc7D6QWtM+/IbrYiXesNeeCZHCMf3+6xASuDYQ+AyB
// SIG // TX0YlXSOxGnBLOzgEukBxezbfnhUTTk7YB2/TxMUcuBC
// SIG // P45zMM0CVTaJE8btloB6/3wbFrOhvQHCILx41jTd6kUq
// SIG // 4bIBHah3NG0Q1H/FCCwHRGTjAbyiwq5n/pCTxLz5XYCu
// SIG // 4RTvy/ZJnFXuuwZynowyju90muegCToTOwpHgE6yRcTv
// SIG // Ri16LKCr68Ab8p8QINfFvqWoEwJCXn853rlkpp4k7qzw
// SIG // lBNiZ71uw2pbzjQzrRtNbCFQAfmoTtsHFD2tmZvQIg1Q
// SIG // VkzM/V1KCjHL54ItqKm7Ay4WyvqWK0VIEaTbdMtbMWbF
// SIG // zq2hkRfJTNnFr7RJFeVC/k0DNaab+bpwx5FvCUvkJ3z2
// SIG // wfHWVUckZjEOGmP7cecefrF+rHpif/xW4nJUjMUiPsyD
// SIG // btY2Hq3VMLgovj+qe0pkJgpYQzPukPm7RNhbabFNFvq+
// SIG // kXWBX/z/pyuo9qLZfTb697Vi7vll5s/DBjPtfMpyfpWG
// SIG // 0phVnAI+0mM4gH09LCMJUERZMgu9bbCGVIQR7cT5YhlL
// SIG // t+tpSDtC6XtAzq4PJbKZxFjpB5wk+SRJ1gm87olbfEV9
// SIG // SFdO7iL3jWbjgVi1Qs1iYxBmvh4WhLWr48uouzCCB3ow
// SIG // ggVioAMCAQICCmEOkNIAAAAAAAMwDQYJKoZIhvcNAQEL
// SIG // BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
// SIG // aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMT
// SIG // KU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhv
// SIG // cml0eSAyMDExMB4XDTExMDcwODIwNTkwOVoXDTI2MDcw
// SIG // ODIxMDkwOVowfjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEoMCYG
// SIG // A1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0Eg
// SIG // MjAxMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAKvw+nIQHC6t2G6qghBNNLrytlghn0IbKmvpWlCq
// SIG // uAY4GgRJun/DDB7dN2vGEtgL8DjCmQawyDnVARQxQtOJ
// SIG // DXlkh36UYCRsr55JnOloXtLfm1OyCizDr9mpK656Ca/X
// SIG // llnKYBoF6WZ26DJSJhIv56sIUM+zRLdd2MQuA3WraPPL
// SIG // bfM6XKEW9Ea64DhkrG5kNXimoGMPLdNAk/jj3gcN1Vx5
// SIG // pUkp5w2+oBN3vpQ97/vjK1oQH01WKKJ6cuASOrdJXtjt
// SIG // 7UORg9l7snuGG9k+sYxd6IlPhBryoS9Z5JA7La4zWMW3
// SIG // Pv4y07MDPbGyr5I4ftKdgCz1TlaRITUlwzluZH9TupwP
// SIG // rRkjhMv0ugOGjfdf8NBSv4yUh7zAIXQlXxgotswnKDgl
// SIG // mDlKNs98sZKuHCOnqWbsYR9q4ShJnV+I4iVd0yFLPlLE
// SIG // tVc/JAPw0XpbL9Uj43BdD1FGd7P4AOG8rAKCX9vAFbO9
// SIG // G9RVS+c5oQ/pI0m8GLhEfEXkwcNyeuBy5yTfv0aZxe/C
// SIG // HFfbg43sTUkwp6uO3+xbn6/83bBm4sGXgXvt1u1L50kp
// SIG // pxMopqd9Z4DmimJ4X7IvhNdXnFy/dygo8e1twyiPLI9A
// SIG // N0/B4YVEicQJTMXUpUMvdJX3bvh4IFgsE11glZo+TzOE
// SIG // 2rCIF96eTvSWsLxGoGyY0uDWiIwLAgMBAAGjggHtMIIB
// SIG // 6TAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUSG5k
// SIG // 5VAF04KqFzc3IrVtqMp1ApUwGQYJKwYBBAGCNxQCBAwe
// SIG // CgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
// SIG // /wQFMAMBAf8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h
// SIG // 6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvTWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNy
// SIG // bDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
// SIG // dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
// SIG // TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDCB
// SIG // nwYDVR0gBIGXMIGUMIGRBgkrBgEEAYI3LgMwgYMwPwYI
// SIG // KwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2lvcHMvZG9jcy9wcmltYXJ5Y3BzLmh0bTBABggr
// SIG // BgEFBQcCAjA0HjIgHQBMAGUAZwBhAGwAXwBwAG8AbABp
// SIG // AGMAeQBfAHMAdABhAHQAZQBtAGUAbgB0AC4gHTANBgkq
// SIG // hkiG9w0BAQsFAAOCAgEAZ/KGpZjgVHkaLtPYdGcimwuW
// SIG // EeFjkplCln3SeQyQwWVfLiw++MNy0W2D/r4/6ArKO79H
// SIG // qaPzadtjvyI1pZddZYSQfYtGUFXYDJJ80hpLHPM8QotS
// SIG // 0LD9a+M+By4pm+Y9G6XUtR13lDni6WTJRD14eiPzE32m
// SIG // kHSDjfTLJgJGKsKKELukqQUMm+1o+mgulaAqPyprWElj
// SIG // HwlpblqYluSD9MCP80Yr3vw70L01724lruWvJ+3Q3fMO
// SIG // r5kol5hNDj0L8giJ1h/DMhji8MUtzluetEk5CsYKwsat
// SIG // ruWy2dsViFFFWDgycScaf7H0J/jeLDogaZiyWYlobm+n
// SIG // t3TDQAUGpgEqKD6CPxNNZgvAs0314Y9/HG8VfUWnduVA
// SIG // KmWjw11SYobDHWM2l4bf2vP48hahmifhzaWX0O5dY0Hj
// SIG // Wwechz4GdwbRBrF1HxS+YWG18NzGGwS+30HHDiju3mUv
// SIG // 7Jf2oVyW2ADWoUa9WfOXpQlLSBCZgB/QACnFsZulP0V3
// SIG // HjXG0qKin3p6IvpIlR+r+0cjgPWe+L9rt0uX4ut1eBrs
// SIG // 6jeZeRhL/9azI2h15q/6/IvrC4DqaTuv/DDtBEyO3991
// SIG // bWORPdGdVk5Pv4BXIqF4ETIheu9BCrE/+6jMpF3BoYib
// SIG // V3FWTkhFwELJm3ZbCoBIa/15n8G9bW1qyVJzEw16UM0x
// SIG // ghoiMIIaHgIBATCBlTB+MQswCQYDVQQGEwJVUzETMBEG
// SIG // A1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
// SIG // ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5n
// SIG // IFBDQSAyMDExAhMzAAAEA73VlV0POxitAAAAAAQDMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCD8mezkFYM5AW4C
// SIG // QBggYWr/AGwTA3eyjH2ERnhevnRo6TBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBAFEqUghvas1BhL6xu6RjM0pXpc0bKcn9
// SIG // /Y6SDPk6GTqwoXsfsxHnFvEWAJn0dtTISd1emo555GyI
// SIG // hTBNcC95kuShJS8+iJotOqT30nQhfmr2zhgtuy0ZKx8S
// SIG // IlPziPeIZ5iudmoNazLyeE50E3vhagBbB1JgkhHOyc/h
// SIG // o8fOCUDWDIfYoTyrUIpWt2iAeSJQalegpTOd2sQfVw29
// SIG // BopZdFdDbVqD9OXVfBi2zcGonFTpj8T7uObpqLjjBnxX
// SIG // 45R6uadCWYxKYi6dF7WPtG40xIbmCb2ggdvqghyxCpO5
// SIG // gaZy9pMrCQ8+Ql6uJ2IAs9q+XpwiK+csGT0cr7zbCe8m
// SIG // +pChghesMIIXqAYKKwYBBAGCNwMDATGCF5gwgheUBgkq
// SIG // hkiG9w0BBwKggheFMIIXgQIBAzEPMA0GCWCGSAFlAwQC
// SIG // AQUAMIIBWgYLKoZIhvcNAQkQAQSgggFJBIIBRTCCAUEC
// SIG // AQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQg
// SIG // 6a8zgRIqX8nU+6dJ6vrn9RxtIEwMSNSgaHCEb4xqbfUC
// SIG // BmhSyyy6ThgTMjAyNTA2MzAxNDQ4MzYuMzY0WjAEgAIB
// SIG // 9KCB2aSB1jCB0zELMAkGA1UEBhMCVVMxEzARBgNVBAgT
// SIG // Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
// SIG // BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsG
// SIG // A1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9u
// SIG // cyBMaW1pdGVkMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBF
// SIG // U046MkExQS0wNUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jv
// SIG // c29mdCBUaW1lLVN0YW1wIFNlcnZpY2WgghH6MIIHKDCC
// SIG // BRCgAwIBAgITMwAAAfkfZ411q6TxsQABAAAB+TANBgkq
// SIG // hkiG9w0BAQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UE
// SIG // CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYw
// SIG // JAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0Eg
// SIG // MjAxMDAeFw0yNDA3MjUxODMxMDlaFw0yNTEwMjIxODMx
// SIG // MDlaMIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
// SIG // EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExp
// SIG // bWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVTTjoy
// SIG // QTFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0
// SIG // IFRpbWUtU3RhbXAgU2VydmljZTCCAiIwDQYJKoZIhvcN
// SIG // AQEBBQADggIPADCCAgoCggIBALQ9TB98gB1hzVbJQvgg
// SIG // U4/zKXeeSwz7UK4Te1nqhYUXgvcSl0o6G1tWR8x1PFdg
// SIG // TiVImIO3wydgMRlRsqL1LYBmYNvhmrhSpN2Y47C0rKno
// SIG // WCLFEK4F/q/1QE2lvPzjVsupTshmcGacX1dhF+KgIepm
// SIG // 9oWnQLr3W0ZdUCtbXwZUd33XggUBvsm8/SRWeOSzdqbP
// SIG // DXNca+NTfEItylSS2F9ImxGwJJLEeG27Mws72Pr3Uq41
// SIG // sigI0emIGIWgWg8RNigydrEERRRf3oAsSoKIHRd1SCaA
// SIG // hP1rsvTLhIMqXmtR3ou5RRr3S0GR+SaNkEebjfIYjHPG
// SIG // eO0USbiFgjnsiCdWJ0Yoom6VGe9vsKb/C06L9Mh+guR0
// SIG // fw/PgE+L6rT+eyE17A/QzzqG/LY7bHnz3ECXm1DYqsn8
// SIG // ky+Y+fyftnfhjwnFxGKHlmfp67GUn63eQxzOKLwpg95Y
// SIG // n4GJ84zq8uIIUE/3L5nR8Ba+siRqYVvxxvBkHfnAeMO8
// SIG // BqToR1SW8uOJBlSvDM2PbN9g8tUx5yYPKe8tbBBs/wNc
// SIG // vOGbeoCLCE2GnHB4QSqeHDlTa36EVVMdhv9E6+w5N36Q
// SIG // lPLvuaJajz8CoGbOe45fpTq0VbF9QGBJgJ8gshq6kQM6
// SIG // Rl8pNR7zSAaUjTbkwUJOxQb7vmKYugO0tldk4+pc2FlQ
// SIG // b7hhAgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQUie2jupyV
// SIG // ySPXoo80uUJEdkZZ4AAwHwYDVR0jBBgwFoAUn6cVXQBe
// SIG // Yl2D9OXSZacbUzUZ6XIwXwYDVR0fBFgwVjBUoFKgUIZO
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
// SIG // cmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUy
// SIG // MDIwMTAoMSkuY3JsMGwGCCsGAQUFBwEBBGAwXjBcBggr
// SIG // BgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
// SIG // L3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0
// SIG // YW1wJTIwUENBJTIwMjAxMCgxKS5jcnQwDAYDVR0TAQH/
// SIG // BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAOBgNV
// SIG // HQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBAGYg
// SIG // CYBW5H+434cf5pmZZxma6WnvhxqcVsbPCO/b1G/BkKLu
// SIG // dDNZ7O4sBtgnHaF2qu1YKVZDX9bryIaxmKSggV0Pkmid
// SIG // jtAb8LiUe1LIE2ijdI/8n936Rw9JLR/hJBLhl7PQwS8r
// SIG // e9YrrVZMKMPYkJkpOKCCvEvAKzRqUjs3rrvU3SYwY7Gr
// SIG // JriftquU45q4BCsj3t0wKQIqPHHcP29XAQJo7SO7aTWF
// SIG // eT8kSNytTYbg4HxI+ZMpxhf7osz9Tbh0sRf1dZLP9rQh
// SIG // KK4onDOJNTyU0wNEwozW5KZgXLADJcU8wZ1rKpwQrfXf
// SIG // lHfVWtyMPQbOHHK5IAYy7YN72BmGq+teaH2LVPnbqfi7
// SIG // lNHdsAQxBtZ4Ulh2jvrtsukotwGjSDbf6TjClOpeAFtL
// SIG // g1lB9/Thx9xKhR7U7LGV2gzo7ckYG6jBppH/CiN6iFQW
// SIG // Sdl0KZ4RLkW4fgIKZkZ/2uNdA5O1bT4NrguNtliwvB/C
// SIG // FZPxXqIkkuLxaHYZ3BXrSdGSt+sMQGtxYj4AXm0VslbW
// SIG // e+t6gw88Q29Jgehy/RxH02zfuKBwpGWtRypfAdLPEYhQ
// SIG // TH/1u/juxD2fsDB/MHZI2e0m7HXbXUYEQEakfCBT1rq0
// SIG // PrJ+37RIn2qI87ghGoUgHKvOso8EHkzzfWBvW9+EU7q5
// SIG // 5KQ/sDxkwdVnHDKbC5TNMIIHcTCCBVmgAwIBAgITMwAA
// SIG // ABXF52ueAptJmQAAAAAAFTANBgkqhkiG9w0BAQsFADCB
// SIG // iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWlj
// SIG // cm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
// SIG // IDIwMTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgz
// SIG // MjI1WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
// SIG // Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCC
// SIG // AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOTh
// SIG // pkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjKNVf2
// SIG // AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZnhUYj
// SIG // DLWNE893MsAQGOhgfWpSg0S3po5GawcU88V29YZQ3MFE
// SIG // yHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJprx2rrPY2
// SIG // vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxqD89d9P6O
// SIG // U8/W7IVWTe/dvI2k45GPsjksUZzpcGkNyjYtcI4xyDUo
// SIG // veO0hyTD4MmPfrVUj9z6BVWYbWg7mka97aSueik3rMvr
// SIG // g0XnRm7KMtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdb
// SIG // Z2De+JKRHh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZ
// SIG // nkXftnIv231fgLrbqn427DZM9ituqBJR6L8FA6PRc6ZN
// SIG // N3SUHDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEz
// SIG // OUyOArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMY
// SIG // ctenIPDC+hIK12NvDMk2ZItboKaDIV1fMHSRlJTYuVD5
// SIG // C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6
// SIG // bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17a
// SIG // j54WcmnGrnu3tz5q4i6tAgMBAAGjggHdMIIB2TASBgkr
// SIG // BgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQWBBQq
// SIG // p1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cV
// SIG // XQBeYl2D9OXSZacbUzUZ6XIwXAYDVR0gBFUwUzBRBgwr
// SIG // BgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYzaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1Jl
// SIG // cG9zaXRvcnkuaHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMI
// SIG // MBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1Ud
// SIG // DwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQY
// SIG // MBaAFNX2VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRP
// SIG // ME0wS6BJoEeGRWh0dHA6Ly9jcmwubWljcm9zb2Z0LmNv
// SIG // bS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8y
// SIG // MDEwLTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYI
// SIG // KwYBBQUHMAKGPmh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
// SIG // bS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYt
// SIG // MjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3h
// SIG // LB9nATEkW+Geckv8qW/qXBS2Pk5HZHixBpOXPTEztTnX
// SIG // wnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6U03d
// SIG // mLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74py27Y
// SIG // P0h1AdkY3m2CDPVtI1TkeFN1JFe53Z/zjj3G82jfZfak
// SIG // Vqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis9/kpicO8
// SIG // F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4s
// SIG // a3tuPywJeBTpkbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6
// SIG // MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0sHrYUP4KWN1A
// SIG // PMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lU
// SIG // ZNlz138eW0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtq
// SIG // RRFHqfG3rsjoiV5PndLQTHa1V1QJsWkBRH58oWFsc/4K
// SIG // u+xBZj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLB
// SIG // gqJ7Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr
// SIG // 4A245oyZ1uEi6vAnQj0llOZ0dFtq0Z4+7X6gMTN9vMvp
// SIG // e784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQ
// SIG // tB1VM1izoXBm8qGCA1UwggI9AgEBMIIBAaGB2aSB1jCB
// SIG // 0zELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWlj
// SIG // cm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVk
// SIG // MScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046MkExQS0w
// SIG // NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVAKrO
// SIG // Vo1ju81QCpiHHcIaoGb8qelGoIGDMIGApH4wfDELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0
// SIG // IFRpbWUtU3RhbXAgUENBIDIwMTAwDQYJKoZIhvcNAQEL
// SIG // BQACBQDsDRrcMCIYDzIwMjUwNjMwMTQxNzAwWhgPMjAy
// SIG // NTA3MDExNDE3MDBaMHMwOQYKKwYBBAGEWQoEATErMCkw
// SIG // CgIFAOwNGtwCAQAwBgIBAAIBFTAHAgEAAgIRHjAKAgUA
// SIG // 7A5sXAIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEE
// SIG // AYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0G
// SIG // CSqGSIb3DQEBCwUAA4IBAQCJJXwnzGDc5c6EZZfunJ4U
// SIG // G1NutG2FC1fGGt5QIGs33VWRQoveBinJFn7hhBxeGR7v
// SIG // 3dA793biN8pZXy3sxJlPNBI9L9cy4yIeovkBFG6Xkzsz
// SIG // V9g0QzWotyaiU9wV0X2wN/LdjMvS3BhCmoyEAse7zmho
// SIG // iM+VBC66KnRZf0gcTY2KDbwF48LGpGIdiicUUYfG0j4B
// SIG // pLRlrVscQoxKRqe+GE0y1zJliZ7339tdOIgKDyl/j+tN
// SIG // upYfhDJEzBEs8XPdKqP9Xjzjt8l4/e0VPv1q/a+0v7+Y
// SIG // TIV+kkt3QK6QxAaV24s+8hACxF6AYMTEPI5YFu4QoWFD
// SIG // L9nsOluhvYOQMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UE
// SIG // BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
// SIG // BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
// SIG // b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
// SIG // bWUtU3RhbXAgUENBIDIwMTACEzMAAAH5H2eNdauk8bEA
// SIG // AQAAAfkwDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3
// SIG // DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQx
// SIG // IgQggYd6kRQTRYSeKIYxzXlX9uJKT7sGcIAlm7/SvJdu
// SIG // 9pIwgfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCA5
// SIG // I4zIHvCN+2T66RUOLCZrUEVdoKlKl8VeCO5SbGLYEDCB
// SIG // mDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // AhMzAAAB+R9njXWrpPGxAAEAAAH5MCIEIB8qfJKTGEZ/
// SIG // Zhc8JLKEHPzpf3VNSkA++Ri1z/eBm0INMA0GCSqGSIb3
// SIG // DQEBCwUABIICAB/ggbXoIK7LM4OkTk/o0v5VmnwBTRA+
// SIG // 41TmrRY27lwgtSyrWd0MvW34VZLAtauPWXZ1TizJkuSt
// SIG // YmZodfwjnXioVabwBUlzcEhhRxU9wvyeZkMLMW8bmyvm
// SIG // mxLdXFcURPYYZmU7eKIIRyN/t1Cmj81zTw4kgV0wbdeL
// SIG // 2Z6zYc4VMeLExpfFWPoAA9WtrbI/dbRM1IhjC49X/ZDh
// SIG // zlrdpArq7TtdMaSZbGpK2WCLrqqExHGBBlN6lGFuhGGN
// SIG // DYXoe6d4eLrJ1DVOKVn5ZpQYYztwj3RS7RbyBTNJnuLX
// SIG // Z7MgkwFQZImgFhJ12jd+1wT+ScM8pDGThSCwXXqPqiDI
// SIG // FdPJtXQP7bnt5SUxHqdZXLUu6wUz7o/FWdKU/ntZ0MZh
// SIG // lWQcNU385K687eMq0S72xH6zMmRAZSOIsswMBfPdOER5
// SIG // mbiKA9A0aRmh/fpnt9N8dGl7faI2TwvZ7YksPhnFSrcX
// SIG // 7eXhq0c3dZEuKgigj2bdEoHsQo+gOsEBW+heoPEbmSiT
// SIG // VTPQDQrYfwbMpmWK2/I6ObU/qDcTnVMiumRSAU3FK0Y/
// SIG // 529YaBhqrTQyh8scCbAT2DGRZKYHVmr2OfLRYqKUusSn
// SIG // d1g6GXYen4tIj77i2LBUCfYvGVOIIHb0znBPx4BIFEB1
// SIG // iNxwC71SMFEdW5Ly7T6wwZMmG7dR4WFuxOw/
// SIG // End signature block
