define("fileReadsViewModel",["diagnosticsHub","diagnosticsHub-swimlanes","diagnosticsHub-ui","knockout","plugin-vs-v2"],((e,t,i,r,a)=>{return s={750:e=>{const t=document.createElement("script");t.id="BacktraceRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9ImJhY2t0cmFjZXNOYW1lIj4NCiAgICAgICAgPHNwYW4gZGF0YS1iaW5kPSJyb3dJbmRlbnQ6IGRlcHRoIj4mbmJzcDs8L3NwYW4+DQogICAgICAgIDxkaXYgZGF0YS1iaW5kPSJ0cmVlR3JpZEV4cGFuZGVyOiBleHBhbmRlZCwgc3R5bGU6IHsgdmlzaWJpbGl0eTogZXhwYW5kYWJsZSA/ICd2aXNpYmxlJyA6ICdoaWRkZW4nIH0iPjwvZGl2Pg0KICAgICAgICA8c3BhbiBjbGFzcz0idHJlZUdyaWRDZWxsLWxhYmVsIiBkYXRhLWJpbmQ9InRleHQ6IGxhYmVsIj48L3NwYW4+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBkYXRhLWJpbmQ9ImxvY2FsaXplZE51bWJlcjoge3ZhbHVlOiBvcGVyYXRpb25TaXplS0IsIG9wdGlvbnM6IHttaW5pbXVtRnJhY3Rpb25EaWdpdHM6IDMsIG1heGltdW1GcmFjdGlvbkRpZ2l0czogM319IiBkYXRhLWNvbHVtbmlkPSJiYWNrdHJhY2VzT3BlcmF0aW9uU2l6ZUtCIj48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBvcGVyYXRpb25Db3VudCIgZGF0YS1jb2x1bW5pZD0iYmFja3RyYWNlc09wZXJhdGlvbkNvdW50Ij48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgZGF0YS1iaW5kPSJ0ZXh0OiBtb2R1bGVOYW1lIiBkYXRhLWNvbHVtbmlkPSJiYWNrdHJhY2VzTW9kdWxlTmFtZSI+PC90ZD4NCjwvdHI+"),t.type="text/html",document.head.appendChild(t),e.exports={}},538:e=>{const t=document.createElement("script");t.id="FileReadWriteRowView",t.innerHTML=atob("PHRyIGNsYXNzPSJ0cmVlR3JpZFJvdyIgcm9sZT0icm93IiB0YWJpbmRleD0iLTEiIGRhdGEtYmluZD0iDQogICAgdHJlZUdyaWRSb3dGb2N1czogJHBhcmVudC5mb2N1c2VkUm93KCkgPT09ICRkYXRhLA0KICAgIGNzczogeyBzZWxlY3RlZDogc2VsZWN0ZWQoKSB9LA0KICAgIGF0dHI6IHsgJ2FyaWEtbGV2ZWwnOiBkZXB0aCArIDEgfSI+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ibmFtZSBjb250YWluZXIiIGRhdGEtY29sdW1uaWQ9Im5hbWUiPg0KICAgICAgICA8c3BhbiBkYXRhLWJpbmQ9InJvd0luZGVudDogZGVwdGgiPiZuYnNwOzwvc3Bhbj4NCiAgICAgICAgPGRpdiBkYXRhLWJpbmQ9InRyZWVHcmlkRXhwYW5kZXI6IGV4cGFuZGVkLCBzdHlsZTogeyB2aXNpYmlsaXR5OiBleHBhbmRhYmxlID8gJ3Zpc2libGUnIDogJ2hpZGRlbicgfSI+PC9kaXY+DQogICAgICAgIDxzcGFuIGRhdGEtYmluZD0idGV4dDogbmFtZSI+PC9zcGFuPg0KICAgIDwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0ib3BlcmF0aW9uQ291bnQiIGRhdGEtYmluZD0idGV4dDogb3BlcmF0aW9uQ291bnQiIGRhdGEtY29sdW1uaWQ9Im9wZXJhdGlvbkNvdW50Ij48L3RkPg0KICAgIDx0ZCByb2xlPSJncmlkY2VsbCIgY2xhc3M9Im9wZXJhdGlvblNpemVLQiIgZGF0YS1iaW5kPSJ0ZXh0OiBsb2NhbGl6ZWRPcGVyYXRpb25TaXplS0IiIGRhdGEtY29sdW1uaWQ9Im9wZXJhdGlvblNpemVLQiI+PC90ZD4NCiAgICA8dGQgcm9sZT0iZ3JpZGNlbGwiIGNsYXNzPSJmaWxlU2l6ZUtCIiBkYXRhLWJpbmQ9InRleHQ6IGxvY2FsaXplZEZpbGVTaXplS0IiIGRhdGEtY29sdW1uaWQ9ImZpbGVTaXplS0IiPjwvdGQ+DQogICAgPHRkIHJvbGU9ImdyaWRjZWxsIiBjbGFzcz0iZHVwbGljYXRpb25GYWN0b3IiIGRhdGEtYmluZD0idGV4dDogbG9jYWxpemVkRHVwbGljYXRpb25GYWN0b3IiIGRhdGEtY29sdW1uaWQ9ImR1cGxpY2F0aW9uRmFjdG9yIj48L3RkPg0KPC90cj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},680:e=>{const t=document.createElement("script");t.id="LoadingView",t.innerHTML=atob("PGRpdiBpZD0icHJvZ3Jlc3MtY29udHJvbCI+DQogICAgPHNwYW4gY2xhc3M9Im1lc3NhZ2UiIGRhdGEtYmluZD0ibG9jYWxpemVkVGV4dDogJ0xvYWRpbmdEYXRhTWVzc2FnZSciPjwvc3Bhbj4NCiAgICA8IS0tIGtvIHRlbXBsYXRlOiB7IG5hbWU6ICdJbmRldGVybWluYXRlUHJvZ3Jlc3MnIH0gLS0+PCEtLSAva28gLS0+DQo8L2Rpdj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},833:e=>{const t=document.createElement("script");t.id="MessageView",t.innerHTML=atob("PHNwYW4gdGFiSW5kZXg9IjAiIGRhdGEtYmluZD0idGV4dDogJGRhdGEiPjwvc3Bhbj4="),t.type="text/html",document.head.appendChild(t),e.exports={}},103:e=>{const t=document.createElement("script");t.id="IndeterminateProgress",t.innerHTML=atob("PGRpdiBjbGFzcz0ic3Bpbm5lciIgcm9sZT0icHJvZ3Jlc3NiYXIiIGFyaWEtdmFsdWVub3c9IjAiIGFyaWEtdmFsdWVtaW49IjAiIGFyaWEtdmFsdWVtYXg9IjEwMCIgYXJpYS1saXZlPSJhc3NlcnRpdmUiDQogICAgIGRhdGEtYmluZD0ibG9jYWxpemVkQXJpYUxhYmVsOidPdmVybGF5X1Byb2dyZXNzSW5kZXRlcm1pbmF0ZUFyaWFMYWJlbCciPg0KICAgIDxkaXYgY2xhc3M9ImJhcjEiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjIiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjMiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjQiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjUiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjYiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjciPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjgiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjkiPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImJhcjEwIj48L2Rpdj4NCjwvZGl2Pg=="),t.type="text/html",document.head.appendChild(t),e.exports={}},701:(e,t,i)=>{var r,a;r=[i,t,i(952),i(28),i(881),i(881),i(117),i(117),i(453)],a=function(e,t,i,r,a,s,o,n,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BacktraceDAO=void 0;class l{constructor(e,t,i,s){this._dataLoadStatus=r.observable(a.DataLoadEvent.DataLoadCompleted),this._currentFileId=-1,this._currentProcessId=-1,this._currentPid=-1,this._currentSelectedFileName=r.observable(""),this._logger=o.getLogger("BacktraceDAO"),this._automation=n.getAutomationManager(this._logger),this._dataWarehouse=e,this._timeFilter=r.observable(t),this._marshaler=i,this._isReads=s}getRoots(e,t,r){this._dataLoadStatus(a.DataLoadEvent.DataLoadStart),this._currentFileId=e;let s=!1;e===l.NewFilterRequest&&(this._currentResult&&(this._currentResult.dispose(),this._currentResult=null),s=!0,this._currentProcessId=e,this._currentPid=e);let o=Promise.resolve(this._currentResult);return!this._currentResult&&(o=this._marshaler.isNativeCodeFoldingEnabled().then((e=>({timeDomain:this.timeFilter(),customDomain:{view:"Backtrace",FoldNativeFrames:e?"true":"false"}}))).then((e=>this._dataWarehouse.getFilteredData(e,i.FileIOAnalyzerId(),r))),s)?o.then((()=>(this._dataLoadStatus(a.DataLoadEvent.DataLoadCompleted),Promise.resolve([])))):o.then((e=>{r?.throwIfCancellationRequested();const t=this._dataWarehouse.getJmcService().getJmcEnabledState();this._currentResult=e;const i=Promise.resolve(this._currentResult.getResult({task:"getRoots",fileId:this._currentFileId,isReads:this._isReads,processId:this._currentProcessId,pid:this._currentPid},r));return Promise.all([i,t])})).then((e=>{r?.throwIfCancellationRequested();const[i,s]=e,o=i.map((e=>new d.BacktraceRowViewModel(null,this,this._currentFileId,this._currentProcessId,this._currentPid,e,0,s)));return this._dataLoadStatus(a.DataLoadEvent.DataLoadCompleted),1===o.length?this.expand(o[0],t,r).then((()=>o)):Promise.resolve(o)})).then((e=>this.sort(e,t,r)))}get timeFilter(){return this._timeFilter}expand(e,t,i){return e.expand(this._currentResult,t,i)}search(e,t,i,r,a,s,o){throw new Error("Method not implemented.")}sort(e,t,i){const r=l.SortFunc[t.columnId](t.direction),a=e=>{e.children&&(e.children.sort(r),e.children().forEach(a))};return e.sort(r),e.forEach(a),Promise.resolve(e)}get defaultSortColumnId(){return"backtracesOperationSizeKB"}get currentFileId(){return this._currentFileId}get currentPid(){return this._currentPid}set currentPid(e){this._currentPid=e}get currentProcessId(){return this._currentProcessId}set currentProcessId(e){this._currentProcessId=e}get dataLoadStatus(){return this._dataLoadStatus}get currentFileName(){return this._currentSelectedFileName}getSourceInfo(e){return this._currentResult.getResult({task:"getSourceInfo",rowId:e,isReads:this._isReads})}}t.BacktraceDAO=l,l.NewFilterRequest=-1,l.SortFunc={backtracesName:e=>s.SortFunctions.stringSort("name",e),backtracesOperationSizeKB:e=>s.SortFunctions.numericSort("operationSizeKB",e),backtracesOperationCount:e=>s.SortFunctions.numericSort("operationCount",e),backtracesModuleName:e=>s.SortFunctions.stringSort("moduleName",e)}}.apply(t,r),void 0===a||(e.exports=a)},453:(e,t,i)=>{var r,a;r=[i,t,i(28),i(226),i(881),i(558),i(750)],a=function(e,t,i,r,a,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.BacktraceRowViewModel=void 0;class o{constructor(e,t,r,a,s,o,n,d){this._selected=i.observable(!1),this._expanded=i.observable(!1),this._haveLoaded=!1,this._jmcEnabled=!1,this._dto=o,this._depth=n,this._jmcEnabled=d,this._parent=e,this._dao=t,this._fileId=r,this._processId=a,this._pid=s,this._children=i.observableArray([]),this._label=i.pureComputed((()=>this.computeLabel()))}get templateName(){return"BacktraceRowView"}get id(){return this._dto.id}get name(){return this._dto.n}get operationCount(){return this._dto.co}get operationSizeKB(){return s.convertBytesToKB(this._dto.op)}get isReads(){return this._dto.ir}get label(){return this._label}get depth(){return this._depth}get selected(){return this._selected}get children(){return this._children}get expanded(){return this._expanded}invoke(){}get sourceFilePosition(){return this._dto.sfp}set sourceFilePosition(e){this._dto.sfp=e}get AggregationId(){return this._dto.aId}get moduleName(){switch(this._dto.mc){case 0:return r.Resources.getString("UnknownModuleLabel");case 1:return this._dto.mn;default:return r.Resources.getString("MultipleModuleLabel")}}get expandable(){return void 0===this._dto.c||this._children().length>0}computeLabel(){if(this._dto.a===a.AggregateType.BrokenStack)return r.Resources.getString("UnwalkableStackLabel");if(!this._jmcEnabled)switch(this._dto.a){case a.AggregateType.Native:return r.Resources.getString("FoldedNativeLabel");case a.AggregateType.AsyncMethod:return r.Resources.getString("AsyncMethodLabel");default:return""}if(this._dto.n)switch(this._dto.j){case a.JmcState.SystemCode:return r.Resources.getString("SystemCallLabel");case a.JmcState.LibraryCode:return r.Resources.getString("ExternalCallLabel")}switch(this._dto.a){case a.AggregateType.SystemCode:return r.Resources.getString("SystemCodeLabel");case a.AggregateType.JmcRejected:return r.Resources.getString("ExternalCodeLabel");case a.AggregateType.AsyncMethod:return r.Resources.getString("AsyncMethodLabel");case a.AggregateType.Native:return r.Resources.getString("FoldedNativeLabel");default:return""}}expand(e,t,i){let r=Promise.resolve();return this._haveLoaded||(this._haveLoaded=!0,r=e.getResult({task:"expand",fileId:this._fileId,rowId:this.id,path:this.getIdPath(),isReads:this.isReads,processId:this._processId},i).then((e=>{i?.throwIfCancellationRequested();const r=e.map((e=>new o(this,this._dao,this._fileId,this._processId,this._pid,e,this.depth+1,this._jmcEnabled)));return this._dao.sort(r,t)})).then((r=>(i?.throwIfCancellationRequested(),this.children(r),1===r.length?r[0].expand(e,t,i):Promise.resolve())))),this._expanded(!this._expanded()),r}getIdPath(){if(!this._parent)return[this.id];const e=this._parent.getIdPath();return e.unshift(this.id),e}}t.BacktraceRowViewModel=o}.apply(t,r),void 0===a||(e.exports=a)},118:(e,t,i)=>{var r,a;r=[i,t,i(79)],a=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileIOColumnSettingsProvider=void 0,t.FileIOColumnSettingsProvider=class{constructor(e){this._marshaler=new i.FileIOMarshaler,this._templateName=e}getColumnSettings(){return this._marshaler.getColumnSettings(this._templateName)}onColumnChanged(e){this._marshaler.onColumnChanged(this._templateName,e)}}}.apply(t,r),void 0===a||(e.exports=a)},952:(e,t,i)=>{var r;r=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileIOAnalyzerId=t.FileWritesViewId=t.FileReadsViewId=void 0,t.FileReadsViewId=function(){return"4AA24559-7978-4ECB-B9DE-697514D19709"},t.FileWritesViewId=function(){return"C9350735-F728-4EE7-A5F0-F008F3F82E03"},t.FileIOAnalyzerId=function(){return"C8556299-6B78-4348-848F-C90C46FF567D"}}.apply(t,[i,t]),void 0===r||(e.exports=r)},79:(e,t,i)=>{var r,a;r=[i,t,i(226),i(117)],a=function(e,t,i,r){"use strict";let a;Object.defineProperty(t,"__esModule",{value:!0}),t.FileIOMarshaler=void 0,t.FileIOMarshaler=class{constructor(){a||(a=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.FileIO.FileIOMarshaler",{},!0)),this._updateNativeCodeEvent=new r.ObservableEvent(a,"updateNativeCodeEvent")}getDoubleClickTimeMs(){return a._call("getDoubleClickTimeMs")}isNativeCodeFoldingEnabled(){return a._call("isNativeCodeFoldingEnabled")}setNativeCodeFoldingEnabled(e){return a._call("setNativeCodeFolding",{isEnabled:e})}get onUpdateNativeCodeFolding(){return this._updateNativeCodeEvent}getColumnSettings(e){return a._call("getColumnSettings",e)}onColumnChanged(e,t){return a._call("onColumnChanged",e,t)}}}.apply(t,r),void 0===a||(e.exports=a)},455:(e,t,i)=>{var r,a;r=[i,t,i(226)],a=function(e,t,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileIOTelemetryMarshaler=void 0;let r=null;t.FileIOTelemetryMarshaler=class{constructor(){null===r&&(r=i.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.FileIO.VisualStudio.FileIOTelemetryMarshaler",{},!0))}backtraceComputed(){r._post("backtraceComputed")}contextMenuVisible(){r._post("contextMenuVisible")}sourceFileOpened(){r._post("sourceFileOpened")}}}.apply(t,r),void 0===a||(e.exports=a)},953:(e,t,i)=>{var r,a;r=[i,t,i(28),i(952),i(97),i(881)],a=function(e,t,i,r,a,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileReadWriteDAO=void 0;class o{constructor(e,t,r,a,s){this._roots=i.observableArray([]),this._dataWarehouse=e,this._timeFilter=i.observable(t),this._isReads=r,this._backtrace=a,this._backtraceDao=s,this._isReads?this._viewName="FileReads":this._viewName="FileWrites"}get timeFilter(){return this._timeFilter}get roots(){return this._roots}get defaultSortColumnId(){return"duplicationFactor"}getRoots(e,t,i){const s={timeDomain:this.timeFilter(),customDomain:{view:this._viewName}};return this._dataWarehouse.getFilteredData(s,r.FileIOAnalyzerId()).then((e=>(this._currentResult&&this._currentResult.dispose(),this._currentResult=e,this._currentResult?this._currentResult.getResult({task:"getRoots",isReads:this._isReads}):[]))).then((e=>{e instanceof Array&&this._roots(e.map((e=>new a.FileReadWriteRowViewModel(e,0,this._backtrace,this._backtraceDao))))})).then((()=>1!==this._roots().length||this._roots()[0].expanded()?this.sort(this._roots(),t,i):this.expand(this._roots()[0],t,i).then((()=>this.sort(this._roots(),t,i)))))}expand(e,t,i){return e.expand(this._currentResult,t,i)}search(e,t,i,r,a,s,o){throw new Error("Method not implemented.")}sort(e,t,i){const r=o.SortFunc[t.columnId](t.direction),a=e=>{e.children&&(e.children.sort(r),e.children().forEach(a))};return e.sort(r),e.forEach(a),Promise.resolve(e)}getSourceInfo(e,t,i){return this._currentResult.getResult({task:"getSourceInfo",processId:e,codeAddress:t,timestamp:i})}}t.FileReadWriteDAO=o,o.SortFunc={name:e=>s.SortFunctions.stringSort("name",e),duplicationFactor:e=>s.SortFunctions.numericSort("duplicationFactor",e),operationCount:e=>s.SortFunctions.numericSort("operationCount",e),operationSizeKB:e=>s.SortFunctions.numericSort("operationSizeKB",e),fileSizeKB:e=>s.SortFunctions.numericSort("fileSizeKB",e)}}.apply(t,r),void 0===a||(e.exports=a)},97:(e,t,i)=>{var r,a;r=[i,t,i(226),i(28),i(558),i(455),i(538)],a=function(e,t,i,r,a,s){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.FileReadWriteRowViewModel=void 0;class o{constructor(e,t,i,a){this._selected=r.observable(!1),this._expanded=r.observable(!1),this._children=r.observableArray([]),this._haveLoaded=!1,this._telemetry=new s.FileIOTelemetryMarshaler,this._dto=e,this._depth=t,this._backtrace=i,this._backtraceDao=a}get fileId(){return this._dto.fid}get codeAddress(){return this._dto.ca}get name(){return this._dto.nm?this._dto.nm:i.Resources.getString("UnknownDataLabel")}get operationCount(){return this._dto.co}get operationSizeKB(){return a.convertBytesToKB(this._dto.op)}get localizedOperationSizeKB(){return this.operationSizeKB.toLocaleString(i.Culture.formatRegion,{minimumFractionDigits:3,maximumFractionDigits:3})}get fileSizeKB(){return 0===this._dto.s?null:a.convertBytesToKB(this._dto.s)}get localizedFileSizeKB(){return this.fileSizeKB?this.fileSizeKB.toLocaleString(i.Culture.formatRegion,{minimumFractionDigits:3,maximumFractionDigits:3}):""}get duplicationFactor(){return this.fileSizeKB?this.operationSizeKB/this.fileSizeKB:null}get localizedDuplicationFactor(){return this.duplicationFactor?this.duplicationFactor.toLocaleString(i.Culture.formatRegion,{minimumFractionDigits:3,maximumFractionDigits:3}):""}get isReads(){return this._dto.ir}get processId(){return this._dto.procId}get pid(){return this._dto.pid}get isSizeEstimate(){return this._dto.ie}get timestamp(){return this._dto.ti}get sourceFilePosition(){return this._dto.sfp}set sourceFilePosition(e){this._dto.sfp=e}get templateName(){return"FileReadWriteRowView"}get id(){return this.fileId}get depth(){return this._depth}get selected(){return this._selected}get expanded(){return this._expanded}get expandable(){return this._dto.co>1}get children(){return this._children}invoke(){-1===this.fileId||this.processId===this._backtraceDao.currentProcessId&&this.fileId===this._backtraceDao.currentFileId||(this._backtraceDao.currentProcessId=this.processId,this._backtraceDao.currentPid=this.pid,this._backtrace.onResultChanged(this.id),this._telemetry.backtraceComputed(),this._backtraceDao.currentFileName(this.name))}expand(e,t,i){let r=Promise.resolve(void 0);return this.expandable?(this._haveLoaded||(this._haveLoaded=!0,r=e.getResult({task:"expand",fileId:this.fileId,isReads:this.isReads,processId:this.processId},i).then((e=>{const t=e.map((e=>new o(e,this.depth+1,this._backtrace,this._backtraceDao)));this.children(t)}))),this._expanded(!this._expanded()),r):r}}t.FileReadWriteRowViewModel=o}.apply(t,r),void 0===a||(e.exports=a)},913:(e,t,i)=>{var r,a;r=[i,t,i(28),i(226),i(952),i(117),i(117),i(560),i(881),i(881),i(881),i(881),i(881),i(117),i(117),i(117),i(881),i(953),i(79),i(455),i(701),i(453),i(118),i(680),i(833),i(103)],a=function(e,t,i,r,a,s,o,n,d,l,c,h,u,g,m,p,I,b,_,R,F,v,C){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getFileReadsViewModel=t.FileReadsViewModel=void 0;class S{constructor(){let e;this._marshaler=new _.FileIOMarshaler,this._telemetry=new R.FileIOTelemetryMarshaler,this._logger=s.getLogger("FileReadsViewModel"),this._automation=o.getAutomationManager(this._logger),this._currentOverlay=i.pureComputed((()=>this.computeOverlay())),this._backtraceOverlay=i.pureComputed((()=>this.computeBacktraceOverlay())),this._backtraceFile=i.pureComputed((()=>r.Resources.getString("BacktraceFileDisplay",this._backtraceDao.currentFileName(),this._backtraceDao.currentPid))),g.loadDataWarehouse().then((t=>(e=t,e.getContextService().getGlobalContext()))).then((t=>Promise.all([e.getJmcService().getJmcEnabledState(),t.getTimeDomain(),this._marshaler.isNativeCodeFoldingEnabled()]))).then((t=>{const[s,o,n]=t;this._showJmc=new I.ToggleButtonViewModel(void 0,void 0,"ShowJmc","ShowJmc"),this._showJmc.isChecked(s),this._showJmc.isChecked.subscribe((()=>{e.getJmcService().setJmcEnabledState(this._showJmc.isChecked())})),this._showNative=new I.ToggleButtonViewModel(void 0,void 0,"ShowNative","ShowNative"),this._showNative.isChecked(!n),this._showNative.isChecked.subscribe((()=>{this._marshaler.setNativeCodeFoldingEnabled(!this._showNative.isChecked()),this._backtraceTree.onResultChanged(F.BacktraceDAO.NewFilterRequest)})),this._marshaler.onUpdateNativeCodeFolding.addEventListener((e=>this._showNative.isChecked(!e.isEnabled))),this._backtraceDao=new F.BacktraceDAO(e,o,this._marshaler,!0);const h=r.Resources.getString,u=new c.TreeGridHeaderViewModel([{id:"backtracesName",text:h("FileReadWriteHeaderName"),tooltip:h("FileReadWriteTreeGrid_NameTooltip"),hideable:!1,sortable:l.SortDirection.Asc},{id:"backtracesOperationSizeKB",text:h("FileReadsHeaderKBRead"),tooltip:h("FileReadWriteTreeGrid_DataReadTooltip"),hideable:!0,sortable:l.SortDirection.Desc},{id:"backtracesOperationCount",text:h("FileReadWriteHeaderCount"),tooltip:h("FileReadWriteTreeGrid_ReadCountTooltip"),hideable:!0,sortable:l.SortDirection.Desc},{id:"backtracesModuleName",text:h("HeaderModuleName"),tooltip:h("HeaderModuleNameToolTip"),hideable:!0,sortable:l.SortDirection.Asc}],new C.FileIOColumnSettingsProvider("BacktraceView"),this._backtraceDao.defaultSortColumnId);this._backtraceTree=new d.TreeGridViewModel(this._backtraceDao,u,"BacktraceAriaLabel"),this._fileReadWriteDAO=new b.FileReadWriteDAO(e,o,!0,this._backtraceTree,this._backtraceDao);const g=new c.TreeGridHeaderViewModel([{id:"name",text:h("FileReadWriteHeaderName"),tooltip:h("FileReadWriteTreeGrid_NameTooltip"),hideable:!1,sortable:l.SortDirection.Asc},{id:"duplicationFactor",text:h("FileReadWriteHeaderDuplicationFactor"),tooltip:h("FileReadWriteTreeGrid_ReadDuplicationFactorTooltip"),hideable:!0,sortable:l.SortDirection.Desc},{id:"operationCount",text:h("FileReadWriteHeaderCount"),tooltip:h("FileReadWriteTreeGrid_ReadCountTooltip"),hideable:!0,sortable:l.SortDirection.Desc},{id:"operationSizeKB",text:h("FileReadsHeaderKBRead"),tooltip:h("FileReadWriteTreeGrid_DataReadTooltip"),hideable:!0,sortable:l.SortDirection.Desc},{id:"fileSizeKB",text:h("FileReadWriteHeaderSize"),tooltip:h("FileReadWriteTreeGrid_SizeTooltip"),hideable:!0,sortable:l.SortDirection.Desc}],new C.FileIOColumnSettingsProvider("ReadWriteView"),this._fileReadWriteDAO.defaultSortColumnId);this._fileReads=new d.TreeGridViewModel(this._fileReadWriteDAO,g,"FileReadsAriaLabel");const p=m.getViewEventManager();this._fileReads.onResultChanged(0),p.selectionChanged.addEventListener((e=>{e.isIntermittent||(this._fileReadWriteDAO.timeFilter(e.position),this._backtraceDao.timeFilter(e.position),this._fileReads.onResultChanged(0))})),this._backtraceDao.timeFilter.subscribe((()=>this._backtraceTree.onResultChanged(F.BacktraceDAO.NewFilterRequest))),p.jmcEnabledStateChanged.addEventListener((e=>{this.showJmc.isChecked(e.currEnabledState),this._backtraceTree.onResultChanged(F.BacktraceDAO.NewFilterRequest),this.fileReads.onResultChanged(0),this.fileReads.selectedRows([])})),i.applyBindings(this),p.detailsViewReady.raiseEvent({Id:a.FileReadsViewId()})}))}get fileReads(){return this._fileReads}get backtraceTree(){return this._backtraceTree}get currentOverlay(){return this._currentOverlay}get backtraceOverlay(){return this._backtraceOverlay}get backtraceFile(){return this._backtraceFile}get showJmc(){return this._showJmc}get showNative(){return this._showNative}get showJmcButtonEnabled(){return!0}onKeyDown(e,t){if(!t.ctrlKey||t.keyCode!==n.KeyCodes.C)return!0;const i=h.TreeGridUtils.formatTreeGridSelectedToText(this._fileReads,!1);return navigator.clipboard.writeText(i),!1}onKeyDownBacktrace(e,t){if(!t.ctrlKey||t.keyCode!==n.KeyCodes.C)return!0;const i=h.TreeGridUtils.formatTreeGridSelectedToText(this._backtraceTree);return navigator.clipboard.writeText(i),!1}showSourceFile(e){e instanceof v.BacktraceRowViewModel?this._backtraceDao.getSourceInfo(e.AggregationId).then((t=>{e.sourceFilePosition=t,t?(this._telemetry.sourceFileOpened(),p.getSourceFileViewerService().openSourcePosition(e.sourceFilePosition)):this._automation.getAlertPromise(o.AutomationConstants.DataWarehouseRequestKey,r.Resources.getString("NoSource"))})):this._fileReadWriteDAO.getSourceInfo(e.processId,e.codeAddress,e.timestamp).then((t=>{e.sourceFilePosition=t,t?(this._telemetry.sourceFileOpened(),p.getSourceFileViewerService().openSourcePosition(e.sourceFilePosition)):this._automation.getAlertPromise(o.AutomationConstants.DataWarehouseRequestKey,r.Resources.getString("NoSource"))}))}contextMenu(e,t){this._telemetry.contextMenuVisible();const i=e;if("number"!=typeof i.id)return null;const a=i instanceof v.BacktraceRowViewModel;let s=this._fileReads;a&&(s=this._backtraceTree);const o=a,n=[{label:r.Resources.getString("ContextMenu_GoToSourceFile"),callback:()=>this.showSourceFile(i),disabled:()=>!i.sourceFilePosition,type:r.ContextMenu.MenuItemType.command},{type:r.ContextMenu.MenuItemType.separator},{label:r.Resources.getString("ContextMenu_Copy"),callback:()=>{const e=h.TreeGridUtils.formatTreeGridSelectedToText(s,o);navigator.clipboard.writeText(e)},type:r.ContextMenu.MenuItemType.command},{label:r.Resources.getString("ContextMenu_CopyAsMarkdown"),callback:()=>{const e=h.TreeGridUtils.formatTreeGridSelectedToMarkdown(s,o);navigator.clipboard.writeText(e)},type:r.ContextMenu.MenuItemType.command}];return r.ContextMenu.create(n)}computeOverlay(){return this._fileReads.dataLoadStatus()===l.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._fileReads.dataLoadStatus()===l.DataLoadEvent.DataLoadCompleted&&0===this._fileReads.treeAsArray().length?{name:"MessageView",data:r.Resources.getString("NoDataMessage")}:this._fileReads.dataLoadStatus()===l.DataLoadEvent.DataLoadFailed?{name:"MessageView",data:r.Resources.getString("UnableShowDataMessage")}:null}computeBacktraceOverlay(){return this._backtraceDao.dataLoadStatus()===l.DataLoadEvent.DataLoadStart?{name:"LoadingView"}:this._backtraceDao.dataLoadStatus()===l.DataLoadEvent.DataLoadCompleted&&0===this._backtraceTree.roots().length?-1===this._backtraceDao.currentProcessId?{name:"MessageView",data:r.Resources.getString("SelectFileMessage")}:{name:"MessageView",data:r.Resources.getString("BacktraceNoStacks")}:null}}let w;t.FileReadsViewModel=S,(new _.FileIOMarshaler).getDoubleClickTimeMs().then((e=>{u.Init(e),w=new S})),t.getFileReadsViewModel=function(){return w}}.apply(t,r),void 0===a||(e.exports=a)},558:(e,t,i)=>{var r;r=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.convertBytesToKB=void 0,t.convertBytesToKB=function(e){return e/1024}}.apply(t,[i,t]),void 0===r||(e.exports=r)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},881:e=>{"use strict";e.exports=i},28:e=>{"use strict";e.exports=r},226:e=>{"use strict";e.exports=a}},o={},function e(t){var i=o[t];if(void 0!==i)return i.exports;var r=o[t]={exports:{}};return s[t](r,r.exports,e),r.exports}(913);var s,o}));
// SIG // Begin signature block
// SIG // MIIoKAYJKoZIhvcNAQcCoIIoGTCCKBUCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // huKedoS9FQXWSqd0zqNHAUngSfjiZgDNURS29fq91++g
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghoKMIIaBgIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCDYFAH5BT8gRmU42juFEnA7KI8n0umZ54tm
// SIG // Z40hvo3FaTBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAGHHHKNN
// SIG // Oyi7cMT3M741oM4ukHKxoM8FwCg+0npVRs9a/7R5zP9j
// SIG // Qht938/c1vwcAVIlXDTuZVW8L/edDu1ACB5BfBaeh25+
// SIG // nrgrTR42E7n1+JfN2WG83y2NZMBObboQcU4T7OJ+Jl54
// SIG // XpyJugbE9QAmVDHnUQqXA/yyGg43s5j2wJ04V2HDZn5k
// SIG // Fr0xy2LsAiAUMIghoNDucTeXwSdbibXuJQVKkyEP0RMf
// SIG // h2ch432zQPH10+2HyNmdYtZ7VEZJ6f1Jt52KMReUAWKh
// SIG // O5PgA/2VNVO/nomQWf8Gux15lpmAd2U60sAlQ/+guxyz
// SIG // w+5eLGJ5HqMpClLbb2Ayk0yk4TihgheUMIIXkAYKKwYB
// SIG // BAGCNwMDATGCF4Awghd8BgkqhkiG9w0BBwKgghdtMIIX
// SIG // aQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUgYLKoZIhvcN
// SIG // AQkQAQSgggFBBIIBPTCCATkCAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQgKJQSi75S0zynnM3ON6tf
// SIG // ZfQ3UxVzoTn+NuePJ5nuZY4CBmhK1JmxXBgTMjAyNTA2
// SIG // MzAxNDUyMzkuNTcxWjAEgAIB9KCB0aSBzjCByzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0
// SIG // IEFtZXJpY2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNo
// SIG // aWVsZCBUU1MgRVNOOjkyMDAtMDVFMC1EOTQ3MSUwIwYD
// SIG // VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
// SIG // oIIR6jCCByAwggUIoAMCAQICEzMAAAIJCAfg+VyM5lUA
// SIG // AQAAAgkwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
// SIG // U3RhbXAgUENBIDIwMTAwHhcNMjUwMTMwMTk0MjU1WhcN
// SIG // MjYwNDIyMTk0MjU1WjCByzELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3Bl
// SIG // cmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNO
// SIG // OjkyMDAtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAg8AMIICCgKCAgEAwpRKMPcuDN39Uvc9
// SIG // cbTRBE8Fi9bxIosNKA+0lxHb+LHT9MbFconb+iNq5hJf
// SIG // D2LPS3GY87FjhyO3UJES9vBj9wl3L2NGaup1rB2NkGpg
// SIG // mRSxdiJUR+gR8dkZDe2UQyprOwTqOCBgUZQjJFL/Tff7
// SIG // cDswJKVjbDN2/wUMXMIVYLEKrUPDRD1Lokfhlea3UB1E
// SIG // +KY4oWU5CcK2pYs9GW2KVEx+TpIt3dwacfaoj64geoYT
// SIG // Xxj45dDyKdtw+e/a6VumZj6j0/I9dil+8kmcDbsbNz2L
// SIG // xf8NdxrEV5MyGyMiyhD84/Zc5pqxdsI771K8fQGcOxi0
// SIG // l5NvA59V0n+toW5BblBsDxS6dxG0aiFZgWeNsHM+ZkiC
// SIG // Ast0LP4cIRGIVJ3ZwAYDaQ+WrwCzle7FHyaxw2V1+n/Y
// SIG // IG4yAOo9p4UgEiKpfBeS7CgcNET7Q7st49gj8bU5maM2
// SIG // yyvEzLcQ4jAoMU6X4OYmFL8oVeGqmgy8EQbKAUYTv/oc
// SIG // Mmyp2MF8Snnjq7DsEC52jhOQZhSWFgThc93fPCwSvUEQ
// SIG // YHRB+Qi1Ye8JIDCHofenB+fh9MRL5oOre7s7ZV19kle8
// SIG // XVGD8QN7441dxJFe2m0hw+Rx0GU63dxarA/1TmAAlFQT
// SIG // 68RfpFK2Rl8WCJ2U6a2DGBKulCBtQ0+KQlT/Q3GgixiD
// SIG // mBCdYNMCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBRJi+jR
// SIG // xF045b3wL0DNtXczFpPK0jAfBgNVHSMEGDAWgBSfpxVd
// SIG // AF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQ
// SIG // hk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
// SIG // JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwG
// SIG // CCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
// SIG // Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4G
// SIG // A1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // XF58bzg8JOIf421AbJxZRba0rgQWW+8EmX2uZSkTEzXz
// SIG // ZZmgAuG3e1qNCOYTMbBCVMrqR8IeJA+apEWXMyHNIyAA
// SIG // UENcQ1AWvlk8a6f1AKgte4oxQnj2SmFYzax3/wZo8+xW
// SIG // jiONZMbnkYcCzSHENoJgag0eVuE0tobUSWMmQLO43yZm
// SIG // w7U3FDjIRJdTlpcfxZ73EG6LeVT82lMIk+jYnvJej2Y6
// SIG // ELLsYmrLkgJsSiEHbB5yeUKJKsHcql4tRWQ7RE1b213w
// SIG // 7KH807WuHp9qn+PIcxGcFL25M+bJrfPdJ1QCu5M9nK68
// SIG // zd4aZ3xbn7af61y1k78T0HH1l4hLiFHdhoO3kfELcirS
// SIG // Q1PPjw8BApM6GiY2xgiqsfREoBSc861zcIYV+kXPINhF
// SIG // P/ut5pqlnghf5CThYNnicO2rv2mxEoKtxGs8g9VZS/h2
// SIG // l/jARxs0Jh7bzpt0JeMFUzd1qvF/GwkevKoheaxWrJuE
// SIG // cRes2o2Xkhwv6kud9+v+GjA6rFejvOkZTzwmBiTj7X9j
// SIG // Gyju1ySXi/1EDdHN7oseUTE6OunWwE8T1BRBuT4eDx8x
// SIG // o1GxDuw9+S7hAYohvGK5TETpBpd3wUJfW1m4MPQiFEG8
// SIG // KuXE2hMZXxKTHUqMnSaJVE0A+RCyhs9UyWoU4nXdtMJc
// SIG // IuQZN+lyJs7B+GLNeYl0XwIwggdxMIIFWaADAgECAhMz
// SIG // AAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUA
// SIG // MIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylN
// SIG // aWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
// SIG // dHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAx
// SIG // ODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
// SIG // YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
// SIG // VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
// SIG // BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // 5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1
// SIG // V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeF
// SIG // RiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
// SIG // wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus
// SIG // 9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130
// SIG // /o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHI
// SIG // NSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTes
// SIG // y+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGp
// SIG // F1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+
// SIG // /NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fz
// SIG // pk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNO
// SIG // wTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLi
// SIG // Mxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5
// SIG // UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
// SIG // BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
// SIG // XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIG
// SIG // CSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYE
// SIG // FCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSf
// SIG // pxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
// SIG // DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3Mv
// SIG // UmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0f
// SIG // BE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBK
// SIG // BggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
// SIG // Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
// SIG // reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1
// SIG // OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpT
// SIG // Td2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinL
// SIG // btg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
// SIG // 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJ
// SIG // w7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2Fz
// SIG // Lixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7
// SIG // hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY
// SIG // 3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFX
// SIG // SVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFU
// SIG // a2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz
// SIG // /gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/
// SIG // AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1
// SIG // ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328
// SIG // y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
// SIG // ahC0HVUzWLOhcGbyoYIDTTCCAjUCAQEwgfmhgdGkgc4w
// SIG // gcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1p
// SIG // Y3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJzAlBgNV
// SIG // BAsTHm5TaGllbGQgVFNTIEVTTjo5MjAwLTA1RTAtRDk0
// SIG // NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
// SIG // U2VydmljZaIjCgEBMAcGBSsOAwIaAxUAfO+tqz00HeyJ
// SIG // wwkHW9ZIBSkJAkSggYMwgYCkfjB8MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAOwN
// SIG // DIYwIhgPMjAyNTA2MzAxMzE1NTBaGA8yMDI1MDcwMTEz
// SIG // MTU1MFowdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA7A0M
// SIG // hgIBADAHAgEAAgIGUjAHAgEAAgISfzAKAgUA7A5eBgIB
// SIG // ADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMC
// SIG // oAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3
// SIG // DQEBCwUAA4IBAQBs/iJuA/ovEN/YkvkNRLce/BqBe8la
// SIG // k0qHZ+gX1iuOSVn7MC3jgJ/leGz3wViLD94yYr6ZSi6Z
// SIG // n2YA6aZCdutYidBCsQW+nViVpMnpMDiuO2+y2atOsP26
// SIG // /fTKgwUChQfhQpZNUgo82CgLahnRMNYX5DwNmlMLEqfZ
// SIG // Ui+IPhMX9xZoKer92rRwkOkKB3tF22XUGkUTuJ+eLZAF
// SIG // thOza3XAxuw7AhEifo2m3cOuKLl08r25slx6NUdgOYEp
// SIG // ejBWNYUxaIkZjzRB6aVbtVdp38S7jU9NyJWMpnXL35J8
// SIG // eo7UPXee2xoUA99n6XpDYYwVAehHId6wllRlfAKIz9/D
// SIG // Cc2pMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
// SIG // bXAgUENBIDIwMTACEzMAAAIJCAfg+VyM5lUAAQAAAgkw
// SIG // DQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzEN
// SIG // BgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgHJf5
// SIG // 2H8Fq/X8KZchEa5Oog53wP5fmSlJN+EDpPDHRe0wgfoG
// SIG // CyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCBoGyweyL30
// SIG // Ai5lDlGYY3VKivG4pHwemVVXaE4zcIUTPjCBmDCBgKR+
// SIG // MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
// SIG // dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
// SIG // aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
// SIG // Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAC
// SIG // CQgH4PlcjOZVAAEAAAIJMCIEIFoJJYPIIv8TolmZVP8C
// SIG // lACrvfr1aPRonRIaAi/23ZFhMA0GCSqGSIb3DQEBCwUA
// SIG // BIICAGkPGh7Tgk0YkFb77N8ambUOnx7G8SYmZFvnBMDT
// SIG // FXMyKW6xPg+E0VxeJ1rTRuKg25pg8Xlur6+OSXEHWiNN
// SIG // vMuvTRoJkQMv6tWRLFWkFko94de0fKZyAs5wBRB/GF58
// SIG // 7DjYCCD2tRoqUINKwYzN+ZMwiETzPqRsszQ27LxTPUXn
// SIG // YfrJ2ul8SCbjmrFWdB3YygQL8ReQxFMfzvMvpYNOVJOx
// SIG // 9cgLxCxVZeLiNsVKavXtmlY/JgcMYk33ndu0KW3sYt36
// SIG // dTNcKcXxhoE9rAUYRREFRzCadBoCtU1UHbWjmVCdoM7A
// SIG // 5FPjoXgUwydsRFH36Si06Bsm8NGsMPKotpgiV2HezTzd
// SIG // snFF4QubJJ2IxI2iUhsBZ4nvDBSmTTAjDCiHQlaQJick
// SIG // zMy9x9sBFWh6SoVyeOV+vUTAiT7PCUP8mfT61MbXXRhS
// SIG // KqOnXunBNsUxh1AH/C7rcg/L38NHc6MlRQW2gcKu3cjP
// SIG // LtVLAxdRa2gLA0ETVj1Vof7JhLiaHlneIkCQiDHcdBdx
// SIG // Zu0nhgIb8/e7cJb1UsvlyKZ6aCxw3I3SCu6kW66wvnXa
// SIG // ltlj8XcNNnXTTyuW4QysZG7xhdUOsQmtDFZcsjhEupBD
// SIG // BRIpTG55jZRSff2u37jmW/0KxWxmH3lcCpqMcn6DHHFJ
// SIG // fSkJXHe/EoBosC7893iHtKDO/j0P
// SIG // End signature block
