define("dotNetCountersSwimlane",["diagnosticsHub","diagnosticsHub-swimlanes","plugin-vs-v2"],((e,t,n)=>{return i={374:(e,t,n)=>{var i,r;i=[n,t,n(952),n(560),n(560),n(560),n(714),n(558),n(560),n(560),n(560),n(560),n(560),n(560),n(90),n(560)],r=function(e,t,n,i,r,s,o,a,l,d,u,c,h,g,m,p){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetCountersSwimlane=void 0,t.DotNetCountersSwimlane=class{constructor(e,t,n,r){this._counterSwimlaneMap={},this._counterDataSeriesMap={},this._counterIdsAdded=[],this._counterIdToFilterMap={},this._swimlaneConfig=e,this._currentTimespan=t,this._selectionTimespan=n,this._renderer=r,this._noCounterSelectedMessage=new o.NoCounterSelectedMessage(e),r.addControl(this._noCounterSelectedMessage,i.Renderer.headerSwimlanePriority+this._counterIdsAdded.length)}addCounterSwimlane(e,t,i,o){if(-1!==this._counterIdsAdded.indexOf(e))return;this._swimlaneConfig.header.titleText=t;const _=a.getLocalizedUnitConverter(i,0),C=a.getLocalizedUnitConverter(i,2),v=this._swimlaneConfig.graph,w=[],D=this._counterIdToFilterMap[e]||"";let E;E=o===n.MeterHistogram()?new m.HistogramDataSeries(e,this._swimlaneConfig.graph.timeRange,C,""):new l.CountersDataSeries(e,this._swimlaneConfig.graph.timeRange,C,new d.ChartColorScheme("rgb(118, 174, 200)",""),"",D),w.push(E),v.jsonConfig.Series=[];const S=new u.MultiSeriesGraph(this._swimlaneConfig.graph,w,C),f=new h.Scale(this._swimlaneConfig.graph.scale,g.ScaleType.Left,_),B=new h.Scale(this._swimlaneConfig.graph.scale,g.ScaleType.Right,_);S.scaleChangedEvent.addEventListener(f.onScaleChanged.bind(f)),S.scaleChangedEvent.addEventListener(B.onScaleChanged.bind(B));const b=new r.SwimlaneBase(this._swimlaneConfig.header,this._swimlaneConfig.graph.height,this._currentTimespan,this._selectionTimespan);S.scaleChangedEvent.addEventListener(b.onScaleChanged.bind(b)),o===n.MeterHistogram()&&b.addTitleControl(new p.Legend(a.getLegends())),b.addMainRegionControl(new s.SelectionOverlay(S,this._currentTimespan,this._selectionTimespan,this._swimlaneConfig.id)),b.addMainRegionControl(new c.GridLineRenderer(this._currentTimespan)),b.addLeftRegionControl(f),b.addRightRegionControl(B),b.onViewportChanged({currentTimespan:this._renderer.viewportController.visible,selectionTimespan:this._renderer.viewportController.selection,isIntermittent:!1}),b.swimlaneVisibilityChangedEvent.addEventListener((()=>this.updateSwimlaneHost())),0===this._counterIdsAdded.length&&this._renderer.removeControl(this._noCounterSelectedMessage),this._counterIdsAdded.push(e),this._renderer.viewportController.viewportStateChanged.addEventListener(b.onViewportChanged.bind(b)),this._renderer.addControl(b,1/0),this._counterSwimlaneMap[e]=b,this._counterDataSeriesMap[e]=E}removeCounterSwimlane(e){const t=this._counterIdsAdded.indexOf(e);if(-1===t)return;this._counterIdsAdded.splice(t,1);const n=this._counterSwimlaneMap[e];this._renderer.removeControl(n),this._renderer.viewportController.viewportStateChanged.removeEventListener(n.onViewportChanged.bind(n)),0===this._counterIdsAdded.length&&this._renderer.addControl(this._noCounterSelectedMessage,i.Renderer.headerSwimlanePriority+this._counterIdsAdded.length)}filterChanged(e,t){this._counterIdToFilterMap[e]=t,-1!==this._counterIdsAdded.indexOf(e)&&this._counterDataSeriesMap[e].filterChanged(t)}updateSwimlaneHost(){i.getRenderer().resizeHost()}}}.apply(t,i),void 0===r||(e.exports=r)},597:(e,t,n)=>{var i,r;i=[n,t,n(560),n(560),n(374),n(766)],r=function(e,t,n,i,r,s){"use strict";function o(e,t,o,a,l,d){const u=new i.SwimlaneConfiguration(e,l,a);u.header.isBodyExpanded=t,u.graph.height=40;const c=n.getRenderer({dataManager:null,containerId:null,isSelectionEnabled:!0,isLive:!0}),h=new r.DotNetCountersSwimlane(u,l,d,c),g=new s.DotNetCountersMarshaler;g.getCountersAddedToSwimlane().then((e=>{e.forEach((e=>{h.addCounterSwimlane(e.CounterId,e.DisplayName,e.DisplayUnit,e.CounterType)}))})),g.counterAddedEvent.addEventListener((e=>{h.addCounterSwimlane(e.counterId,e.displayName,e.displayUnit,e.counterType)})),g.counterRemovedEvent.addEventListener((e=>{h.removeCounterSwimlane(e.counterId)})),g.filterChangedEvent.addEventListener((e=>{h.filterChanged(e.counterId,e.filterString)}))}Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetCountersSwimlaneFactory=void 0,t.DotNetCountersSwimlaneFactory=o,window.DotNetCountersSwimlaneFactory=o}.apply(t,i),void 0===r||(e.exports=r)},90:(e,t,n)=>{var i,r;i=[n,t,n(226),n(117),n(117),n(560),n(117),n(117),n(558),n(560)],r=function(e,t,n,i,r,s,o,a,l,d){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.HistogramDataSeries=void 0;class u{constructor(e,t,n,s,l){this._currentTimespan=new i.JsonTimespan(i.BigNumber.zero,i.BigNumber.zero),this._droppedRequest=!1,this._samples=250,this._width=250,this._logger=o.getLogger("HistogramDataSeries"),this._newDataEvent=new a.AggregatedEvent,this._cachedPoints=new Map,this._bars=[],this._colorMap=new Map,this._minValue=0,this._maxValue=0,this._minBarWidth=5,this._maxBarWidth=50,this._sToNano=1e9,this._gapPx=2,this._currentTimespan=t,this._title=s,this._tooltip=l,this._unitConverter=n,this._marker=document.createElement("div"),this._marker.classList.add("countersDataSeries-marker"),this._barWidth=this._minBarWidth,this._dataWarehouseRequestHandle=r.loadDataWarehouse().then((t=>{const n={customDomain:{Task:"GetHistogram",CounterId:e}};return t.getFilteredData(n,u.analyzerId)})).then((e=>{this._countersResult=e})).then((()=>{this._dataWarehouseRequestHandle=null,this._droppedRequest=!1,this.requestUpdate()}))}get minValue(){return this._minValue}get maxValue(){return this._maxValue}get marker(){return this._marker}get newDataEvent(){return this._newDataEvent}get title(){return this._title}get tooltip(){return this._tooltip}static get analyzerId(){return"66EDDDF1-2277-40F3-983A-6FF57A433ECB"}dispose(){this._countersResult&&this._countersResult.dispose(),this._newDataEvent.dispose()}onViewportChanged(e){this._currentTimespan=e,this.requestUpdate()}getPointAtTimestamp(e,t){if(0===this._bars.length)return null;let i={Timestamp:e,Value:0};const r=d.Utilities.findLessThan(this._bars,i,((e,t)=>t.Timestamp.greater(e.Timestamp)));return i=this._bars[r],{timestamp:i.Timestamp,tooltip:n.Resources.getString("/DiagnosticsHubSwimlaneResources/ChartSeriesFormattableTooltipLabel",this._unitConverter.formatNumber(i.Value,n.Resources.getString("/DiagnosticsHubSwimlaneResources/ChartSeriesFormattableTooltipLabelNumberWithUnit"),null,!0))}}draw(e,t){if(0===this._cachedPoints.size||t.gridX.elapsed.equals(i.BigNumber.zero)||t.chartRect.width<=0)return;if(t.chartRect.width!==this._width){this._width=t.chartRect.width,this._samples=t.chartRect.width;const e=i.BigNumber.subtract(this._currentTimespan.end,this._currentTimespan.begin);let n=t.chartRect.width*this._sToNano/parseInt(e.value,16);const r=this._minBarWidth*this._cachedPoints.size+this._gapPx;for(;n<r;)this._samples=Math.floor(this._samples/2),n*=2;this.requestUpdate()}this._barWidth=this.calculateBarWidth(t,this._cachedPoints);const n=[];for(const e of this._cachedPoints.keys())n.push(e);const r=[];for(const e of n)r.push(this._colorMap.get(e));const s=this._cachedPoints.get(n[0]).length;for(let i=0;i<s;i++){const s=[];for(const e of n){const t=this._cachedPoints.get(e)[i];s.push(t)}this.drawBarGroup(e,t,s,r)}}onDataUpdate(e){if(this._currentTimespan.contains(e)||0===this._cachedPoints.size)return void this.requestUpdate();const t=this._cachedPoints.get(this._cachedPoints.keys().next().value);this._currentTimespan.end.greater(t[t.length-1].Timestamp)&&this.requestUpdate()}requestUpdate(){if(this._dataWarehouseRequestHandle)return void(this._droppedRequest=!0);if(this._currentTimespan.elapsed.equals(i.BigNumber.zero))return void(this._dataWarehouseRequestHandle=null);const e=i.BigNumber.divideNumber(this._currentTimespan.elapsed,2),t=i.BigNumber.subtract(this._currentTimespan.begin,i.BigNumber.min(e,this._currentTimespan.begin)),n=i.BigNumber.multiply(i.BigNumber.divide(t,this._currentTimespan.elapsed),this._currentTimespan.elapsed),r=i.BigNumber.add(n,i.BigNumber.multiplyNumber(this._currentTimespan.elapsed,3)),o={type:"SamplePoints",begin:n.jsonValue,end:r.jsonValue,samples:Math.max(this._samples,2)};this._dataWarehouseRequestHandle=this._countersResult.getResult(o).then((e=>this.cachePoints(e))).then((()=>{this._dataWarehouseRequestHandle=null,this._droppedRequest&&(window.setTimeout((()=>this.requestUpdate()),s.Constants.TimeoutRollingGraph),this._droppedRequest=!1)}),(e=>{this._logger.error(`Error occurred while communicating with the DataWarehouse: ${JSON.stringify(e,Object.getOwnPropertyNames(e))}`)}))}cachePoints(e){const t=Object.keys(e).sort();for(let n=0;n<t.length;n++){const r=t[n],s=e[r].map((e=>{const t=new i.BigNumber(e.t.h,e.t.l);return this._minValue=Math.min(this._minValue,e.v),this._maxValue=Math.max(this._maxValue,e.v),{Timestamp:t,Value:e.v,ToolTip:e.tt}}));this._cachedPoints.set(r,s),this._colorMap.set(r,l.getColorSet()[n])}this._newDataEvent.invokeEvent(this)}drawBarGroup(e,t,n,i){const r=(s=n[0].Timestamp,d.Utilities.convertToPixel(s,t.gridX,t.chartRect.width,!1));var s;let o=0;for(let s=0;s<n.length;s++){e.save();const a=n[s],l=i[s],u=-1*d.Utilities.scaleToRange(a.Value,t.gridY.min,t.gridY.max,0,t.chartRect.height);e.fillStyle=l,e.strokeStyle=l,e.fillRect(r+o,t.chartRect.height,this._barWidth,u);const c=Object.assign({},a);c.Timestamp=d.Utilities.getTimestampAtPixel(r+o,t.chartRect.width,this._currentTimespan),this._bars.push(c),o+=this._barWidth,e.restore()}}calculateBarWidth(e,t){let n=this._maxBarWidth*t.size;const i=this._minBarWidth*this._cachedPoints.size+this._gapPx;let r=0;const[s]=t.values(),o=new Set;s.forEach(((t,s)=>{const a=(l=t.Timestamp,d.Utilities.convertToPixel(l,e.gridX,e.chartRect.width,!1));var l;let u=!1;if(0!==r&&r!==a){u=a-r<i;const e=u?n:a-r;n=Math.min(e,n)}u?o.add(s):r=a}));for(const[e,t]of this._cachedPoints){const n=t.filter(((e,t)=>!o.has(t)));this._cachedPoints.set(e,n)}return(n-this._gapPx)/t.size}}t.HistogramDataSeries=u}.apply(t,i),void 0===r||(e.exports=r)},714:(e,t,n)=>{var i,r;i=[n,t,n(952),n(117)],r=function(e,t,n,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.NoCounterSelectedMessage=void 0,t.NoCounterSelectedMessage=class{constructor(e){if(this._viewEventManager=i.getViewEventManager(),this._container=document.createElement("div"),"PerformanceDebugging"===e.graph.jsonConfig.viewDestinations){const t=document.createElement("span");t.innerText=e.graph.resources.NoCounterSelectedMessage_PerformanceDebugger;const n=document.createElement("a");n.innerText=e.graph.resources.NoCounterSelectedMessage_PerformanceDebuggerLink,this._container.appendChild(t),this._container.appendChild(n),n.onclick=e=>this.onClick(e)}else this._container.innerText=e.graph.resources.NoCounterSelectedMessage_PerformanceProfiler;this._container.style.width="100%",this._container.style.textAlign="center"}onClick(e){this._viewEventManager.selectDetailsView(n.CountersPerformanceDebuggingDetailsViewId())}get container(){return this._container}}}.apply(t,i),void 0===r||(e.exports=r)},952:(e,t,n)=>{var i;i=function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.providerIds=t.providerIdToProviderNameMap=t.EventCounter=t.MeterHistogram=t.MeterCounter=t.errorNameCanceled=t.TimeoutImmediate=t.CountersAnalyzerId=t.DotNetCountersAnalyzerId=t.CountersPerformanceDebuggingDetailsViewId=t.CountersCollectionDetailsViewId=t.CountersAnalysisDetailsViewId=void 0,t.CountersAnalysisDetailsViewId=function(){return"7FB3ABC0-46CA-4888-8AC4-265DB211561B"},t.CountersCollectionDetailsViewId=function(){return"26396E76-DFA0-4CF2-924F-121A8A24DD84"},t.CountersPerformanceDebuggingDetailsViewId=function(){return"F7D99DE5-927E-490D-B41F-573944E0B44E"},t.DotNetCountersAnalyzerId=function(){return"3769A1FC-E2C8-43DE-B722-254410B82363"},t.CountersAnalyzerId=function(){return"66EDDDF1-2277-40F3-983A-6FF57A433ECB"},t.TimeoutImmediate=function(){return 0},t.errorNameCanceled=function(){return"Canceled"},t.MeterCounter=function(){return"MeterCounter"},t.MeterHistogram=function(){return"MeterHistogram"},t.EventCounter=function(){return"EventCounter"},t.providerIdToProviderNameMap={"{49592C0F-5A05-516D-AA4B-A64E02026C89}":"System.Runtime","{9DED64A4-414C-5251-DCF7-1E4E20C15E70}":"Microsoft.AspNetCore.Hosting","{D30B5633-7EF1-5485-B4E0-94979B102068}":"System.Net.Http","{BDEB4676-A36E-5442-DB99-4764E2326C7D}":"Microsoft-AspNetCore-Server-Kestrel","{7BEEE6B1-E3FA-5DDB-34BE-1404AD0E2520}":"System.Net.Security","{D5B2E7D4-B6EC-50AE-7CDE-AF89427AD21F}":"System.Net.Sockets","{DDB567A6-2B86-545E-887F-2677536A7C50}":"System.Runtime.Caching.Default","{C26FE4B6-8790-5D41-5900-0F2B6B74EFAA}":"Microsoft.AspNetCore.Http.Connections","{A605548A-6963-55CF-F000-99A6013DEB01}":"Microsoft.AspNetCore.ConcurrencyLimiter","{4B326142-BFB5-5ED3-8585-7714181D14B0}":"System.Net.NameResolution"},t.providerIds=["{49592C0F-5A05-516D-AA4B-A64E02026C89}","{9DED64A4-414C-5251-DCF7-1E4E20C15E70}","{D30B5633-7EF1-5485-B4E0-94979B102068}","{BDEB4676-A36E-5442-DB99-4764E2326C7D}","{7BEEE6B1-E3FA-5DDB-34BE-1404AD0E2520}","{D5B2E7D4-B6EC-50AE-7CDE-AF89427AD21F}","{DDB567A6-2B86-545E-887F-2677536A7C50}","{C26FE4B6-8790-5D41-5900-0F2B6B74EFAA}","{A605548A-6963-55CF-F000-99A6013DEB01}","{4B326142-BFB5-5ED3-8585-7714181D14B0}","{20752BC4-C151-50F5-F27B-DF92D8AF5A61}"]}.apply(t,[n,t]),void 0===i||(e.exports=i)},766:(e,t,n)=>{var i,r;i=[n,t,n(226),n(117)],r=function(e,t,n,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.DotNetCountersMarshaler=void 0;let r=null;t.DotNetCountersMarshaler=class{constructor(){r||(r=n.JSONMarshaler.attachToMarshaledObject("Microsoft.DiagnosticsHub.Tools.DotNetCounters.DotNetCountersMarshaler",{},!0)),this._counterAddedEvent=new i.ObservableEvent(r,"CounterAddedEvent"),this._counterRemovedEvent=new i.ObservableEvent(r,"CounterRemovedEvent"),this._filterChangedEvent=new i.ObservableEvent(r,"FilterChangedEvent")}getDoubleClickTimeMs(){return r._call("getDoubleClickTimeMs")}getCountersAddedToSwimlane(e=!1){return e?r._call("getCountersAddedToSwimlanePerSolution"):r._call("getCountersAddedToSwimlane")}get counterAddedEvent(){return this._counterAddedEvent}get counterRemovedEvent(){return this._counterRemovedEvent}get filterChangedEvent(){return this._filterChangedEvent}addCounter(e,t,n,i){r._call("addCounter",e,t,n,i)}removeCounter(e){r._call("removeCounter",e)}changeFilter(e,t){r._call("changeFilter",e,t)}getColumnSettings(e){return r._call("getColumnSettings",e)}onColumnChanged(e,t){r._call("onColumnChanged",e,t)}}}.apply(t,i),void 0===r||(e.exports=r)},558:(e,t,n)=>{var i,r;i=[n,t,n(226),n(560)],r=function(e,t,n,i){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getLegends=t.getColorSet=t.MiBUnitConverter=t.ByteUnitConverter=t.getFormatTemplate=t.getLocalizedUnitConverter=void 0,t.getLocalizedUnitConverter=function(e,t){return"%"===e?new i.LocalizedUnitConverter([{Unit:"percentage",Divider:1,Decimals:t,LowerBound:0}],{percentage:"%"}):"B"===e?new r(t):"MB"===e?new s(t):new i.LocalizedUnitConverter([{Unit:"",Divider:1,Decimals:t,LowerBound:0},{Unit:"K",Divider:1e3,Decimals:t,LowerBound:1e3},{Unit:"M",Divider:1e6,Decimals:t,LowerBound:1e6},{Unit:"B",Divider:1e9,Decimals:t,LowerBound:1e9}],{"":"",K:n.Resources.getString("/DiagnosticsHubSwimlaneResources/CountKUnit"),M:n.Resources.getString("/DiagnosticsHubSwimlaneResources/CountMUnit"),B:n.Resources.getString("/DiagnosticsHubSwimlaneResources/CountBUnit")})},t.getFormatTemplate=function(e){return"%"===e?n.Resources.getString("/DiagnosticsHubSwimlaneResources/FormattedPercentage"):n.Resources.getString("/DiagnosticsHubSwimlaneResources/FormattedNumberWithUnitsTableView")};class r extends i.BitBinaryMultipleUnitConverter{scaleValue(e){return super.scaleValue(8*e)}}t.ByteUnitConverter=r;class s extends i.BitBinaryMultipleUnitConverter{scaleValue(e){return super.scaleValue(1024*e*1024*8)}}t.MiBUnitConverter=s,t.getColorSet=function(){return[n.Theme.getValue("diagnostics-swimlane-bar-strong-blue"),n.Theme.getValue("diagnostics-swimlane-bar-red"),n.Theme.getValue("diagnostics-swimlane-bar-green")]},t.getLegends=function(){return[{legendText:n.Resources.getString("/DiagnosticsHubSwimlaneResources/Histogram_Legend_50th"),color:n.Theme.getValue("diagnostics-swimlane-bar-strong-blue"),legendTooltip:n.Resources.getString("/DiagnosticsHubSwimlaneResources/Histogram_Legend_Tooltip")},{legendText:n.Resources.getString("/DiagnosticsHubSwimlaneResources/Histogram_Legend_95th"),color:n.Theme.getValue("diagnostics-swimlane-bar-red"),legendTooltip:n.Resources.getString("/DiagnosticsHubSwimlaneResources/Histogram_Legend_Tooltip")},{legendText:n.Resources.getString("/DiagnosticsHubSwimlaneResources/Histogram_Legend_99th"),color:n.Theme.getValue("diagnostics-swimlane-bar-green"),legendTooltip:n.Resources.getString("/DiagnosticsHubSwimlaneResources/Histogram_Legend_Tooltip")}]}}.apply(t,i),void 0===r||(e.exports=r)},117:t=>{"use strict";t.exports=e},560:e=>{"use strict";e.exports=t},226:e=>{"use strict";e.exports=n}},r={},function e(t){var n=r[t];if(void 0!==n)return n.exports;var s=r[t]={exports:{}};return i[t](s,s.exports,e),s.exports}(597);var i,r}));
// SIG // Begin signature block
// SIG // MIIoQQYJKoZIhvcNAQcCoIIoMjCCKC4CAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // yHKoWvpcQpBA0eH66IYvFiVs+Dq9uqVNed4Gr4oxXmag
// SIG // gg12MIIF9DCCA9ygAwIBAgITMwAABARsdAb/VysncgAA
// SIG // AAAEBDANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTI0MDkxMjIwMTExNFoX
// SIG // DTI1MDkxMTIwMTExNFowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // tCg32mOdDA6rBBnZSMwxwXegqiDEUFlvQH9Sxww07hY3
// SIG // w7L52tJxLg0mCZjcszQddI6W4NJYb5E9QM319kyyE0l8
// SIG // EvA/pgcxgljDP8E6XIlgVf6W40ms286Cr0azaA1f7vaJ
// SIG // jjNhGsMqOSSSXTZDNnfKs5ENG0bkXeB2q5hrp0qLsm/T
// SIG // WO3oFjeROZVHN2tgETswHR3WKTm6QjnXgGNj+V6rSZJO
// SIG // /WkTqc8NesAo3Up/KjMwgc0e67x9llZLxRyyMWUBE9co
// SIG // T2+pUZqYAUDZ84nR1djnMY3PMDYiA84Gw5JpceeED38O
// SIG // 0cEIvKdX8uG8oQa047+evMfDRr94MG9EWwIDAQABo4IB
// SIG // czCCAW8wHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFPIboTWxEw1PmVpZS+AzTDwo
// SIG // oxFOMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQLExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAx
// SIG // Mis1MDI5MjMwHwYDVR0jBBgwFoAUSG5k5VAF04KqFzc3
// SIG // IrVtqMp1ApUwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNybDBhBggr
// SIG // BgEFBQcBAQRVMFMwUQYIKwYBBQUHMAKGRWh0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
// SIG // Q29kU2lnUENBMjAxMV8yMDExLTA3LTA4LmNydDAMBgNV
// SIG // HRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQCI5g/S
// SIG // KUFb3wdUHob6Qhnu0Hk0JCkO4925gzI8EqhS+K4umnvS
// SIG // BU3acsJ+bJprUiMimA59/5x7WhJ9F9TQYy+aD9AYwMtb
// SIG // KsQ/rst+QflfML+Rq8YTAyT/JdkIy7R/1IJUkyIS6srf
// SIG // G1AKlX8n6YeAjjEb8MI07wobQp1F1wArgl2B1mpTqHND
// SIG // lNqBjfpjySCScWjUHNbIwbDGxiFr93JoEh5AhJqzL+8m
// SIG // onaXj7elfsjzIpPnl8NyH2eXjTojYC9a2c4EiX0571Ko
// SIG // mhENF3RtR25A7/X7+gk6upuE8tyMy4sBkl2MUSF08U+E
// SIG // 2LOVcR8trhYxV1lUi9CdgEU2CxODspdcFwxdT1+G8YNc
// SIG // gzHyjx3BNSI4nOZcdSnStUpGhCXbaOIXfvtOSfQX/UwJ
// SIG // oruhCugvTnub0Wna6CQiturglCOMyIy/6hu5rMFvqk9A
// SIG // ltIJ0fSR5FwljW6PHHDJNbCWrZkaEgIn24M2mG1M/Ppb
// SIG // /iF8uRhbgJi5zWxo2nAdyDBqWvpWxYIoee/3yIWpquVY
// SIG // cYGhJp/1I1sq/nD4gBVrk1SKX7Do2xAMMO+cFETTNSJq
// SIG // fTSSsntTtuBLKRB5mw5qglHKuzapDiiBuD1Zt4QwxA/1
// SIG // kKcyQ5L7uBayG78kxlVNNbyrIOFH3HYmdH0Pv1dIX/Mq
// SIG // 7avQpAfIiLpOWwcbjzCCB3owggVioAMCAQICCmEOkNIA
// SIG // AAAAAAMwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290
// SIG // IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTEx
// SIG // MDcwODIwNTkwOVoXDTI2MDcwODIxMDkwOVowfjELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0
// SIG // IENvZGUgU2lnbmluZyBQQ0EgMjAxMTCCAiIwDQYJKoZI
// SIG // hvcNAQEBBQADggIPADCCAgoCggIBAKvw+nIQHC6t2G6q
// SIG // ghBNNLrytlghn0IbKmvpWlCquAY4GgRJun/DDB7dN2vG
// SIG // EtgL8DjCmQawyDnVARQxQtOJDXlkh36UYCRsr55JnOlo
// SIG // XtLfm1OyCizDr9mpK656Ca/XllnKYBoF6WZ26DJSJhIv
// SIG // 56sIUM+zRLdd2MQuA3WraPPLbfM6XKEW9Ea64DhkrG5k
// SIG // NXimoGMPLdNAk/jj3gcN1Vx5pUkp5w2+oBN3vpQ97/vj
// SIG // K1oQH01WKKJ6cuASOrdJXtjt7UORg9l7snuGG9k+sYxd
// SIG // 6IlPhBryoS9Z5JA7La4zWMW3Pv4y07MDPbGyr5I4ftKd
// SIG // gCz1TlaRITUlwzluZH9TupwPrRkjhMv0ugOGjfdf8NBS
// SIG // v4yUh7zAIXQlXxgotswnKDglmDlKNs98sZKuHCOnqWbs
// SIG // YR9q4ShJnV+I4iVd0yFLPlLEtVc/JAPw0XpbL9Uj43Bd
// SIG // D1FGd7P4AOG8rAKCX9vAFbO9G9RVS+c5oQ/pI0m8GLhE
// SIG // fEXkwcNyeuBy5yTfv0aZxe/CHFfbg43sTUkwp6uO3+xb
// SIG // n6/83bBm4sGXgXvt1u1L50kppxMopqd9Z4DmimJ4X7Iv
// SIG // hNdXnFy/dygo8e1twyiPLI9AN0/B4YVEicQJTMXUpUMv
// SIG // dJX3bvh4IFgsE11glZo+TzOE2rCIF96eTvSWsLxGoGyY
// SIG // 0uDWiIwLAgMBAAGjggHtMIIB6TAQBgkrBgEEAYI3FQEE
// SIG // AwIBADAdBgNVHQ4EFgQUSG5k5VAF04KqFzc3IrVtqMp1
// SIG // ApUwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYD
// SIG // VR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0j
// SIG // BBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0f
// SIG // BFMwUTBPoE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQu
// SIG // Y29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0
// SIG // MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRS
// SIG // MFAwTgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9z
// SIG // b2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
// SIG // MV8yMDExXzAzXzIyLmNydDCBnwYDVR0gBIGXMIGUMIGR
// SIG // BgkrBgEEAYI3LgMwgYMwPwYIKwYBBQUHAgEWM2h0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvZG9jcy9w
// SIG // cmltYXJ5Y3BzLmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBwAG8AbABpAGMAeQBfAHMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // Z/KGpZjgVHkaLtPYdGcimwuWEeFjkplCln3SeQyQwWVf
// SIG // Liw++MNy0W2D/r4/6ArKO79HqaPzadtjvyI1pZddZYSQ
// SIG // fYtGUFXYDJJ80hpLHPM8QotS0LD9a+M+By4pm+Y9G6XU
// SIG // tR13lDni6WTJRD14eiPzE32mkHSDjfTLJgJGKsKKELuk
// SIG // qQUMm+1o+mgulaAqPyprWEljHwlpblqYluSD9MCP80Yr
// SIG // 3vw70L01724lruWvJ+3Q3fMOr5kol5hNDj0L8giJ1h/D
// SIG // Mhji8MUtzluetEk5CsYKwsatruWy2dsViFFFWDgycSca
// SIG // f7H0J/jeLDogaZiyWYlobm+nt3TDQAUGpgEqKD6CPxNN
// SIG // ZgvAs0314Y9/HG8VfUWnduVAKmWjw11SYobDHWM2l4bf
// SIG // 2vP48hahmifhzaWX0O5dY0HjWwechz4GdwbRBrF1HxS+
// SIG // YWG18NzGGwS+30HHDiju3mUv7Jf2oVyW2ADWoUa9WfOX
// SIG // pQlLSBCZgB/QACnFsZulP0V3HjXG0qKin3p6IvpIlR+r
// SIG // +0cjgPWe+L9rt0uX4ut1eBrs6jeZeRhL/9azI2h15q/6
// SIG // /IvrC4DqaTuv/DDtBEyO3991bWORPdGdVk5Pv4BXIqF4
// SIG // ETIheu9BCrE/+6jMpF3BoYibV3FWTkhFwELJm3ZbCoBI
// SIG // a/15n8G9bW1qyVJzEw16UM0xghojMIIaHwIBATCBlTB+
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNy
// SIG // b3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExAhMzAAAE
// SIG // BGx0Bv9XKydyAAAAAAQEMA0GCWCGSAFlAwQCAQUAoIGu
// SIG // MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisG
// SIG // AQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3
// SIG // DQEJBDEiBCDa4uIz2zl080WRJRXaspFySbh5198LCMHT
// SIG // yTJ2kIrKCTBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBp
// SIG // AGMAcgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAC2TRbbv
// SIG // u+5GRKR1AiVUDsTf1iVSID2NZjwTlysWkfoX6boBpj9i
// SIG // GRE7uQmxleUTNz55EsU/Yrb2Tf8LV+dVdOcd7afEngt8
// SIG // EdFMyk5J8NQ3xBoAs8ZMVtWEBmOb+Ari0BgkXl86/qIQ
// SIG // iWUvMF3l/WPrpAmOaccPyCeZz06gg8O3J8mxgvEN7QMP
// SIG // ETD89LXWpmf1kacvMc7+oBf74imIakCOFrkgz+uCU747
// SIG // kokwI7sL1mg7ZvsBBhX3eXfbJDSpdi9zt6lXHUwm9xhl
// SIG // 4l3XitgcebNuXQYDCu0UDhMX8ArgnHWiGdqpx9PgsHjO
// SIG // ZPJlT69RihqBAlC9Irj0fCEInWqhghetMIIXqQYKKwYB
// SIG // BAGCNwMDATGCF5kwgheVBgkqhkiG9w0BBwKggheGMIIX
// SIG // ggIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBWgYLKoZIhvcN
// SIG // AQkQAQSgggFJBIIBRTCCAUECAQEGCisGAQQBhFkKAwEw
// SIG // MTANBglghkgBZQMEAgEFAAQg2W6HItSlW9FdJ5q8E0Hx
// SIG // ktWKrXPFf1fT82CqTtLl4ZwCBmhS9bE+mhgTMjAyNTA2
// SIG // MzAxNDQ3NDUuNzQ1WjAEgAIB9KCB2aSB1jCB0zELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0
// SIG // IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMScwJQYD
// SIG // VQQLEx5uU2hpZWxkIFRTUyBFU046NTIxQS0wNUUwLUQ5
// SIG // NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFNlcnZpY2WgghH7MIIHKDCCBRCgAwIBAgITMwAAAgAL
// SIG // 16p/GyoXVgABAAACADANBgkqhkiG9w0BAQsFADB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNDA3MjUx
// SIG // ODMxMjFaFw0yNTEwMjIxODMxMjFaMIHTMQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
// SIG // bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
// SIG // Hm5TaGllbGQgVFNTIEVTTjo1MjFBLTA1RTAtRDk0NzEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
// SIG // ggIBAK9V2mnSpD9k5Lp6Exee9/7ReyiTPQ6Ir93HL9up
// SIG // qp1IZr9gzOfYpBE+Fp0X6OW4hSB3Oi6qyHqgoE/X0/xp
// SIG // LOVSjvdGUFtmr4fzzB55dJGX1/yOc3VaKFx23VFJD4mX
// SIG // zV7M1rMJi/VJVqPJs8r/S6fUwLcP6FzmEwMXWEqjgeVM
// SIG // 89UNwPLgqTZbpkDQyRg2OnEp9DJWLpF5JQKwoaupfimK
// SIG // 5eq/1pzql0pJwAaYIErCd96C96J5g4jfWFAKWcI5zYfT
// SIG // OpA2p3ks+/P2LQ/9qRqcffy1xC6GsxFBcYcoOCnZqFhj
// SIG // WMHUe/4nfNYHjhEevZeXSb+9Uv5h/i8W+i+vdp/LhJgF
// SIG // cOn1bxPnPMI4GGW5WQjTwMpwpw3bkS3ZNY7MAqo6jXN1
// SIG // /1iMwOxhrOB1EuGCKwFMfB9gPeLwzYgPAFmu2fx0sEws
// SIG // iIHlW5XV2DNgbcTCqt5J3kaE9uzUO2O5/GU2gI3uwZX4
// SIG // 7vN7KRj/0FmDWdcGM2FRkcjqXQPFpsauVfH+a+B2hvcz
// SIG // 3MpDsiaUWcvld0RooIRZrAiVwHDM4ju+h4p8AiIyJpwh
// SIG // ShifyGy4x+ie3yV6kT24Ph+q2C2fFwaZlwRR+D02pGVW
// SIG // MQfz/hEGy+SzcNGSDPnrn8QpY1eDvpx5DPs4EsfPtOwV
// SIG // WTwSrJaKHm7JoSHATtO+/ZHoXImDAgMBAAGjggFJMIIB
// SIG // RTAdBgNVHQ4EFgQUgCUk2r4JIyqoHucUDl59+X13dzow
// SIG // HwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIw
// SIG // XwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0JTIw
// SIG // VGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
// SIG // CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9N
// SIG // aWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAx
// SIG // MCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8E
// SIG // DDAKBggrBgEFBQcDCDAOBgNVHQ8BAf8EBAMCB4AwDQYJ
// SIG // KoZIhvcNAQELBQADggIBACjwhvZ40bSKkPn7hAoMc1jL
// SIG // EDiNx71u7FfT5hFggjlpU7hgiMzYt4m3S2UtG9iAx4NM
// SIG // i67XVbgYtxcVXXrCF7s2MqHyHv2pUwXVeA4Yoy017Qez
// SIG // YDp6Oxtdojt7eo8tYT0qrsxi68v9phGQcCLEqEtg/h/t
// SIG // xwicTw8oczBaj/qZZbTwAgf0DcGe6vhxsmb97/Hrfq0G
// SIG // IPLBdz07lng4N3Uf85NTWsCf3XxQg2JVjXggQi7zT0AX
// SIG // HjGFxURSoXElMLO5hXSAw4WacasiCg9lg8BcjSBhHs5/
// SIG // p3eJF0bqXjRMfnkqSV8pUQ/tXeOYW+j8ziBewZHD7UbR
// SIG // VtsF4JIy6rU1lpQZL85drjX2Cdwj2VWg8jA2ml4Dvh+g
// SIG // 4q7CeCBvYpCHfeNfplg3o5I+WmJ/UDekTn6PxzR4NbYp
// SIG // sKRaFIr6gBbuoq1mRcOVfsi6/BS3O52zGtpRUosc7ves
// SIG // 3Zw7DyJs9HOkrW2MoSkpTN7g0YvVFsnUiqpxG7SejJPm
// SIG // Lsb86a5LlkCWFn6T77oPsE54qMpFcHNMkVXLHeMTM555
// SIG // 0bWQxjElBJfbTFZ3m2EbIcGSMiU7AYC2ZhzO6tkxSv1/
// SIG // feOEpCKsmNtgHLi3tBqqDXwEgiHGbc22f8z+JU9vzdKQ
// SIG // 259n3wM42ZISPkK6q/fN5kGVsGXa905NTGBJQ04c9g9D
// SIG // MIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJmQAAAAAA
// SIG // FTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2Vy
// SIG // dGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMw
// SIG // MTgyMjI1WhcNMzAwOTMwMTgzMjI1WjB8MQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
// SIG // BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O
// SIG // 1YLT/e6cBwfSqWxOdcjKNVf2AX9sSuDivbk+F2Az/1xP
// SIG // x2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhgfWpS
// SIG // g0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/Y
// SIG // JlN8OWECesSq/XJprx2rrPY2vjUmZNqYO7oaezOtgFt+
// SIG // jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/dvI2k45GP
// SIG // sjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6
// SIG // BVWYbWg7mka97aSueik3rMvrg0XnRm7KMtXAhjBcTyzi
// SIG // YrLNueKNiOSWrAFKu75xqRdbZ2De+JKRHh09/SDPc31B
// SIG // mkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn42
// SIG // 7DZM9ituqBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n
// SIG // 6Jl8P0zbr17C89XYcz1DTsEzOUyOArxCaC4Q6oRRRuLR
// SIG // vWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2
// SIG // ZItboKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9
// SIG // stQcxWv2XFJRXRLbJbqvUAV6bMURHXLvjflSxIUXk8A8
// SIG // FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
// SIG // AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQAB
// SIG // MCMGCSsGAQQBgjcVAgQWBBQqp1L+ZMSavoKRPEY1Kc8Q
// SIG // /y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacbUzUZ
// SIG // 6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/
// SIG // BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQu
// SIG // Y29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnkuaHRtMBMG
// SIG // A1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQM
// SIG // HgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMB
// SIG // Af8EBTADAQH/MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjR
// SIG // PZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6
// SIG // Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1
// SIG // Y3RzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBa
// SIG // BggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6
// SIG // Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWlj
// SIG // Um9vQ2VyQXV0XzIwMTAtMDYtMjMuY3J0MA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
// SIG // XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x
// SIG // 5MKP+2zRoZQYIu7pZmc6U03dmLq2HnjYNi6cqYJWAAOw
// SIG // Bb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVtI1Tk
// SIG // eFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8Z
// SIG // thISEV09J+BAljis9/kpicO8F7BUhUKz/AyeixmJ5/AL
// SIG // aoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTpkbKpW99J
// SIG // o3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32
// SIG // THJvEKt1MMU0sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEU
// SIG // BHG/ZPkkvnNtyo4JvbMBV0lUZNlz138eW0QBjloZkWsN
// SIG // n6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQ
// SIG // THa1V1QJsWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+
// SIG // y/g75LcVv7TOPqUxUYS8vwLBgqJ7Fx0ViY1w/ue10Cga
// SIG // iQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0l
// SIG // lOZ0dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghi
// SIG // f9lwY1NNje6CbaUFEMFxBmoQtB1VM1izoXBm8qGCA1Yw
// SIG // ggI+AgEBMIIBAaGB2aSB1jCB0zELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQg
// SIG // T3BlcmF0aW9ucyBMaW1pdGVkMScwJQYDVQQLEx5uU2hp
// SIG // ZWxkIFRTUyBFU046NTIxQS0wNUUwLUQ5NDcxJTAjBgNV
// SIG // BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wi
// SIG // IwoBATAHBgUrDgMCGgMVAIyTny2W94r4qS97Ei5VhWy6
// SIG // 1o5koIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEm
// SIG // MCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // IDIwMTAwDQYJKoZIhvcNAQELBQACBQDsDJyiMCIYDzIw
// SIG // MjUwNjMwMDUxODI2WhgPMjAyNTA3MDEwNTE4MjZaMHQw
// SIG // OgYKKwYBBAGEWQoEATEsMCowCgIFAOwMnKICAQAwBwIB
// SIG // AAICCyQwBwIBAAICEf0wCgIFAOwN7iICAQAwNgYKKwYB
// SIG // BAGEWQoEAjEoMCYwDAYKKwYBBAGEWQoDAqAKMAgCAQAC
// SIG // AwehIKEKMAgCAQACAwGGoDANBgkqhkiG9w0BAQsFAAOC
// SIG // AQEAGn5GFtNP5Z4IqxsGf6A+yRDvI0ON95CCSFRTgmFk
// SIG // WrQ4Sj8Sg6VLIBUOQrF0g2dmBVQHjgc6sdeCNP+SGt2t
// SIG // t2u+d278qokoHM6XhuooVRMmX8dovF/0NDW8SJnouabi
// SIG // GeZXdKPpm0VNEm3LKi4zpFTqg8VG2ZOuEk6FJJmhaPsr
// SIG // dBiO3UFG1EekUMPiivgv7II0XIQyRnxhS50mVfnWgkw8
// SIG // U073taQ5Y8nMQ3yow0Mq2bfdSRrlFIXXMs6IhqGNDsG5
// SIG // J6Ctp2PqpeZpQmys9wiFKnd117OncH8Qm5f///p54Ptk
// SIG // 3g6TWe3tX3II9F7jLKGHPKsVJwpahB+bR8jJijGCBA0w
// SIG // ggQJAgEBMIGTMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
// SIG // EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
// SIG // HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAk
// SIG // BgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAy
// SIG // MDEwAhMzAAACAAvXqn8bKhdWAAEAAAIAMA0GCWCGSAFl
// SIG // AwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZIhvcN
// SIG // AQkQAQQwLwYJKoZIhvcNAQkEMSIEIGjm383Levpyiy7q
// SIG // iH22/7Nh+EKpmsEBLCtJMe9hmEVxMIH6BgsqhkiG9w0B
// SIG // CRACLzGB6jCB5zCB5DCBvQQg1Mjt7DWd27qwTQxlAleD
// SIG // XzNoB+GlrkbnSJP/SgJP2ScwgZgwgYCkfjB8MQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQg
// SIG // VGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAgAL16p/GyoX
// SIG // VgABAAACADAiBCC/WO+lgw4JUqcsc4DDpow/deqRuYCB
// SIG // bvW6SICnwx6+4jANBgkqhkiG9w0BAQsFAASCAgBT/Nug
// SIG // eJJ1Wiu0orVS8U3P+zepTPWl+/RS/TgbfAOgUvpdUg+U
// SIG // HcelNji5rshB+ZnpeZoWSWS78RUNh7HTv9ITA5Mhl6bu
// SIG // ps1Cr5wR1aO54oVxHMKe4be5H4CwQoqPFovDYSw6Oaf7
// SIG // 6gd/UCqgEMjmy1/EKMQsZCxJiBqmQEnjDPVvcmcWiPeg
// SIG // 8d+CgepaLnOdJOOY8ZjnXN/vEd5WRIMB5ylTwXZWUJ+W
// SIG // tJY6fSmt0vm/9U0c8Lfn3u6azg5glhNOSR7Qsuckujs3
// SIG // jSzWfyptMgC4kOdRxA21zJNsS9DAmkhda7ciEhEBqmee
// SIG // Fx7c44WFEMONMZCyU6NIFESbS3uQTb1RG5VTckGzeRQ8
// SIG // /GPhfdu8EdWSMT4ftm9M/n5xxuM8vCF3q2w45j9THRu7
// SIG // QFeG/Ey1s8IElih/9mGoRjbVgfhIOYui6VIOkD/3gxqA
// SIG // qcmXKmlKQ5dNQs5nA5c45qfg4gAjLdukGV/6yWvhqy6T
// SIG // q2Un14UfUv6DflhIw0Nz2zg0Nw6ick5vHUySBZvDp6fz
// SIG // H9KTWuhngAblzvehaIcQXVauxwX1maN66X2jzMdLp645
// SIG // c61YRHMlJA0bo92TJeRA2bd+OVcyTMLhixxymuIRbIXd
// SIG // Ionhl97j0WspPEt9jE2YA1lAItJ9MIgAweIPVoQJOnk/
// SIG // G/kKxYShhVG842/A+g==
// SIG // End signature block
